- std/core/artifacts/artifact.bri
- std/core/artifacts/directory.bri
- std/core/artifacts/file.bri
- std/core/runtime.bri
This is a companion PR to brioche-dev/brioche#7
> Update `Directory` artifacts to use blobs

- packages/eza/brioche.lock
- packages/eza/project.bri
Package [eza](https://github.com/eza-community/eza) as a Brioche package. Nothing more. And it was pretty straightforward.
> feat: Add brioche.lock and project.bri files for eza package

- packages/dust/brioche.lock
- packages/dust/project.bri
- packages/oha/brioche.lock
- packages/oha/project.bri
- packages/tokei/brioche.lock
- packages/tokei/project.bri
- packages/xsv/brioche.lock
- packages/xsv/project.bri
- packages/zoxide/brioche.lock
- packages/zoxide/project.bri
Add:
- dust
- oha
- tokei
- xsv
- zoxide
> Add few additional packages

- packages/go/project.bri
- packages/pv/brioche.lock
- packages/pv/project.bri
Add [pv](http://ivarch.com/programs/pv.shtml) tool as a Brioche package + resolve a typo in a Go file
> Add pv package

- packages/jq/project.bri
- packages/nodejs/project.bri
- packages/openssl/project.bri
I did two modifications separated in two commits. Please let me know for the second one, I could revert it if it was really necessary.
> Unify package recipes

- packages/rust/project.bri
Work on https://github.com/brioche-dev/brioche-packages/issues/31
> feat: add the possibility to specify deps during building a rust crate

- packages/rust/project.bri
- packages/xplr/brioche.lock
- packages/xplr/project.bri
Package [xplr](https://github.com/sayanarijit/xplr)
Based on top of the work done here: https://github.com/brioche-dev/brioche-packages/pull/41
> Add xplr package

- .github/workflows/ci.yml
It should resolve https://github.com/brioche-dev/brioche-packages/issues/44 by checking if the packages are well formatted in each PR.
> feat: run brioche code formatter in CI workflow

- packages/lurk/brioche.lock
- packages/lurk/project.bri
Add [lurk](https://github.com/JakWai01/lurk) package, which is basically a rust alternative to strace. I tried this package while working on this issue #45
> feat: add lurk package

- packages/go/project.bri
I just updated go to the latest version available.
> feat: update go version to 1.22.5

- packages/carapace/brioche.lock
- packages/carapace/project.bri
- packages/go/project.bri
Based on top of #54 
Add the [carapace](https://github.com/carapace-sh/carapace-bin) package to Brioche
> feat: add carapace package

- packages/go/project.bri
- packages/k9s/brioche.lock
- packages/k9s/project.bri
Based on top of https://github.com/brioche-dev/brioche-packages/pull/54
Add the [k9s](https://github.com/derailed/k9s) package to Brioche
> feat: add k9s package

- examples/go_cli/project.bri
- examples/nodejs_frontend/project.bri
- examples/rust_backend/project.bri
- packages/bat/project.bri
- packages/broot/project.bri
- packages/carapace/project.bri
- packages/dust/project.bri
- packages/eza/project.bri
- packages/go/project.bri
- packages/joshuto/project.bri
- packages/jwt_cli/project.bri
- packages/k9s/project.bri
- packages/lurk/project.bri
- packages/miniserve/project.bri
- packages/nodejs/project.bri
- packages/nushell/project.bri
- packages/oha/project.bri
- packages/opentofu/project.bri
- packages/rust/project.bri
- packages/tokei/project.bri
- packages/xplr/project.bri
- packages/xsv/project.bri
- packages/zoxide/project.bri
Unify the build options to help to better use the current helpers across different languages.
> [Package] Normalize build package options

- packages/gitui/brioche.lock
- packages/gitui/project.bri
This PR adds a new `gitui` package for [GitUI](https://github.com/extrawurst/gitui). I built this off of the work from #38, where the package was originally included but was deferred until #43 was resolved
> Add GitUI package

- packages/wasmtime/brioche.lock
- packages/wasmtime/project.bri
This PR adds a new package for the WebAssembly runtime [Wasmtime](https://wasmtime.dev/)
> Add `wasmtime` package

- packages/moreutils/brioche.lock
- packages/moreutils/project.bri
This PR adds a new package for [moreutils](https://joeyh.name/code/moreutils/), which is a collection of a some convenient Unix-y tools (my favorite is `sponge`)
> Add `moreutils` package

- packages/fx/brioche.lock
- packages/fx/project.bri
This PR adds a new package for [Fx](https://fx.wtf/), a TUI / CLI for viewing and processing JSON
> Add `fx` package

- packages/opentofu/brioche.lock
- packages/opentofu/project.bri
Updates OpenTofu to v1.9.0 and adds in a test to validate functionality.
> Update OpenTofu to v1.9.0

- packages/just/brioche.lock
- packages/just/project.bri
What the PR message says :D
I got inspired to do this from the Discord :3
> Add `just` package

- packages/broot/brioche.lock
- packages/broot/project.bri
Update broot package to the latest release
> chore: update broot to version 1.44.6

- packages/ca_certificates/brioche.lock
- packages/ca_certificates/project.bri
Update Ca Certs to the latest release
> fix: update CA certificates to version 2024-12-31

- packages/carapace/brioche.lock
- packages/carapace/project.bri
> feat: update carapace to version 1.1.1

- packages/eza/brioche.lock
- packages/eza/project.bri
Update eza to the latest release
> feat: update eza to version 0.20.17

- packages/k9s/brioche.lock
- packages/k9s/project.bri
Update K9s package to latest release
> fix: update k9s to version 0.32.7

- packages/jwt_cli/brioche.lock
- packages/jwt_cli/project.bri
Update JWT cli package to the latest release
> fix: update jwt_cli to version 6.2.0

- packages/go/brioche.lock
- packages/go/project.bri
Update go package to the latest release
> feat: update Go version to 1.23.5

- packages/git/brioche.lock
- packages/git/project.bri
Update git package to the latest release
> feat: update git to version 2.48.1

- packages/lurk/brioche.lock
- packages/lurk/project.bri
Just update to the latest release
> feat: update lurk to version 0.3.9

- packages/nodejs/brioche.lock
- packages/nodejs/project.bri
> feat: update nodejs to version 23.6.1

- packages/moreutils/brioche.lock
- packages/moreutils/project.bri
> feat: update moreutils to version 0.70

- packages/libxml2/brioche.lock
- packages/libxml2/project.bri
> feat: update libxml2 to version 2.13.5

- packages/amber/project.bri
This is part of the POC for https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165 functionalities.
> feat: add auto-update functionality and improve test script in amber package

- packages/alsa_lib/project.bri
- packages/libpsl/brioche.lock
- packages/libpsl/project.bri
Part of https://github.com/brioche-dev/brioche-packages/issues/188. Add the initial libels package with auto update and test features.
> feat(libpsl): add initial package

- packages/broot/project.bri
This is part of the POC for https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165 functionalities.
> feat(broot): add auto update and testing functions

- packages/bat/project.bri
Just add the autoUpdate function for https://github.com/brioche-dev/brioche/issues/165.
> feat(bat): add autoUpdate function to fetch latest version from GitHub

- packages/alsa_lib/project.bri
- packages/amber/project.bri
- packages/just/project.bri
- packages/jwt_cli/project.bri
- packages/nushell/project.bri
- packages/ripgrep/project.bri
- packages/ruff/project.bri
- packages/xsv/project.bri
This pull request includes a few changes to improve consistency of the codebase by removing unnecessary template literals in various files.
> Refactor packages for consistency

- packages/carapace/project.bri
Part of https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165.
> feat(carapace): add autoUpdate and test functions for version management

- packages/nasm/brioche.lock
- packages/nasm/project.bri
Hello, another package contribution :D
I needed this package while building some programs, so I decided to contribute it :3
> Add a `nasm` package

- packages/go/brioche.lock
- packages/go/project.bri
This updates go to the latest release as of today 1.24
> Update go to 1.24.0

- packages/nushell/brioche.lock
- packages/nushell/project.bri
This PR adds test and autoUpdate functions for the nushell package, as part of https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165
> Nushell poc

- packages/aws_cli/brioche.lock
- packages/aws_cli/project.bri
- packages/broot/brioche.lock
- packages/broot/project.bri
- packages/carapace/brioche.lock
- packages/carapace/project.bri
- packages/claude_code/project.bri
- packages/eza/brioche.lock
- packages/eza/project.bri
- packages/github_cli/brioche.lock
- packages/github_cli/project.bri
- packages/seaweedfs/brioche.lock
- packages/seaweedfs/project.bri
This PR includes several version updates for various projects. Thanks to the autoUpdate methods !
> Update packages with auto update

- packages/asciinema/project.bri
- packages/cmake/project.bri
- packages/dust/project.bri
- packages/fd/project.bri
- packages/fx/project.bri
- packages/gitui/project.bri
- packages/joshuto/project.bri
- packages/just/project.bri
- packages/jwt_cli/project.bri
- packages/k9s/project.bri
- packages/libffi/project.bri
- packages/lurk/project.bri
- packages/miniserve/project.bri
- packages/nasm/project.bri
- packages/oha/project.bri
- packages/oniguruma/project.bri
- packages/opentofu/project.bri
- packages/pcre2/project.bri
- packages/proot/project.bri
- packages/pstack/project.bri
- packages/ruff/project.bri
- packages/terraform/project.bri
- packages/vdeplug4/project.bri
- packages/wasmtime/project.bri
- packages/xplr/project.bri
- packages/xsv/project.bri
- packages/zoxide/project.bri
Almost all the GitHub projects do now contain an `autoUpdate` method.
Part of https://github.com/brioche-dev/brioche/issues/165
> Add auto update method for GitHub projects 

- packages/rust/brioche.lock
- packages/rust/project.bri
This PR updates the Rust package to v1.86.0
> [rust] Update to v1.86.0

- packages/s2argv_execs/project.bri
```bash
bash-5.2$ brioche run -e autoUpdate -p packages/s2argv_execs/
Build finished, completed (no new jobs) in 3.95s
{
"name": "s2argv_execs",
"version": "1.4"
}
bash-5.2$ brioche build -e test -p packages/s2argv_execs/
2094   │ Hello, World!
0.76s ✓ Process 2094
Build finished, completed 1 job in 23.08s
Result: ae9e539b35679544b1bf809d1af4d7c5309ac62a01dc2aa83064a5d5fca578ad
```
> feat(s2argv_execs): add test and auto-update functions

- packages/opentofu/project.bri
```bash
bash-5.2$ brioche run -e autoUpdate -p packages/opentofu
Build finished, completed (no new jobs) in 2.78s
{
"name": "opentofu",
"version": "1.9.0"
}
bash-5.2$ brioche build -e test -p packages/opentofu
Build finished, completed (no new jobs) in 2.26s
Result: 3f50a83cceed641e1227170beeb96b0941156567866b9bab0b6c41ef843eabe9
```
> feat(opentofu): add test capability

- packages/joshuto/project.bri
```bash
[container@f1fcb7d2edd4 workspace]$ brioche run -e autoUpdate -p packages/joshuto/
Build finished, completed (no new jobs) in 2.54s
{
"name": "joshuto",
"version": "0.9.8"
}
[container@f1fcb7d2edd4 workspace]$ brioche build -e test -p packages/joshuto/
Build finished, completed (no new jobs) in 2.23s
Result: ac1ed278170e3fdf385f1c0a1bda548f55241a863cb07ca3a07201991dcc5c3a
```
> feat(joshuto): add test function to validate version output

- packages/libxslt/brioche.lock
- packages/libxslt/project.bri
```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/libxslt/
{
"name": "libxslt",
"version": "1.1.43",
"extra": {
"majorVersion": "1",
"minorVersion": "1"
}
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/libxslt
Build finished, completed (no new jobs) in 1.83s
Result: 0b39275e89f7c6ed34b927baf53e28b6888ca2147a5237296eff4ac965511648
```
> feat(libxslt): add test and autoUpdate capabilities

- packages/git/project.bri
```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/git
0.07s ✓ Process 13550
Build finished, completed 1 job in 3.47s
{
"name": "git",
"version": "2.49.0"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/git
Build finished, completed (no new jobs) in 1.65s
Result: 34a5f76ed15f91c31fe2588b010f05825ea57813c35e66c52253b3e1e8dbf43d
```
> feat(git): add test and autoUpdate capabilities

- packages/pcre2/project.bri
```bash
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/pcre2
Build finished, completed (no new jobs) in 1.82s
Result: c02ab8bbc340bef42aba61b6ac40901093cdbde2d240d45f3130919d7b63937f
```
> feat(pcre2): add test capability

- packages/asciinema/project.bri
```bash
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/asciinema/
Build finished, completed (no new jobs) in 1.83s
Result: 3acb892c5cc3d246852b0ff0a0e8096faec8cf00e5b82adfa515159945cf636b
```
> feat(asciinema): add test capability

- packages/curl/brioche.lock
- packages/curl/project.bri
Resolve https://github.com/brioche-dev/brioche-packages/issues/188
> feat(curl): add libpsl as a dependency in project.bri

- packages/rust/project.bri
```bash
[container@c734a75a8076 workspace]$ brioche run -e autoUpdate -p packages/rust
0.06s ✓ Process 9949
Build finished, completed 1 job in 3.71s
{
"name": "rust",
"version": "1.86.0"
}
```
> feat(rust): add test capability

- packages/proot/brioche.lock
- packages/proot/project.bri
- packages/uthash/brioche.lock
- packages/uthash/project.bri
For uthash package:
```bash
[container@c734a75a8076 workspace]$ brioche build -e test -p packages/uthash/
Build finished, completed (no new jobs) in 1.77s
Result: cfac8462ba7832779deb696a39a940b178d432b332a6fb2d671c79a93c6fa5d3
[container@c734a75a8076 workspace]$ brioche run -e autoUpdate -p packages/uthash/
Build finished, completed (no new jobs) in 2.31s
{
"name": "uthash",
"version": "2.3.0"
}
```
For proot package:
```bash
[container@c734a75a8076 workspace]$ brioche build -e test -p packages/proot/
Build finished, completed (no new jobs) in 2.19s
Result: f07563a3cefd0b4ed5d903f64ef8cc7777ccadd12122f27d1e65ea97bbb81d49
```
> Update proot package

- packages/pcre/brioche.lock
- packages/pcre/project.bri
```bash
[container@c734a75a8076 workspace]$ brioche run -e autoUpdate -p packages/pcre
Build finished, completed (no new jobs) in 2.40s
{
"name": "pcre",
"version": "8.45"
}
[container@c734a75a8076 workspace]$ brioche build -e test -p packages/pcre
Result: 5cacf2ad67602972f604308c82420cfafee7fb7f38fe8a138b3441013a72ac44
```
> feat(pcre): add package

- packages/htop/brioche.lock
- packages/htop/project.bri
[htop](https://htop.dev/) is an interactive TUI process viewer-- basically an interactive version of `top`
> Add `htop` package

- packages/ninja/brioche.lock
- packages/ninja/project.bri
This PR adds a package for [Ninja](https://ninja-build.org/), a small and fast build system.
> Add `ninja` package

- packages/talloc/project.bri
```bash
[container@de5053fafebd workspace]$ brioche build -e test -p packages/talloc
Build finished, completed (no new jobs) in 1.87s
Result: 671745f8eceb9b8805be6a9eedb11b84747978dd2b9bfb53e45d9460d9f25bab
```
> feat(talloc): add test capability

- packages/pv/project.bri
```bash
[container@de5053fafebd workspace]$ brioche build -e test -p packages/pv
Build finished, completed (no new jobs) in 1.55s
Result: 4776d3d90b622bdd8ea15e8309533af4743083a55bd6083815465801c17f4f5b
```
> feat(pv): add test capability

- packages/scdoc/project.bri
```bash
[container@868094031ec6 workspace]$ brioche build -e test -p packages/scdoc/
Build finished, completed (no new jobs) in 1.74s
Result: d5b47cb10fae877baf94e888d22a5ac282e0659ec0cd5fada9756e070f15b01d
```
> feat(scdoc): add test capability

- packages/tcsh/project.bri
```bash
[container@07115ffb5a58 workspace]$ brioche run -e liveUpdate -p packages/tcsh/
0.07s ✓ Process 51
Build finished, completed 1 job in 3.76s
{
"name": "tcsh",
"version": "6.24.15"
}
```
> feat(tcsh): add liveUpdate capability

- packages/pv/project.bri
```bash
[container@07115ffb5a58 workspace]$ brioche run -e liveUpdate -p packages/pv
0.06s ✓ Process 156
Build finished, completed 1 job in 3.25s
{
"name": "pv",
"version": "1.9.31"
}
```
> feat(pv): add liveUpdate capability

- packages/zlib/brioche.lock
- packages/zlib/project.bri
Add a new package [`zlib`](https://zlib.net): A Massively Spiffy Yet Delicately Unobtrusive Compression Library
```bash
[container@07115ffb5a58 workspace]$ brioche run -e liveUpdate -p packages/zlib
Build finished, completed (no new jobs) in 2.54s
{
"name": "zlib",
"version": "1.3.1"
}
[container@07115ffb5a58 workspace]$ brioche build -e test -p packages/zlib
Result: 427dfa60b822651ca8542553070c63173e61643fd84217b5f74552f834efb265
```
> feat(zlib): add package

- packages/alsa_lib/project.bri
- packages/asciinema/project.bri
- packages/aws_cdk/project.bri
- packages/bubblewrap/project.bri
- packages/ca_certificates/project.bri
- packages/llvm/project.bri
- packages/s2argv_execs/project.bri
- packages/vdeplug4/project.bri
Two things here:
1. Begin to make use of use std.pipe(), but it's just the beginning !
2. Properly extract the source to a const variable for ca_certificates package.
> Quick follow up due to recent MRs

- packages/libpng/brioche.lock
- packages/libpng/project.bri
Add a new package [`libpng`](http://www.libpng.org/pub/png/libpng.html)
```bash
[container@b2a31d2f54d4 workspace]$ brioche-live-update packages/libpng/
Build finished, completed (no new jobs) in 5.90s
{
"name": "libpng",
"version": "1.6.48"
}
[container@b2a31d2f54d4 workspace]$ brioche-test packages/libpng/
Result: 3671e6adc1ba469a0a7335a109ff56aa6e71e74acd88c61850b8687bf1df95d9
```
> feat(libpng): add package

- packages/difftastic/brioche.lock
- packages/difftastic/project.bri
This PR adds a package for [difftastic](https://github.com/Wilfred/difftastic), a human-readable semantic diff tool
> Add `difftastic` package

- .github/workflows/_build.yml
- .github/workflows/_check.yml
- .github/workflows/build.yml
- .github/workflows/live-updates.yml
Resolve #429 by implementing the quick and dirty option. Tested inside a Ubuntu 22.04 docker container:
```bash
container@9a7deaa1699e:/workspace$ packages_glob="packages/*"
container@9a7deaa1699e:/workspace$ packages=( $packages_glob )
container@9a7deaa1699e:/workspace$ echo "${packages[@]}"
packages/alsa_lib packages/amber packages/asciinema packages/aws_cdk packages/aws_cli packages/bat packages/biome packages/broot packages/brotli packages/bubblewrap packages/bugstalker packages/ca_certificates packages/caddy packages/carapace packages/cargo_nextest packages/claude_code packages/cmake packages/codex packages/curl packages/dasel packages/difftastic packages/dust packages/eks_node_viewer packages/expat packages/eza packages/fd packages/fx packages/fzf packages/giflib packages/git …
```
> Shuffle live update packages

- packages/cargo_nextest/project.bri
- packages/rust/project.bri
- packages/sqlite/project.bri
- packages/uv/project.bri
This pull request includes minor updates to comments and dependencies in several files to improve clarity and correctness. The most important changes include clarifying comments about `cargo-chef`, updating dependency references, and refining a TODO comment for better guidance.
> Minor updates extracted from local changes

- packages/openssl/project.bri
See the comment in https://github.com/brioche-dev/brioche-packages/pull/595 for more understanding
> chore(openssl): specialize CMAKE_PREFIX_PATH env var

- packages/inframap/brioche.lock
- packages/inframap/project.bri
Adding: [Inframap](https://github.com/cycloidio/inframap)
> feat(inframap): add package

- packages/helix/brioche.lock
- packages/helix/project.bri
add a package for https://helix-editor.com/
> feat(helix): 📦️ add package

- packages/libdnet/brioche.lock
- packages/libdnet/project.bri
Add a new package `libdnet`: 
```bash
Build finished, completed (no new jobs) in 0.84s
Result: 7da2d1ea8410bc3050048c5077f6939a74fb27f08002a04a52b56a9754c3c0ed
```
```bash
Build finished, completed 1 job in 10.74s
{
"name": "libdnet",
"version": "1.18.0",
"repository": "https://github.com/ofalk/libdnet"
}
```
> feat(libdnet): add package
