std/core/artifacts/process.bri
std/core/runtime.bri
std/toolchain/stage0/index.bri

This PR makes a few minor changes based on recent changes in [Brioche](https://github.com/brioche-dev/brioche);
- Replace `runtime.LazyProxy.hash` field with `blob` (brioche-dev/brioche#12)
- Add new `outputScaffold` option to `std.process()` and corresponding change to `runtime.LazyProcess` (brioche-dev/brioche#13)
- Update `bootstrapRun` to use `workDir` where possible. This wasn't motivated by an upstream change, but this seemed like a good opportunity to make this change since I had to do a full rebuild of `std.native()` anyway...

Minor `std` changes to reflect upstream changes

---

std/core/runtime.bri

This PR updates the `std` package so that the `File.unpack()` method accepts a new compression type of `bzip2`. This corresponds with the upstream change from brioche-dev/brioche#15

Add `bzip2` decompression format

---

projects/std/core/recipes/process.bri
projects/std/core/runtime.bri

This is a companion PR to brioche-dev/brioche#33, which just updates `std.process` to take the new process fields of `networking` and `unsafe`. The types were tweaked so that `networking` can only be set if `unsafe` is set to true.

Update `std.process` to expose new `networking` and `unsafe` fields

---

projects/std/core/global.bri
projects/std/core/index.bri
projects/std/project.bri

Companion PR: brioche-dev/brioche#34
This PR updates the `std` package to define the new global constant `Brioche`, plus the function `Brioche.get(...)`. This is a special function that works with the Brioche runtime to allow loading an artifact from a local path relative to the current module. It's defined as a global because the runtime needs special awareness of this function.
I tried to make the implementation pretty defensive when setting `Brioche.get`-- it's only set if it's currently undefined. I figured this might save some headache in the future if we end up in a state where we have multiple versions of `std` loaded at once (which will probably cause mayhem with this feature). If we want to handle that case, future versions of `std` can set `Brioche.get` globally, which will take …

Add `Brioche.get` global in `std`

---

projects/std/core/global.bri

Companion PR: brioche-dev/brioche#35
This PR is a follow-up to #7, replacing the function `Brioche.get(...)` with `Brioche.includeFile` and `Brioche.includeDirectory` instead to match the upstream change from brioche-dev/brioche#35

Replace `Brioche.get` with `Brioche.includeFile` / `Brioche.includeDirectory`

---

projects/std/core/recipes/process.bri
projects/std/core/runtime.bri

This PR adds the new `dependencies` option to the function `std.process()`, to match the changes upstream. See brioche-dev/brioche#38

Add `dependencies` option to `std.process`

---

projects/std/core/global.bri

This PR provides an implementation for `Brioche.glob` from `std`. See brioche-dev/brioche#40

Add implementation for `Brioche.glob` global function

---

projects/std/core/recipes/process.bri
projects/std/core/runtime.bri
projects/std/pack_tools.bri
projects/std/toolchain/stage0/index.bri

This PR updates `std` to match the changes from this upstream PR: brioche-dev/brioche#42
- Update template components
- Remove `std.resourcesDir` symbol (plural)
- Add `std.resourceDir` (singular) and `std.inputResourceDirs` symbol
- Update default env vars set by `std.process()`
- Remove `$BRIOCHE_PACK_RESOURCES_DIR`
- Add `$BRIOCHE_RESOURCE_DIR` and `$BRIOCHE_INPUT_RESOURCE_DIRS`
- Update pack tools to a version that handles these changes

Update `std` to reflect changes to resource dirs

---

projects/curl/brioche.lock
projects/curl/project.bri

This PR adds a new package for Curl, pretty self-explanatory!
Note that Curl does **not** provide CA certificates out of the box! Since the build sandbox doesn't (currently?) include CA certs from the host, you need to bring your own when using Curl in a build. The easiest way to do that is to use the `ca_certificates` package as a dependency as well:
```ts
import * as std from "std";
import curl from "curl";
import caCertificates from "ca_certificates";
export default () => {
return std.runBash`
curl -L 'https://example.com' -o "$BRIOCHE_OUTPUT"
`
.dependencies(curl(), caCertificates())
.unsafe({ networking: true });
};
```

Add Curl package

---

projects/ca_certificates/brioche.lock
projects/ca_certificates/project.bri

This PR adds a new `ca_certificates` package. This provides a bundle of CA certificates from Mozilla (the same bundle endorsed by Curl and used by lots of other package managers, as far as I can tell).
When used as a dependency, it sets the `$SSL_CERT_FILE` env var, which OpenSSL (and others) can use to verify TLS / HTTPS certificates

Add `ca_certificates` package

---

projects/nodejs/brioche.lock
projects/nodejs/project.bri

This PR adds a new `nodejs` package.
- The default export can be used as a dependency, giving the `node` and `npm` binaries
- `nodejs.npmInstall()` takes an NPM package and downloads the dependencies while verifying the lockfile is up-to-date, returning the same package with a `node_modules` directory. It's effectively equivalent to running `npm install`.
This package does not currently build from source-- instead, it downloads and wraps an official Node.js binary. In the future, this will probably be replaced with a from-source build.
```ts
import * as std from "std";
import node, { npmInstall } from "nodejs";
export default () => {
const npmPackage = npmInstall(
Brioche.glob("package.json", "package-lock.json", "src"),
);
return std.runBash`
node src/index.js
`
.workDir(npmPackage) …
```

Add Node.js package (binary-only)

---

projects/rust/brioche.lock
projects/rust/project.bri
projects/smol_toml/brioche.lock
projects/smol_toml/date.bri
projects/smol_toml/error.bri
projects/smol_toml/extract.bri
projects/smol_toml/index.bri
projects/smol_toml/parse.bri
projects/smol_toml/primitive.bri
projects/smol_toml/project.bri
projects/smol_toml/stringify.bri
projects/smol_toml/struct.bri
projects/smol_toml/util.bri
projects/typer/project.bri

This PR adds a new `rust` package:
- Using the default export as a dependency gives you `rustc` and `cargo`, among other standard Rust binaries
- The function `rust.cargoBuild()` lets you build a crate, including caching dependency downloads and validating the lockfile is up to date
Rather than build from source, the current version of the `rust` package installs Rust by downloading a manifest file (the same one used by Rustup) and calling the `install.sh` file for each desired component. This ends up using the official Rust binaries.
To parse the manifest, I had to make two other changes:
- Add `typer.record()` function for parsing objects based on key/value type
- Add `smol_toml` package. The Rustup manifests are TOML, so to parse them, I vendored the …

Add Rust package (binary-only)

---

projects/std/extra/index.bri
projects/std/extra/oci_container_image.bri

This PR adds a new `std.ociContainerImage` function. As the name implies, it builds an OCI container image, compatible with container runtimes like Docker and Podman.
It takes two arguments:
- `recipe`: The recipe to use as the root of the container image
- `entrypoint` (optional): The container's entrypoint. Defaults to `["/brioche-run"]`

Add `std.ociContainerImage` function

---

packages/nodejs/project.bri
packages/rust/project.bri
packages/std/core/global.bri
packages/std/core/recipes/directory.bri
packages/std/core/recipes/download.bri
packages/std/core/recipes/file.bri
packages/std/core/recipes/hash.bri
packages/std/core/recipes/process.bri
packages/std/core/recipes/proxy.bri
packages/std/core/recipes/recipe.bri
packages/std/core/recipes/symlink.bri
packages/std/core/recipes/sync.bri
packages/std/core/utils.bri
packages/std/extra/autowrap.bri
packages/std/extra/bash_runnable.bri
packages/std/extra/oci_container_image.bri
packages/std/extra/run_bash.bri
packages/std/extra/set_env.bri
packages/std/extra/with_runnable_link.bri
packages/std/project.bri
packages/std/toolchain/index.bri
packages/std/toolchain/native/index.bri

This PR adds documentation to most inline functions, as well as a few minor tweaks to the `rust.cargoBuild()` function (namely, removing the `profile` and `toolchain` options; the former wasn't actually used and the latter is... more complex).

Add inline documentation for most functions

---

packages/std/toolchain/native/mpfr.bri

This PR adjusts the build for `mpfr` used in `std.toolchain()`. The previous iteration called `std.recipeFn()`, which internally called `.bake()` on the recipe. This made it so everything before this point in the build would need to fetch, including the earlier stages of the build.
Now, we use a basic process with a `sed` command. This handles the work lazily, in a way that allows the client to pull a lot less from the registry.
Here's a comparison before:
```sh-session
$ time brioche run -r hello_world
[100%] Fetched 2 blobs + 10 recipes from registry
[100%] Fetched 11323 blobs + 14295 recipes from registry
[100%] Fetched 687 blobs + 1609 recipes from registry
Build finished, completed 73 jobs in 9:19.5
Hello, world!
real    9m19.513s
user    0m28.139s
sys …
```

Tweak `mpfr` build in `std.toolchain()` to speed up initial setup

---

packages/jq/brioche.lock
packages/jq/project.bri

Pretty self-explanatory. This adds a new `jq` package, which includes `bin/jq`.
Because `std.toolchain()` doesn't set all the variables needed for autotools builds, the build definition is a little hacky and needs to set a bunch of env vars manually (similar to what `std` itself does).

Add jq package

---

packages/std/core/console.bri
packages/std/core/index.bri
packages/std/core/recipes/collect_references.bri
packages/std/core/recipes/index.bri
packages/std/core/recipes/recipe.bri
packages/std/core/runtime.bri
packages/std/extra/oci_container_image.bri

This PR exposes a few upstream features, and uses them to make OCI container images smaller:
- Add `std.BRIOCHE_VERSION` export. This uses the ops introduced in brioche-dev/brioche#59 / brioche-dev/brioche#60 to return the current Brioche version. This is useful for feature-gating things that depend on new Brioche versions
- Since this op wasn't present on v0.1.0, we set the version to v0.1.0 if the op is not present
- Add new `std.collectReferences()` function. It takes a directory recipe and returns a new directory recipe that explicitly includes a `brioche-resources.d` directory. This is useful creating self-contained tarballs of recipes, e.g. for OCI container images
-  This is feature-gated for Brioche >=v0.1.1 (v0.1.1 should go out very shortly)
- Update `std.ociContainerImage()` to …

Add some upstream changes + make OCI images smaller

---

examples/rust_backend/README.md
packages/std/extra/oci_container_image.bri

This PR updates the `std.ociContainerImage` function used to create a container image, so that the resulting image is compatible with `docker load`. This was done by adding a new `manifest.json` file to the root of the image, which conforms to the format specified in [Docker Image Specification v1.3.0](https://github.com/moby/docker-image-spec/blob/f1d00ebd2d6d6805170d5543dbca4b850f35f9af/spec.md). It turns out `docker load` doesn't directly support OCI container images, but the `manifest.json` format is easy enough to add in a way that's still OCI compatible. The result is both a valid OCI container image and Docker image.
(I was also concerned such a combined image would have problems with multi-platform images, but it seems like this same format will work for multi-platform images too …

Update `std.ociContainerImage` to support Docker

---

packages/rust/project.bri

Nothing else, except a really really small refactor to use package.version variable.

Update rust to 1.79.0

---

packages/rust/project.bri

Resolve the issue https://github.com/brioche-dev/brioche-packages/issues/32.
Before:
```rust
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=-stack:10000000", "-C", "target-feature=+crt-static"]
[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=apple-m1"][source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
```
After:
```rust
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=-stack:10000000", "-C", "target-feature=+crt-static"]
[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=apple-m1"]
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
```

Append newline when vendoring Rust dependencies

---

packages/openssl/project.bri

Needed to build the Nushell tool, otherwise this error is emitted:
```
error: failed to run custom build command for `openssl-sys v0.9.102`
Caused by:
process didn't exit successfully: `/home/brioche-runner-c6d4477cc819ddcba40e878ffddbe16cd5781b95641aa1b868d2536c156545f2/work/target/release/build/openssl-sys-ec786e98e368251d/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset …
```

feat: expose PKG_CONFIG_PATH in OpenSSL package

---

packages/rust/project.bri

Resolves #39 
The issue was described in [this comment](https://github.com/brioche-dev/brioche-packages/issues/39#issuecomment-2208214878), but basically the problem boils down to the `cargo vendor` command creating a new `.cargo/config.toml` file, while the crate contained a `.cargo/config` file. When this happens, Cargo prefers `.cargo/config`, meaning the config from `cargo vendor` was being ignored.
The fix I went with was to move `.cargo/config` to `.cargo/config.toml` if it exists in the crate before vendoring. After we merge the vendored crate with the original, we then remove `.cargo/config`, since `.cargo/config.toml` would have the final config by this point. I'm not confident this is the cleanest solution to the problem, but it seems fix the issue seen when trying to build …

Fix `cargoBuild()` failing when crate contains file `.cargo/config`

---

packages/rust/project.bri

Closes #40
This PR adds a new `path` option. When set, this specifies a subpath for the crate to build, and is passed as `--path` to the `cargo install` invocation (in this case, the `crate` argument is expected to be a Cargo workspace). This works well for Rust software that is broken up into different crates, including [ripgrep](https://github.com/BurntSushi/ripgrep), [Yazi](https://github.com/sxyazi/yazi), and [Brioche](https://github.com/brioche-dev/brioche)

[Rust] Add `path` option to `cargoBuild()`

---

packages/go/project.bri

The commit adds new options to the `GoBuildOptions` interface in the `go` package. The `buildParams` option allows specifying build parameters such as running `go generate` before building and passing ldflags to the `go install` command. The `packagePath` option allows setting the package path to build. This change enhances the flexibility and customization of the `goInstall` function.

feat: add buildParams and packagePath options to GoBuildOptions interface

---

packages/jwt_cli/brioche.lock
packages/jwt_cli/project.bri

This PR adds a package for the [`jwt-cli`](https://github.com/mike-engel/jwt-cli) command-line tool. There's at least one other project with the same name, but the one from mike-engel seems to be the most popular and has the name in a few other package repositories.
The package includes the `jwt` binary, which is used for encoding and decoding JSON web tokens (JWTs)

Add `jwt-cli` package

---

packages/go/project.bri

- Added ModOptions to support the -mod flag
- Allow to pass environment variables to go build through `env` in BuildOptions
- Add `trimpath` boolean to set the trimpath flag.
- Clean up flag input to install command.

Add in more build options for go builds

---

packages/go/project.bri
packages/opentofu/project.bri

This created a problem where CGO kept trying to be used by default.

mistakenly added std.toolchain to go package

---

packages/carapace/project.bri
packages/go/project.bri
packages/opentofu/project.bri
packages/rust/project.bri

Two commits:
- first one to normalize the usage of `path` in GoBuildOptions interface to make it consistent with other interfaces
- second one to add the ability to set environment variables that could be injected in the `cargo install` command. Some crates rely on these env vars to be customized

[Package] Normalize install options

---

packages/curl/project.bri
packages/git/brioche.lock
packages/git/project.bri

- Fixes Curl first to add in libcurl to the curl package.
- Next adds in Git so future additions can be added to it.

Add in base for Git Package

---

packages/git/project.bri

Closes #43
This PR adds a new `gitCheckout` utility function to the `git` package. It takes a repository URL and a commit hash, and returns a recipe with the repo checked out with just that one commit. As mentioned in #43, this was based on the technique described in this article: https://blog.hartwork.org/posts/clone-arbitrary-single-git-commit/
The commit hash is validated to be a 40-character hex string to ensure that it's a full commit hash. This will prevent cloning from a branch/tag (which could change over time) or from a short commit hash (which could be ambiguous as more commits are added to the upstream repo).
Also, I updated the git package to set some environment variables that needed to be set to use git within Brioche (within the `gitCheckout` function specifically):
- …

[git] Add `gitCheckout` utility function

---

packages/bat/project.bri
packages/std/extra/run_bash.bri

Add a sort of unit test for `bat` package based on what was done with `openssl`. It helps to figure out if the package is at least built correctly with a basic test.
To run it (not for @kylewlacy since he knows it):
```bash
brioche build -p packages/bat -e test
```
If it suits you (@kylewlacy), I could do the same for the other packages.

[Bat] add a unit test

---

packages/eza/project.bri

Changelog:
- https://github.com/eza-community/eza/releases/tag/v0.18.21
- https://github.com/eza-community/eza/releases/tag/v0.18.22
Tested it locally:
```bash
bash-5.2$ brioche install -p packages/eza
[14352]    = note: `Attributes` has a derived impl for the trait `Clone`, but this is intentionally ignored during dead code analysis                                                                                                                                                                                                            
[14352] note: the lint level is defined here …
```

feat: Update eza package version to 0.18.22

---

packages/ca_certificates/project.bri

Update ca_certificates to "2024-07-02": https://curl.se/docs/caextract.html
Tested locally:
```bash
bash-5.2$ brioche install -p packages/ca_certificates
[100%] Downloaded https://curl.se/ca/cacert-2024-07-02.pem
Build finished, completed 1 job in 1.8s
Writing output
bash-5.2$ ls /home/container/.local/share/brioche/installed
bin  brioche-env.d  brioche-resources.d  etc
bash-5.2$ cat /home/container/.local/share/brioche/installed/etc/ssl/certs/ca-bundle.crt 
##
##
##
##
##
##
....
....
....
```

feat: update ca_certificates version to "2024-07-02"

---

packages/broot/project.bri

I updated the broot package to 1.40.0
Changelog: https://github.com/Canop/broot/releases/tag/v1.40.0
Tested locally:
```bash
bash-5.2$ brioche install -p packages/broot
[133]    Compiling uzers v0.11.3                                                                                                                                                                                                                                                                                                                 
[133]    Compiling memmap2 v0.9.4 …
```

feat: Update broot version to 1.40.0

---

packages/dust/project.bri

Changelog:
- https://github.com/bootandy/dust/releases/tag/v1.1.0
- https://github.com/bootandy/dust/releases/tag/v1.1.1
Tested it locally:
```bash
bash-5.2$ brioche install -p packages/dust
[13021]    Vendoring utf8parse v0.2.1 (/home/brioche-runner-4d1087269516ee993974aa044e40fe1dfb3d0be4c3e48e0c7252190e00878221/.cargo/registry/src/index.crates.io-6f17d22bba15001f/utf8parse-0.2.1) to vendor/utf8parse                                                                                                                            
[13021]    Vendoring wait-timeout v0.2.0 (/home/brioche-runner-4d1087269516ee993974aa044e40fe1dfb3d0be4c3e48e0c7252190e00878221/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wait-timeout-0.2.0) to vendor/wait-timeout …
```

feat: Update dust package version to 1.1.1

---

packages/jujutsu/brioche.lock
packages/jujutsu/project.bri

Add the tool [jujutsu](https://github.com/martinvonz/jj)
Tested with:
```bash
bash-5.2$ brioche install -p packages/jujutsu/           
Build finished, completed (no new jobs) in 2.18s
Writing output
bash-5.2$ jj --version
jj 0.19.0
```

feat: Add jujutsu package

---

packages/alsa_lib/brioche.lock
packages/alsa_lib/project.bri

Add [alsa-lib](https://github.com/astral-sh/ruff) tool.
There are two possibilities to get the source of alsa-lib:
- through git: https://github.com/alsa-project/alsa-lib
- through their website: https://github.com/alsa-project/alsa-lib
Following what is stated [here](https://github.com/alsa-project/alsa-lib/blob/master/INSTALL), the tarball archive from the website is already pre-configured to compile it, while the git sources needed another step to set up the build process by calling the script `gitcompile`. I decided to follow what is already done on [Nixpkgs store](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/al/alsa-lib/package.nix#L39) and on [Homebrew store](https://github.com/Homebrew/homebrew-core/blob/5d936da59a39bab63aad4edd3f6835673388bb27/Formula/a/alsa-lib.r …

feat: Add alsa-lib package

---

packages/ruff/brioche.lock
packages/ruff/project.bri

Add [ruff](https://github.com/astral-sh/ruff) tool. Based on @kylewlacy's comment https://github.com/brioche-dev/brioche/issues/103#issuecomment-2241778792.
Tested with:
```bash
bash-5.2$ brioche install -p packages/ruff     
[17205]    Compiling ruff_linter v0.5.3 (/home/brioche-runner-d5be76f5f48436b982fa26da047d369eb7ce00bff
eb3f7ee9ed26c61c43572c8/work/crates/ruff_linter)                                                       
[17205]    Compiling clap_complete_command v0.6.1                                                      
[17205]    Compiling cachedir v0.3.1                                                                   
[17205]    Compiling bincode v1.3.3                                                                    
[17205]    Compiling wild v2.2.1 …
```

feat: Add ruff package

---

packages/ripgrep/brioche.lock
packages/ripgrep/project.bri
packages/rust/project.bri

Package [ripgrep](https://github.com/BurntSushi/ripgrep).
Finally, I didn't need #81, since pcre2 library was built from the crate https://github.com/BurntSushi/rust-pcre2.
This PR also contains a new way to set cargo build option based on what's already done with go build parameters.

Add ripgrep package

---

packages/oniguruma/brioche.lock
packages/oniguruma/project.bri

Resolve #50 
Add [oniguruma](https://github.com/kkos/oniguruma) package.
Some hacks have been taken from #81, but it also contains two additional modifications:
1. `AUTOHEADER`is set as part of the `autotoolsEnv(). Without it, the tool wasn't found correctly
2. I also set `aclocal_dir` to give it as input to `autoreconf` to find correctly the tool `libtool`
Tested with:
```bash
bash-5.2$ brioche install -p packages/oniguruma                  
Build finished, completed (no new jobs) in 1.48s
Writing output
bash-5.2$ onig-config 
Usage: onig-config [OPTION]
Values for OPTION are:
--prefix[=DIR]       change prefix to DIR
--prefix             print prefix
--exec-prefix[=DIR]  change exec_prefix to DIR
--exec-prefix        print …
```

feat: Add oniguruma package

---

packages/pcre2/brioche.lock
packages/pcre2/project.bri

Resolve #45 
Package [pcre2](https://github.com/PCRE2Project/pcre2) which is a common library used by other tools such as `git`, `ripgrep`, etc.
The packaging is a bit hacky due to hard-coded paths in a few build scripts, see the discussion in the related issue #45.
```bash
bash-5.2$ brioche build -p packages/pcre2 -o /tmp/pcre2
Build finished, completed (no new jobs) in 2.76s
Result: 26526a47af9efabb19badc404039cf41aa89874b3bdd1d3bf37f39c743d4715d
Writing output
Wrote output to /tmp/pcre2
bash-5.2$ ls /tmp/pcre2
bin  brioche-env.d  brioche-resources.d  include  lib  share
bash-5.2$ ls /tmp/pcre2/lib/pkgconfig/
libpcre2-16.pc  libpcre2-32.pc  libpcre2-8.pc  libpcre2-posix.pc
```

feat: Add pcre2 package

---

packages/opentofu/project.bri

- This updates OpenTofu to [1.8.0 Updates in OpenTofu](https://github.com/opentofu/opentofu/releases/tag/v1.8.0)

Update opentofu to 1.8.0

---

packages/broot/project.bri

Changelog:
- https://github.com/Canop/broot/releases/tag/v1.41.0
- https://github.com/Canop/broot/releases/tag/v1.41.1
Tested with:
```bash
Process 103 [6:11.3 Exited 0]
Process 97 [14.03s Exited 0]
Process 95 [200.7ms Exited 0]
Build finished, completed 6 jobs in 7:09.6
Writing output
bash-5.2$ broot --version
broot 1.41.1
```

build: update broot version to 1.41.1

---

packages/carapace/project.bri

Changelog:
- https://github.com/carapace-sh/carapace-bin/releases/tag/v1.0.5
Tested with:
```bash
bash-5.2$ brioche install -p packages/carapace
Process 12934 [2:12.2 Exited 0]
Process 12923 [2.71s Exited 0]
[100%] Downloaded https://github.com/carapace-sh/carapace-bin/archive/refs/tags/v1.0.5.tar.gz
Build finished, completed 4 jobs in 2:55.2
Writing output
bash-5.2$ carapace --version
1.0.5
```

build: update carapace version to 1.0.5

---

packages/curl/project.bri

Changelog:
- https://curl.se/changes.html
Tested with:
```bash
53423f8941b5cbe61/work'                                                                                 
Process 22101 [19:01.6 Exited 0]
[100%] Downloaded https://curl.se/download/curl-8.9.1.tar.gz
[100%] Unarchived
Build finished, completed 3 jobs in 19:17.5
Writing output
bash-5.2$ curl --version
curl 8.9.1 (x86_64-pc-linux-gnu) libcurl/8.9.1 OpenSSL/3.3.1 zlib/1.2.13 zstd/1.5.5
Release-Date: 2024-07-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets zstd
```

build: update curl version to 8.9.1

---

packages/rust/project.bri

Changelog:
- https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html
Tested with:
```bash
bash-5.2$ brioche install -p packages/rust
Build finished, completed (no new jobs) in 1.98s
Writing output
bash-5.2$ rustc --version
rustc 1.80.0 (051478957 2024-07-21)
```

build: update rust version to 1.80.0

---

packages/eza/project.bri

Changelog:
- https://github.com/eza-community/eza/releases/tag/v0.18.23
- https://github.com/eza-community/eza/releases/tag/v0.18.24
Tested with:
```bash
bash-5.2$ eza --version
eza - A modern, maintained replacement for ls
v0.18.24 [+git]
https://github.com/eza-community/eza
```

build: update eza version to 0.18.24

---

packages/ruff/project.bri

Changelog:
- https://github.com/astral-sh/ruff/releases/tag/0.5.3
- https://github.com/astral-sh/ruff/releases/tag/0.5.4
- https://github.com/astral-sh/ruff/releases/tag/0.5.5
- https://github.com/astral-sh/ruff/releases/tag/0.5.6
Tested with:
```bash
bash-5.2$ ruff --version
ruff 0.5.6
```

build: update ruff version to 0.5.6

---

packages/joshuto/joshuto-v0.9.8.patch
packages/joshuto/project.bri
packages/miniserve/miniserve-v0.27.1.patch
packages/miniserve/project.bri

This PR adds some patches for the `joshuto` and `miniserve` packages to update their `Cargo.lock` files to fix a conflict between older versions of the `time` crate and Rust 1.80 (see time-rs/time#681 for more context).
Both Joshuto and miniserve have already been updated on their main branches to fix this issue, but neither fix had been in a released version yet. So, to come up with a patch, I bisected between the main branch and the release tag to find the first compiling commit, then made a patch by grabbing just the `Cargo.lock` from that commit. The commits I bisected to are below:
- https://github.com/kamiyaa/joshuto/commit/1245124fcd264e25becfd75258840708d7b8b4bb
- https://github.com/svenstaro/miniserve/commit/2fbfcbfe17b5c12630ccb03b6ccd31cb4b8316cc
These patches should go away …

Fix build errors from upgrade to Rust 1.80.0

---

packages/eza/project.bri

I had to use to same trick as with ruff package due to https://github.com/brioche-dev/brioche/issues/103

build: update eza version to 0.19.0

---

packages/std/core/index.bri
packages/std/core/recipes/collect_references.bri
packages/std/core/semver.bri
packages/std/extra/oci_container_image.bri

This PR adds a new `std.semverMatches` function, which takes a semantic version number and version constraints (like those seen in Cargo and NPM), and returns true if the version is compatible based on the constraints
The following types of constraints are supported:
- `^1.2.3`: Version must be compatible with `1.2.3` (also implied if the version is passed as a constraint without a prefix)
- `=1.2.3`: Version must exactly match `1.2.3`
- `>=1.2.3`: Version must be `1.2.3` or any greater version
- `>1.2.3`: Version must be greater than `1.2.3`
- `<=1.2.3`: Version must be `1.2.3` or any lower version
- `<1.2.3`: Version must be less than `1.2.3`
This is mainly meant to be used with `std.BRIOCHE_VERSION` so new features can be added and feature-flagged in `std`. The existing …

[std] Implement semver comparisons

---

packages/std/core/global.bri
packages/std/core/recipes/download.bri

Companion PR: brioche-dev/brioche#102
Part of brioche-dev/brioche#70
This PR adds an implementation for `Brioche.download()` on the `Brioche` global. Just like with the other functions for statics, the implementation is pretty simple and just uses the `op_brioche_get_static` op to do the heavy lifting
Here's an example snippet that could be used in [the `jq` package](https://github.com/brioche-dev/brioche-packages/blob/f5578a79c7e2e22bfce77438bc2ba4571804a192/packages/jq/project.bri):
```typescript
const source = Brioche.download(
"https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-1.7.1.tar.gz",
)
.unarchive("tar", "gzip")
.peel();
```

Add implementation for `Brioche.download()` global function

---

packages/std/core/recipes/glob.bri
packages/std/core/recipes/index.bri
packages/std/core/recipes/recipe.bri
packages/std/core/runtime.bri

This PR adds the new `std.glob()` function. This uses the new `glob` recipe type introduced by brioche-dev/brioche#119. Here's a little example inspired by #62:
```typescript
// Get only the `go.mod` and `go.sum` files from a Go module
std.glob(goModule, ["**/go.mod", "**/go.sum"]);
```

[std] Implement `std.glob()` function

---

packages/git/project.bri
packages/std/core/global.bri
packages/std/core/recipes/download.bri

Companion PR: brioche-dev/brioche#126
This PR adds an implementation for `Brioche.gitRef()` on the `Brioche` global (basically following in the footsteps of #75).
Additionally, the `gitCheckout` function from the `git` package was updated slightly to compose better with the `Brioche.gitRef()` function: it can now take its options wrapped in a `Promise` (one very minor change is that the validation of the commit hash format doesn't run until the recipe returned by `gitCheckout` is baked or serialized).

Add implementation for `Brioche.gitRef()` global function

---

packages/gitui/brioche.lock
packages/gitui/project.bri

This PR updates the `gitui` package to use `Brioche.gitRef`, so that the package source uses the git tag instead of hard-coding a commit (the commit is then recorded in the `brioche.lock` lockfile)
(`gitui` is the only package that uses `gitCheckout`, so it was the only one that needed to be updated)

[gitui] Use `Brioche.gitRef` instead of hard-coding commit hash

---

packages/alsa_lib/project.bri
packages/ca_certificates/project.bri
packages/curl/project.bri
packages/git/project.bri
packages/go/project.bri
packages/jq/project.bri
packages/oniguruma/project.bri
packages/openssl/project.bri
packages/pcre2/project.bri
packages/rust/project.bri
packages/std/extra/autopack.bri
packages/std/extra/index.bri
packages/std/extra/set_env.bri
packages/std/runnable_tools.bri
packages/std/toolchain/index.bri
packages/std/toolchain/native/index.bri
packages/std/toolchain/utils.bri

This PR makes a few changes to `std`:
- Update `std.setEnv()` to support setting fallback env vars, instead of just appended paths
- Update `std.toolchain()` to set env vars for automake/autoconf, which cleans up downstream builds
- Re-wrap `std.toolchain()` and `std.tools()`. This ensures the final built version of each library gets used for all executables, and additionally shrinks the total size of both artifacts
The `std.setEnv()` in particular requires a code change. Here's an example:
```typescript
// Previously
/*
std.setEnv(recipe, {
FOO: { path: "foo" },
BAR: [{ path: "bar" }, { path: "baz" }],
});
*/
// Now
std.setEnv(recipe, {
FOO: { append: [{ path: "foo" }] },
BAR: { append: [{ path: "bar" }, { path: "baz" }] },
});
```
Additionally, there's now `fallback` values for env …

[Breaking][std] Improve toolchain and env var handling

---

packages/go/brioche.lock
packages/go/project.bri

This PR makes a few changes to the `go` package:
- Update Go to v1.23.1
- Improve handling of code bases with complex module structures (like Terraform) by using `std.glob()`. This should unblock #63
- Switch to using `Brioche.download()` instead of `std.download()` (this should've been covered by #104 but some packages were missed)

[go] Improve Go package and update to v1.23.1

---

packages/eza/project.bri
packages/ruff/project.bri

This PR is a followup to #112 to fix the failing builds for the `eza` and `ruff` packages. Both of them were just missing a `.peel()` after calling `.unarchive(...)`

Fix failing package builds

---

packages/terraform/brioche.lock
packages/terraform/project.bri

This package relies on updating the go package first to support globbing of `go.mod` files across directories. Once [Brioche Issue 79](https://github.com/brioche-dev/brioche/issues/79) is completed we can then update the go package for issue number #62

Add in terraform package

---

packages/oniguruma/project.bri
packages/pcre2/project.bri
packages/std/toolchain/native/index.bri

Closes #51
This PR tweaks `std.toolchain()` to set some more env vars for autotools. This makes it so the `pcre2` and `oniguruma` packages no longer need to manually set some env vars to get autotools builds working (which were the last two holdouts even after the changes from #110)

[std] Improve autotools to avoid needing to manually set env vars

---

packages/std/core/recipes/process.bri
packages/std/extra/bash_runnable.bri
packages/std/extra/index.bri
packages/std/extra/runnable.bri

This PR adds a few new functions to `std` used for creating [runnables](https://brioche.dev/docs/core-concepts/runnables/):
- `std.withRunnable(recipe, options)`: Add a new binary in the recipe at the path `brioche-run`. The options include the command, args, and envs to run.
- `std.addRunnable(recipe, path, options)`: Add a new binary in the recipe at the path specified by `path`. Same options as `std.withRunnable`, just with a custom path instead of always using `brioche-run`.
These new functions are meant to be a middle-ground between `std.withRunnableLink()` (where you can only directly run another executable) and `std.bashRunnable` (where you get a lot more flexibility, but need to include Bash as a dependency). By comparison, the new functions allows minimal templating for the …

[std] Add more functions for creating runnables

---

packages/std/toolchain/native/index.bri

Closes #79 
This PR updates `std.toolchain()` to set `$BISON_PKGDATADIR`, which fixes issues where Bison couldn't find some files (like `share/bison/m4sugar/m4sugar.m4`)

[std] Update `std.toolchain()` to set env var to fix Bison

---

packages/libpcap/brioche.lock
packages/libpcap/project.bri
packages/tcpdump/brioche.lock
packages/tcpdump/project.bri

This PR adds the new `tcpdump` package, as well as `libpcap` which is a dependency of `tcpdump`. The `libpcap` package is based on the snippet from #79

Add `tcpdump` and `libpcap` packages

---

packages/std/toolchain/native/index.bri

- Fix typo in `$PERL5LIB` in `std.toolchain()`
- Fix broken library symlinks in `std.toolchain()`
- Patch pkg-config files in `std.toolchain()` to use relative paths. This is kind of a hacky process for now (it just looks for the string `=/`, meant to find variables set with an absolute path). This will probably need to be refined in the future, and we'll probably want a utility function that can be applied to other packages too

[std] Fix some issues with libraries in `std.toolchain()`

---

packages/python/brioche.lock
packages/python/project.bri

This PR adds a new package for Python, which includes both CPython and the bundled version of pip.
Packaging Python definitely posed some unique challenges:
- Compiling Python compiles several native `.so` modules that link against other native libraries, like zlib for example. When this happens, the `.so` module references zlib during the build, but the Python interpreter itself doesn't, which means Python itself couldn't load zlib (which means Python wouldn't be able to load the module at all). So, we have a step in the build to rewrap the Python interpreter to make sure it references the native libraries used by all native modules (with a... kinda weird use of `std.autopack()`)
- We use `--without-ensurepip`, then manually run `ensurepip` at the end. This is because `ensurepip` during …

Add `python` pacakge

---

packages/python/brioche.lock
packages/python/project.bri

Also updated the existing python `project.bri` file to default the runnable link for `bin/python` to support the `brioche run` default

Update python to 3.13

---

packages/python/project.bri
packages/sqlite/brioche.lock
packages/sqlite/project.bri

This PR adds the new `sqlite` package, which includes the `sqlite3` CLI tool and `libsqlite3.so`
I also updated Python to include sqlite as a dependency, which made it so the configure script picked up sqlite and compiled the native `sqlite3` module.
I copied the function introduced in #118 that patches pkg-config files to use portable paths. This is probably a sign that we should add a general utility for this.

Add `sqlite` package

---

packages/std/core/recipes/index.bri
packages/std/core/recipes/process.bri

This PR tweaks the `unsafe` options in `std.process()`. Instead of `unsafe` taking a boolean then taking each unsafe option separately, the `unsafe` option itself is now an object containing each individual setting:
```typescript
// Before
std.process({
command: "/bin/sh",
args: ["-c", "echo 'Hello'"],
unsafe: true,
networking: true,
});
// After
std.process({
command: "/bin/sh",
args: ["-c", "echo 'Hello'"],
unsafe: {
networking: false,
},
});
```
This brings the `unsafe` option more in-line with the `.unsafe()` _method_ on the `std.Process` type. Also, since the underlying `unsafe` boolean is now only set if any unsafe options are enabled, it's now possible to make a process conditionally unsafe based on its inputs

[Breaking][std] Simplify unsafe settings for `std.process()`

---

packages/rust/project.bri

This PR updates the `rust.cargoBuild()` function to take a new `unsafe` option as input. This forwards the unsafe settings to the `std.process()` that does the actual build, which is useful for e.g. Rust projects that use `build.rs` for fetching remote dependencies (of course, we can't guarantee that builds are hermetic in those cases, so the burden is on the package author when enabling this setting).
This builds on the work from #122

[rust] Add `unsafe` option for `rust.cargoBuild()`

---

packages/libxml2/brioche.lock
packages/libxml2/project.bri

This PR adds a new package for `libxml2`, including both libraries and binaries. This was motivated by moretools, which uses `xmllint` provided by `libxml2` at build time

Add `libxml2` package

---

packages/unzip/brioche.lock
packages/unzip/patches/unzip-6.0-consolidated_fixes-1.patch
packages/unzip/patches/unzip-6.0-gcc14-1.patch
packages/unzip/project.bri

Pretty self explanatory. [UnZip](https://infozip.sourceforge.net/UnZip.html) is a nice utility to have, especially while brioche-dev/brioche#88 is still open.
This uses the latest stable release of UnZip, which is v6.0 from 2009. There are several known build-time issues and security issues outstanding with UnZip, so I followed the guidance from https://www.linuxfromscratch.org/blfs/view/12.2/general/unzip.html for extra patches to apply. I decided to duplicate these patches directly in the repo for simplicity

Add `unzip` package

---

packages/perl/brioche.lock
packages/perl/project.bri

This PR adds a new `perl` package. Unlike the version of Perl in `std.toolchain()`, this one is meant to follow the upstream version more directly. Also, having a standalone package means we can do tricks like create a "Perl virtual environment" and install packages into it in a composable way (similar to what we did with Python for `asciinema` in #127)
For some reason, the Perl build failed unless there was at least one additional locale available at build time, so I used `localegen` to create a locale that Perl can find during the build. I used `C.UTF-8` because that seemed like a pretty common one.

Add `perl` package

---

packages/libxslt/brioche.lock
packages/libxslt/project.bri

Like #128, this is part of the yak shave for moretools. `libxslt` includes `xsltproc`, which is used during the moreutils build

Add `libxslt` package

---

packages/pstack/brioche.lock
packages/pstack/project.bri

This PR adds a new `pstack` package.
`pstack` is a small utility that dumps a stack trace for a running process. As far as I can tell, there are two implementations that share a name: the [robotux](https://code.lm7.fr/robotux/pstack) version and the [peadar](https://github.com/peadar/pstack) version. The robotux version is the "original" as best as I can tell, but hasn't been updated in 8 years and has limited platform support; the peadar version is a new, actively maintained rewrite that supports more platforms.
Debian's `pstack` package still uses the robotux version, but I decided to use the peader version. Neither Nixpkgs nor Homebrew have a `pstack` package in their main repositories, although I did find one in Arch's AUR, which also uses the peader implementation.

Add `pstack` package

---

.github/workflows/ci.yml

This PR increases the timeout for the GitHub Actions workflow from the default value (6 hours) to a more generous value (12 hours). Recently, some builds-- namely, those that require rebuilding `std.toolchain()`-- have either gotten close to the threshold or have hit it and failed.

Increase timeout in GitHub Actions workflow

---

packages/jj/brioche.lock
packages/jj/project.bri

This PR adds a package for [Jujutsu](https://github.com/jj-vcs/jj), a git-compatible VCS (abbreviated `jj`)
I also used `jj` to make this PR 🙂

Add `jj` package

---

packages/python/project.bri
packages/talloc/brioche.lock
packages/talloc/project.bri

This PR adds a package for [talloc](https://talloc.samba.org/talloc/doc/html/index.html), a memory allocator from the Samba project. It's a C library, and it's a dependency of PRoot.
As part of this PR, I updated the Python package to build using a shared library. The talloc package also includes the Python library under `lib/python3.13/site-packages`, although it's not exposed via an env var at the moment. I wasn't sure the best way to handle Python packages like this, since the directory includes a specific (minor) Python version number, so I felt it was best to not try to expose it for now. In other words, the package isn't really meant to be used as a Python package at the moment.

Add `talloc` package

---

packages/libarchive/brioche.lock
packages/libarchive/project.bri

This PR adds a package for [libarchive](https://www.libarchive.org/), a C library that supports multiple archive and compression formats
As part of the implementation, I finally got bit by an absolute path in a libtool (`.la`) file. Basically, the file `lib/libacl.la` from `std.toolchain()` references `//lib/libattr.la` by absolute path, and the libarchive build eventually tries to read this absolute path, which won't exist in the sandbox. As a workaround, I manually patched the toolchain as part of this build to replace the absolute path with a normal `-l` flag (i.e. replacing `//lib/libattr.la` with `-lattr`). This patch is localized to the libarchive build (and also only touches `libacl.la`), so we'll likely want to generalize this and apply it to the entirety of `std.toolchain()`

Add `libarchive` package

---

packages/proot/brioche.lock
packages/proot/project.bri

This PR adds a package for [PRoot](https://github.com/proot-me/proot), a userland `chroot` implementation on Linux (which uses `ptrace` under the hood, so it should work even in contexts where user namespaces aren't allowed)

Add `proot` package

---

packages/rust/brioche.lock
packages/rust/project.bri

This PR updates the `rust` package to v1.83.0
Also, as part of this PR, I refactored the dependency vendoring code a bit in `cargoInstall()`, leading to the new public `rust.vendorCrate()` function. This makes it easier to run commands like `cargo check`, `cargo metadata`, etc. that depend on dependencies being available, without having to enable process networking and without needing custom code to handle vendoring (in my case, I was trying to write a project file for Brioche itself which uses the SQLx CLI command, which in turn requires Cargo dependencies to be available).

[rust] Update to Rust v1.83.0

---

packages/dasel/brioche.lock
packages/dasel/project.bri

This PR adds a new package for [Dasel](https://github.com/TomWright/dasel), a CLI tool for converting, querying, and editing JSON/YAML/TOML/XML/CSV documents

Add `dasel` package

---

packages/scdoc/brioche.lock
packages/scdoc/project.bri

This PR adds a new package for [`scdoc`](https://git.sr.ht/~sircmpwn/scdoc), a small C manpage generator

Add `scdoc` package

---

packages/s2argv_execs/brioche.lock
packages/s2argv_execs/project.bri

This PR adds a new package for the [`s2argv-execs`](https://github.com/virtualsquare/s2argv-execs) project, named as `s2argv_execs` (underscore instead of dash) for consistency with Brioche's package naming rules.
This project contains the `libexecs` C library, which at least is used by the [vdeplug4](https://github.com/rd235/vdeplug4) project.

Add `s2argv_execs` package

---

packages/vdeplug4/brioche.lock
packages/vdeplug4/project.bri

This PR adds a package for the [vdeplug4](https://github.com/rd235/vdeplug4) project. It offers a library and plugin system for networking with VMs, including when building [User-mode Linux](https://en.wikipedia.org/wiki/User-mode_Linux).
This is the same project backing the Debian package [`libvdeplug-dev`](https://packages.debian.org/sid/libvdeplug-dev). As best as I can tell, it's the latest of several projects providing the "libvde" library. I chose to name it `vdeplug4` because that's the name advertised in the upstream repo, and it appears to have an entirely separate codebase from prior versions.

Add `vdeplug4` package

---

packages/linux/brioche.lock
packages/linux/project.bri

This PR adds a new package for building [Linux](https://kernel.org/)-- as in, the kernel itself.
Structurally, the Linux kernel is pretty unique as a package. When built, it contains a `lib` directory containing all built kernel modules, and a `boot` directory containing the system map and the kernel itself. Also, the default name of the kernel itself varies by platform, so I decided to keep it consistent and add the symlink `boot/linux`, which points to the actual kernel image. For example, on x86-64 by default, the kernel is installed as `boot/bzImage` (since this is the default name as returned by `make image_name`), and so the symlink `boot/linux` will point to `bzImage`.
I also set up the package to offer a good deal of customization: by default, it uses the default config generated …

Add `linux` package

---

packages/linux/brioche.lock
packages/linux/project.bri

This PR updates the Linux kernel package (`packages/linux`) from v6.12.8 to v6.12.9, which is the current stable release. I also removed an unused env var from the build.

[linux] Update to v6.12.9

---

packages/rust/brioche.lock
packages/rust/project.bri

This PR updates Rust to the v1.84.0, which is the newest release. [Rust v1.84.0 release notes](https://blog.rust-lang.org/2025/01/09/Rust-1.84.0.html)

[rust] Update to v1.84.0

---

packages/go/brioche.lock
packages/go/project.bri

This PR updates Go to the latest version, which is v1.23.4. [Go v1.23.x release notes](https://go.dev/doc/devel/release#go1.23.minor)

[go] Update to v1.23.4

---

packages/rust/project.bri

This PR updates the options for the `rust.cargoBuild()` function with a new `buildParams.defaultFeatures` option. When set to `false`, it adds the `--no-default-features` flag when building the crate.
Also, I made two tiny cleanup changes:
- Validate the feature strings in `buildParams.features` with a regex (this should avoid shell quoting issues)
- Remove extra `.crates.toml` / `.crates2.json` files from build output (see ["Cargo Home"](https://doc.rust-lang.org/cargo/guide/cargo-home.html#files) in the Cargo docs for more context)

[rust] Add `buildParams.defaultFeatures` option to `rust.cargoBuild()`

---

packages/alsa_lib/brioche.lock
packages/alsa_lib/project.bri

Just updating the alsa-lib package. I'll go through all the packages, I think.

chore: update alsa_lib to version 1.2.13

---

packages/amber/brioche.lock
packages/amber/project.bri

Update amber to the latest release available.

chore: update amber to version 0.4.0-alpha

---

packages/asciinema/brioche.lock
packages/asciinema/project.bri

But maybe there was a reason to not having used the method `Brioche.download`.

refactor(asciinema): update source retrieval method to use tar.gz archive

---

packages/aws_cdk/project.bri

Just update aws-cdk package to the latest version available.

chore: update aws_cdk version to 2.176.0

---

packages/std/core/recipes/attach_resources.bri
packages/std/core/recipes/index.bri
packages/std/core/recipes/recipe.bri
packages/std/core/runtime.bri

Companion to brioche-dev/brioche#149
This PR adds a new `std.attachResources()` function. This returns a recipe corresponding to the new upstream `attach_resources` recipe type.

[std] Add `std.attachResources()` recipe

---

packages/std/toolchain/native/index.bri

Depends on #146 
Part of brioche-dev/brioche#147
This PR updates the `std.toolchain()` and `std.tools()` recipes by wrapping them with a new function called `syncTarball`. Internally, this function just tars then untars each recipe, which is effectively a no-op. But the _tarred_ version of the recipe is what would get synced from the registry, meaning this should ensure both `std.toolchain()` and `std.tools()` would get synced as a single tar download, rather than thousands of individual file downloads.

[std] Sync `toolchain()` and `tools()` as tarballs

---

packages/rust/brioche.lock
packages/rust/project.bri

Nothing else than updating the cargo-check package

feat: update cargo-chef to version 0.1.70 in dependencies

---

packages/curl/brioche.lock
packages/curl/project.bri

Update cURL package to the latest release. I had to add the following flag when building the package: `--without-libpsl`. Without it, I was getting this error:
```bash
ERROR build:bake:bake_inner:run_bake: brioche_core::bake: error=process failed, view full output by runing `brioche jobs logs /home/container/.local/share/brioche/process-temp/01JJ2D87R79C72ZPAXJZD26X5A/events.bin.zst`: process exited with status code exit status: 1
at file:///workspace/packages/std/core/recipes/process.bri:190:14
at file:///workspace/packages/curl/project.bri:27:6
at file:///workspace/packages/curl/project.bri:28:6
at file:///workspace/packages/std/extra/set_env.bri:50:25
at file:///workspace/packages/curl/project.bri:30:14
at file:///workspace/packages/std/extra/set_env.bri:61:23 scope=Project { …
```

feat: update curl to version 8.11.1

---

packages/gitui/brioche.lock
packages/gitui/project.bri

Update gitui to the latest release. I had to add the cmake dependency to make it build, otherwise this error was popping:
```bash
ERROR build:bake:bake_inner:run_bake: brioche_core::bake: error=process failed, view full output by runing `brioche jobs logs /home/container/.local/share/brioche/process-temp/01JJ2P8SDJ8RK4FZ183CKA1NK3/events.bin.zst`: process exited with status code exit status: 101
at file:///workspace/packages/std/core/recipes/process.bri:208:14
at file:///workspace/packages/rust/project.bri:196:6
at file:///workspace/packages/gitui/project.bri:18:10
at file:///workspace/packages/rust/project.bri:197:6
at file:///workspace/packages/rust/project.bri:200:29
at file:///workspace/packages/rust/project.bri:201:29 scope=Project { project_hash: …
```

feat: update gitui to version 0.27.0

---

packages/rust/brioche.lock
packages/rust/project.bri

Reverts brioche-dev/brioche-packages#177
There seems to be a regression in cargo-chef that affects the `xplr` package, which leads to an invalid `Cargo.toml` file. I opened an upstream issue here: https://github.com/LukeMathWalker/cargo-chef/issues/295
The regression appears to have started in cargo-chef 0.1.69, meaning the previous version of 0.1.68 seems to be the latest we can use for now. So, a revert seems like the simplest path forward.

Revert "feat: update cargo-chef to version 0.1.70 in dependencies"

---

packages/alsa_lib/project.bri

This is part of the POC for [testing](https://github.com/brioche-dev/brioche/issues/94) and [auto-update](https://github.com/brioche-dev/brioche/issues/165) functionalities.
```bash
> brioche build -p packages/alsa_lib/ -e test      
141    │ 1.2.13
0.87s ✓ Process 141
8.08s ✓ Registry  100% Fetch 136 blobs + 163 recipes from registry                                                                                                                                                                        
14.73s ✓ Registry  100% Fetch 1 blob + 1 recipe from registry                                                                                                                                                                              
2.02s ✓ Registry  100% Fetch 1 blob + 1 recipe from …
```

feat: enhance alsa_lib by adding testing and auto-update functionalities

---

packages/libffi/brioche.lock
packages/libffi/project.bri
packages/python/project.bri

This PR adds a new package for [libffi](https://github.com/libffi/libffi), a library for FFI (foreign function interface) calls.
The main motivation here was to include support for Python, so I went ahead and updated Python. This was as simple as adding libffi as a dependency during the Python build-- the `configure` script auto-detects it. I also updated the Python build to link in a few extra native libraries. I noticed these libraries were required while working on packaging AWS CLI (which uses libffi), and these all seemed like common, low-level libraries, so I thought it made sense to add them to Python by default.
Later, we should probably work backwards and figure out _where_ these libraries are being used, and figure out if we can auto-detect them too.

Add `libffi` package

---

packages/python/brioche.lock
packages/python/project.bri

This PR updates the `python` package to take an optional `version` option as an input. It can be set to either `3.12` or `3.13`, and will return a recipe for the corresponding Python version.
This is a temporary measure until https://github.com/brioche-dev/brioche/issues/97 is resolved. In the meantime, I found that the AWS CLI isn't compatible with Python 3.13, so it seemed worthwhile to manually add support for using a specific version for Python.

Update Python to support both v3.12 and v3.13 builds

---

packages/aws_cli/brioche.lock
packages/aws_cli/project.bri
packages/aws_cli/resolved-lockfiles.patch

This PR adds a new package for the [AWS CLI](https://github.com/aws/aws-cli): the Amazon Web Services Command Line Interface.
This one ended up being trickier than expected, for 3 reasons:
1. It (currently) requires Python 3.12. I updated `python` to support both v3.12 and v3.13 in #216 
2. It builds a native dependency, and requires libffi. I added a new `libffi` package and linked it to Python in #215
3. It has `requirements.txt` files that include hashes, but there are conflicting requirements around the `packaging` dependency (this only applies to the `requirements-*-lock.txt` files I believe, the standard `requirements.txt` file shouldn't have this problem but also doesn't have hashes). I solved this with a small patch file to resolve `packaging` to v24.2, which was the latest …

Add `aws_cli` package

---

packages/seaweedfs/brioche.lock
packages/seaweedfs/project.bri

[SeaweedFS](https://github.com/seaweedfs/seaweedfs) is a distributed object storage system written in Go, which offers an S3-compatible API along with lots of other protocols
cc @jaudiger I added new `test` and `autoUpdate` functions here based on the implementations from #212 (for brioche-dev/brioche#94 and brioche-dev/brioche#165)

Add `seaweedfs` package

---

packages/amber/project.bri
packages/bat/project.bri
packages/broot/project.bri
packages/github_cli/project.bri
packages/libpsl/project.bri
packages/seaweedfs/project.bri

Per discussion https://github.com/brioche-dev/brioche-packages/pull/225#discussion_r1936235366

Standardize version string handling by replacing 'v' prefix in auto update

---

packages/eza/brioche.lock
packages/eza/project.bri

This PR updates eza to the latest release of v0.20.0. I also added `test` and `autoUpdate` functions for https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165.

[eza] Update to v0.20.20

---

packages/ripgrep/project.bri

This PR adds `test` and `autoUpdate` functions for the `ripgrep` package, as part of https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165

[ripgrep] Add `test` and `autoUpdate` functions

---

packages/jq/project.bri

This PR adds test and autoUpdate functions for the jq package, as part of https://github.com/brioche-dev/brioche/issues/94 and https://github.com/brioche-dev/brioche/issues/165

feat(jq): add test and autoUpdate functions for version management

---

packages/github_cli/project.bri

Fix the following errors:
```bash
Error: nu::shell::type_mismatch
× Type mismatch.
╭─[/home/container/.local/share/brioche/locals/9d8325ca9f10271621f4751d9e527987e5995f518d792adff863613d93ea2209/brioche-run.d/recipe-0:1:29]
1 │ let releaseData = (http get https://api.github.com/repos/cli/cli/releases/latest | from json)
·                             ──────────────────────────┬─────────────────────────
·                                                       ╰── string
2 │
╰────
```
```bash
× Removed command: date format
╭─[/home/container/.local/share/brioche/locals/f8274885199553a1ee910c27d5e60468e5b72e73da706fba45803f69d55a9b0a/brioche-run.d/recipe-0:10:5]
9 │   | into datetime
10 │   | date format "%Y-%m-%d"
·     ─────┬─────
·          ╰── 'date format' has been removed from Nushell. …
```

fix(autoUpdate): correct JSON parsing and date formatting in release data retrieval

---

packages/rust/brioche.lock
packages/rust/project.bri

This PR upgrades the `rust` package to v1.85.0. I also cleaned up the test script a bit-- it now validates the version number when running `rustc --version`

[Rust] Update to v1.85.0

---

packages/jujutsu/brioche.lock
packages/jujutsu/project.bri

This PR updates the `jujutsu` (jj) package to v0.26.0. I also added `test` and `autoUpdate` functions for https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165

[jujutsu] Update to v0.26.0

---

packages/rust/brioche.lock
packages/rust/project.bri
packages/xplr/project.bri

This PR updates the version of `cargo-chef` (used for vendoring Cargo dependencies) used in the `rust` package from v0.1.67 to v0.1.71.
From my testing it seems like v0.1.67 doesn't support Rust 2024 edition, which we need to update Brioche itself to Rust 2024 (https://github.com/brioche-dev/brioche/pull/197). I also verified that v0.1.71 works.
We rolled back the last upgrade of `cargo-chef` (#177, rolled back in #189) due to an upstream issue that caused the build of the `xplr` package to fail. It seems like that issue is still open, so I decided to work around it for now by patching the `Cargo.toml` file in `xplr`.

[rust] Update `cargo-chef`

---

packages/restic/project.bri

This PR includes a small but important change to the `autoUpdate` function in the `packages/restic/project.bri` file. The change updates the URL used to fetch the latest release version

fix: update autoUpdate function to fetch latest version from restic repository instead of ripgrep

---

packages/aws_cli/brioche.lock
packages/aws_cli/project.bri

This PR fixes the build failure seen in [CI#611](https://github.com/brioche-dev/brioche-packages/actions/runs/13648116439), which manifested with this error:
```sh-session
$ brioche jobs logs ./01JNG382C31M5ZXEG4TH95YJ2K/events.bin.zst
process stack trace:
- file:///home/runner/_work/brioche-packages/brioche-packages/packages/std/core/recipes/process.bri:202:14
- file:///home/runner/_work/brioche-packages/brioche-packages/packages/aws_cli/project.bri:89:6
[0.00s] [spawned process with pid 30785, preparation took 0.01s]
[0.01s] /home/brioche-runner-82a412d8707a3bbc5ee98bb1058e1915e1df3b505bf079b9d3e908579015a223/.local/share/brioche/outputs/output-82a412d8707a3bbc5ee98bb1058e1915e1df3b505bf079b9d3e908579015a223/bin/pip: 2: exec: /home/brioche-runner-1abf9068b6b9fde6e4df870738b786b31a7ea3bbf …
```

[aws_cli] Fix build error and update to v2.24.17

---

packages/git/project.bri
packages/pcre2/project.bri

This PR fixes the build failure seen in [CI#613](https://github.com/brioche-dev/brioche-packages/actions/runs/13671340922), which manifested with the following error:
```
[22.66s]   CC       src/libpcre2_8_la-pcre2_compile_class.lo
[25.52s]   CC       src/libpcre2_8_la-pcre2_config.lo
[25.72s]   CC       src/libpcre2_8_la-pcre2_context.lo
[26.16s]   CC       src/libpcre2_8_la-pcre2_convert.lo
[28.93s]   CC       src/libpcre2_8_la-pcre2_dfa_match.lo
[37.47s]   CC       src/libpcre2_8_la-pcre2_error.lo
[37.66s]   CC       src/libpcre2_8_la-pcre2_extuni.lo
[38.13s]   CC       src/libpcre2_8_la-pcre2_find_bracket.lo
[38.37s]   CC       src/libpcre2_8_la-pcre2_jit_compile.lo
[38.43s] src/pcre2_jit_compile.c:85:10: fatal error: ../deps/sljit/sljit_src/sljitLir.c: No such file or directory …
```

[pcre2] Fix build failure

---

packages/process_compose/brioche.lock
packages/process_compose/project.bri

This PR adds a new package for [Process Compose](https://github.com/F1bonacc1/process-compose), a tool for scheduling and orchestrating processes (similar to Docker Compose, but without using containers).
This PR includes adds the `process_compose` package at v1.46.0 (the latest version), plus `test` and `autoUpdate` functions for https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165

Add `process_compose` package

---

packages/icu/brioche.lock
packages/icu/project.bri

This PR adds a package for the [ICU4C](https://unicode-org.github.io/icu/userguide/icu4c/) library from the [Unicode ICU](https://icu.unicode.org/) project, including `test` and `autoUpdate` functions for https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165.
I went with the package name `icu`, even though the `default` export builds the "ICU4C" library from the greater ICU project (but also note: ICU4C is part of a larger monorepo that also includes ICU4J and some other files). This matches the naming convention [from Repology](https://repology.org/project/icu/versions), and additionally matches what most other package managers do. The biggest exceptions are Nix and Homebrew, both of which use the package name `icu4c`

Add `icu` package

---

packages/postgresql/brioche.lock
packages/postgresql/project.bri

This PR adds a package for [PostgreSQL](https://postgresql.org/), an open source relational database. I also added `test` and `autoUpdate` functions for https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165.
I enabled several of the optional features in the build with various flags when calling `./configure`-- mainly the ones that used dependencies we already have packaged. I think it'd be worthwhile to go through and enable more of these options over time.

Add `postgresql` package

---

.github/workflows/ci.yml

This PR updates the runner label used for the "Build packages" job in CI GitHub Actions workflow. This is backed by new hardware that should be faster!

Switch to new self-hosted GH Actions runner

---

packages/cmake/project.bri
packages/pstack/project.bri

Closes #242
This PR makes a few minor improvements to the `cmakeBuild()` function from the `cmake` package:
- Improve variable handling to allow passing more values to `set` (e.g. any value compatible with `std.ProcessTemplateLike`)
- Handle arbitrary keys in `set` (instead of being restricted to valid env vars), which addresses #242
- Add new `path` option, which is useful for monorepos. I encountered this when I started looking into packaging LLVM / Clang
I also decided to set `CMAKE_BUILD_PARALLEL_LEVEL` to 16 in the `pstack` build to help speed up build times. This is somewhat related to #230, but for now I just stuck with a fixed value for parallelism, which we already do in a few other places.

CMake improvements

---

packages/postgresql/project.bri

This PR makes a few minor tweaks to the `postgresql` package:
- Use `std.setEnv` to set the `LIBRARY_PATH`, `CPATH`, and `PKG_CONFIG_PATH` env vars when used as a dependency (relates to #136)
- Patch pkg-config files (relates to #135)

PostgreSQL improvements

---

packages/libtirpc/brioche.lock
packages/libtirpc/project.bri

This PR adds a new `libtirpc` package. I ran into this as a dependency while working on a package for MySQL.
This is a very minimal initial implementation to unblock MySQL work, so it'd be worth revisiting to handle auto-updates and tests. I also included the function used for patching pkg-config files seen elsewhere (see #135)

Add `libtirpc` package

---

packages/rpcsvc_proto/brioche.lock
packages/rpcsvc_proto/project.bri

This PR adds an initial basic package for `rpcsvc-proto`, which I found as a dependency for MySQL. I kept the implementation very minimal for now, so it'd be worth revisiting to add tests and an auto-update script in the future.

Add `rpcsvc_proto` package

---

packages/std/brioche.lock
packages/std/runtime_utils.bri
packages/std/toolchain/utils.bri

This PR updates the versions of [`brioche-runtime-utils`](https://github.com/brioche-dev/brioche-runtime-utils) in `std`. This new version updates `brioche-ld` with support for parsing `@file` command line flags (see https://github.com/brioche-dev/brioche-runtime-utils/pull/21)

[std] Upgrade runtime utils

---

packages/rust/brioche.lock
packages/rust/project.bri

This PR updates Rust to v1.85.1. I also spent some time reworking the `rust.cargoBuild()` function to support some extra options under `buildParams`: `allFeatures`, `bins`, and `examples` (to mirror the `cargo install` options `--all-features`, `--bin` / `--bins`, and `--example` / `--examples` respectively).
To account for the new options, I also tweaked `cargoBuild()` to use `std.process()` directly instead of `std.runBash()`. I felt like this simplified things since this avoids concerns with escaping values properly

[rust] Update to v1.85.1, and add more options to `cargoBuild()`

---

packages/caddy/brioche.lock
packages/caddy/project.bri

This PR adds a package for [Caddy](https://caddyserver.com/), an HTTP server. It also includes test and auto-update functions (https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165)

Add `caddy` package

---

packages/nginx/brioche.lock
packages/nginx/project.bri

This PR adds a package for [nginx](https://nginx.org/), an HTTP server. It also includes test and auto-update functions (https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165)

Add `nginx` package

---

packages/llvm/brioche.lock
packages/llvm/project.bri

> Small note about this PR: I tested this build against LLVM v20.1.0, but a new version had released since I started work on this package. I updated the package definition, but due to the very slow build times, I'm going to merge it as-is and let the CI pipeline take care of the build.
This PR adds a new package for [LLVM](https://llvm.org/), a compiler/toolchain project that includes multiple sub-projects including Clang (a C/C++ compiler), LLDB (a debugger), and LLD (a linker).
This PR adds initial support for LLVM, and the default build includes some, but not all, of LLVMs projects: currently, it includes `clang`, `clang-tools-extra`, `lld`, and `lldb`.
I also added an initial iteration of a toolchain function, called `llvm.llvmToolchain()`. It's meant to be similar-ish to …

Add `llvm` package

---

packages/strace/brioche.lock
packages/strace/project.bri

This PR adds a package for [strace](https://strace.io), a debugging tool for tracing Linux syscalls. I also added test and auto-update functions (https://github.com/brioche-dev/brioche/issues/94 / https://github.com/brioche-dev/brioche/issues/165)

Add `strace` package

---

packages/ca_certificates/brioche.lock
packages/ca_certificates/project.bri

This PR updates the `ca_certificates` package to the latest bundle version from https://curl.se/docs/caextract.html

[ca_certificates] Update to 2025-02-25 bundle

---

packages/broot/brioche.lock
packages/broot/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/broot
0.06s ✓ Process 49873
Build finished, completed 1 job in 5.16s
{
"name": "broot",
"version": "1.45.1"
}
bash-5.2$ brioche build -e test -p packages/broot
54928  │    Compiling lru v0.12.5
│    Compiling deser-hjson v2.2.4
│    Compiling umask v2.1.0
│    Compiling uzers v0.12.1
│    Compiling custom_error v1.9.2
│    Compiling strict v0.1.4
│    Compiling pathdiff v0.2.3
│    Compiling flex-grow v0.1.0
│    Compiling bet v1.0.4
│    Compiling id-arena v2.2.1
│    Compiling splitty v1.0.2
│    Compiling glob v0.3.2
│    Compiling base64 v0.21.7
│    Compiling char_reader v0.1.1
│    Compiling rustc-hash v2.1.1
│    Compiling git2 v0.20.1
│ …
```

chore(broot): update version to 1.45.1

---

packages/carapace/brioche.lock
packages/carapace/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/carapace/
0.06s ✓ Process 65282
Build finished, completed 1 job in 4.77s
{
"name": "carapace",
"version": "1.3.0"
}
bash-5.2$ brioche build -e test -p packages/carapace/
65567  │ Initialized empty Git repository in /home/brioche-runner-079ba9e6aa5b4461225b7d12feb5ce5ee9aaf8c7f51ee82f4c1014c51992ae56/.local/share/brioche/outputs/output-079ba9e6aa5b4461225b7d12feb5ce5ee9aaf8c7f51ee82f4c1014c51992ae56/.gi
│ t/
│ From https://github.com/carapace-sh/carapace-bin
│  * branch            2790a2b7a1055d3c03b3e913c0ea0b0ca0a81d96 -> FETCH_HEAD
│ HEAD is now at 2790a2b Merge pull request #2741 from carapace-sh/update-bridge
65758  │ go: downloading …
```

chore(carapace): update version to 1.3.0

---

packages/claude_code/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/claude_code/
0.06s ✓ Process 79095
Build finished, completed 1 job in 5.25s
{
"name": "claude_code",
"version": "0.2.69",
"packageName": "@anthropic-ai/claude-code"
}
bash-5.2$ brioche build -e test -p packages/claude_code/
ERROR build:evaluate: brioche_core::script::evaluate: error=Error: expected 0.2.69, got 0.2.69 (Claude Code)
at Module.assert (file:///workspace/packages/std/core/utils.bri:9:11)
at Module.test (file:///workspace/packages/claude_code/project.bri:29:7)
at eventLoopTick (ext:core/01_core.js:175:7) export="test" project_hash=99e989942061dca41c81570a6ebf7df6215402c5e3f12dd40acd72799dc22e5d
79999  │ npm notice
│ npm notice New major version of npm available! 10.9.2 -> 11.3.0
│ npm notice Changelog: …
```

chore(claudecode): update version to 0.2.69 and adjust expected output format in tests

---

packages/eza/brioche.lock
packages/eza/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/eza   
0.06s ✓ Process 85251
Build finished, completed 1 job in 5.22s
{
"name": "eza",
"version": "0.21.0"
}
bash-5.2$ brioche build -e test -p packages/eza 
85393  │    Compiling uutils_term_grid v0.6.0
│    Compiling nu-ansi-term v0.50.1
│    Compiling url v2.5.4
│    Compiling proc-mounts v0.3.0
│    Compiling uzers v0.12.1
│    Compiling locale v0.2.2
│    Compiling number_prefix v0.4.0
│    Compiling once_cell v1.21.3
│    Compiling timeago v0.4.2
│    Compiling unicode-width v0.2.0
│    Compiling path-clean v1.0.1
│    Compiling glob v0.3.2
│    Compiling natord-plus-plus v2.0.0
│    Compiling git2 v0.20.1
│     Finished `release` profile …
```

chore(eza): update version to 0.21.0

---

packages/dust/brioche.lock
packages/dust/project.bri

```bash
bash-5.2$ brioche build -e test -p packages/dust  
ERROR build:evaluate: brioche_core::script::evaluate: error=Error: expected 'dust 1.2.0', got 'Dust 1.2.0'
at Module.assert (file:///workspace/packages/std/core/utils.bri:9:11)
at Module.test (file:///workspace/packages/dust/project.bri:34:7)
at eventLoopTick (ext:core/01_core.js:175:7) export="test" project_hash=72861b665f17eae23d143337140084f589fbcae67a7438d14512c8faf61b2193
84284  │    Compiling ansi_term v0.12.1
│    Compiling itoa v1.0.15
│    Compiling ryu v1.0.20
│    Compiling iana-time-zone v0.1.61
│    Compiling sysinfo v0.27.8
│    Compiling lscolors v0.13.0
│    Compiling toml v0.5.11
│    Compiling chrono v0.4.40
│    Compiling regex v1.11.1
│ …
```

chore(dust): update version to 1.2.0 and add testing support

---

packages/dasel/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/dasel/
Build finished, completed (no new jobs) in 2.85s
{
"name": "dasel",
"version": "2.8.1"
}
bash-5.2$ brioche build -e test -p packages/dasel/  
84138  │ dasel version 2.8.1
0.17s ✓ Process 84138
2.14s ✓ Registry  100% Fetch 1 blob + 3 recipes from registry                                                                                                                                                                              
Build finished, completed 2 jobs in 8.01s
Result: 1cf736f0c39c1490cfb9c2bb904ddd676bbcef9960ec18a5499d9c57365079f5
```

refactor: uniformize the way we retrieve dasel codebase

---

packages/aws_cli/brioche.lock
packages/aws_cli/project.bri
packages/aws_cli/resolved-lockfiles.patch

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/aws_cli/    
Build finished, completed (no new jobs) in 3.51s
{
"name": "aws_cli",
"version": "2.26.1"
}
bash-5.2$ brioche build -e test -p packages/aws_cli/    
83519  │ d4a0eefef665a59a8/lib/python3.12/site-packages (from awscli==2.26.1) (1.0.1)
│ Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/brioche-runner-bb4f040f10078b094fd494b56c6ac92ac75dbc9057ec1f8d4a0eefef665a59a8/.local/share/brioche/outputs/output-bb4f040f10078b094fd494b56c6ac92ac75dbc9057ec1f8d
│ 4a0eefef665a59a8/lib/python3.12/site-packages (from awscli==2.26.1) (1.26.20)
│ Requirement already satisfied: cffi>=1.12 in /home/brioche-runner-bb4f040f10078b094fd494b56c6ac92ac75dbc9057ec1f8d4a0eefef665a59a8/.local/share/brioche/outputs/outpu …
```

chore(aws_cli): update version to 2.26.1 and adjust packaging dependency to 24.2

---

packages/cmake/project.bri

```bash
bash-5.2$ brioche build -e test -p packages/cmake
19142  │ cmake version 3.31.1
0.16s ✓ Process 19142
Build finished, completed 1 job in 5.08s
Result: 19eeda682ce5ddc8a4e2119325e9561483cfc9f198dad755a3bc296430ed6b3a
```

refactor(cmake): enhance version check to retrieve only relevant output

---

packages/github_cli/brioche.lock
packages/github_cli/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/github_cli/
0.06s ✓ Process 19180
Build finished, completed 1 job in 5.28s
{
"name": "github_cli",
"version": "2.69.0",
"latestBuildDate": "2025-03-19"
}
bash-5.2$ brioche build -e test -p packages/github_cli/
19259  │ Initialized empty Git repository in /home/brioche-runner-98fb5519a8748b5726cbf9bf25afa82ef14b946e6bd24606647355dcac68b566/.local/share/brioche/outputs/output-98fb5519a8748b5726cbf9bf25afa82ef14b946e6bd24606647355dcac68b566/.git/
│ From https://github.com/cli/cli
│  * branch            45ffa3c668f7105e92089220d42aa64c9acbd11c -> FETCH_HEAD
│ HEAD is now at 45ffa3c Merge pull request #10625 from …
```

chore(github_cli): update version to 2.69.0

---

packages/just/brioche.lock
packages/just/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/just
0.09s ✓ Process 33594
Build finished, completed 1 job in 12.70s
{
"name": "just",
"version": "1.40.0"
}
bash-5.2$ brioche build -e test -p packages/just/
33777  │    Compiling shellexpand v3.1.0
│    Compiling clap_complete v4.5.46
│    Compiling rand v0.9.0
│    Compiling derive-where v1.2.7
│    Compiling uuid v1.15.1
│    Compiling num_cpus v1.16.0
│    Compiling ansi_term v0.12.1
│    Compiling lexiclean v0.0.1
│    Compiling percent-encoding v2.3.1
│    Compiling target v2.1.0
│    Compiling typed-arena v2.0.2
│    Compiling is_executable v1.0.4
│    Compiling edit-distance v2.1.3
│    Compiling unicode-width v0.2.0
│    Compiling …
```

chore(just): update version to 1.40.0

---

packages/nushell/brioche.lock
packages/nushell/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/nushell
0.10s ✓ Process 62062
Build finished, completed 1 job in 14.06s
{
"name": "nushell",
"version": "0.103.0"
}
bash-5.2$ brioche build -e test -p packages/nushell
62278  │    Compiling alphanumeric-sort v1.5.3
│    Compiling termcolor v1.4.1
│    Compiling roxmltree v0.20.0
│    Compiling filesize v0.2.0
│    Compiling data-encoding v2.8.0
│    Compiling nu-explore v0.103.0 (/home/brioche-runner-1051ac7841f9dd49732220ebf5021d3d8f155ce5bce43d8db3636f6e6df110f0/work/crates/nu-explore)
│    Compiling nu-cmd-extra v0.103.0 (/home/brioche-runner-1051ac7841f9dd49732220ebf5021d3d8f155ce5bce43d8db3636f6e6df110f0/work/crates/nu-cmd-extra)
│ …
```

chore(nushell): update version to 0.103.0

---

packages/php/brioche.lock
packages/php/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/php  
0.09s ✓ Process 69687
Build finished, completed 1 job in 5.20s
{
"name": "php",
"version": "8.4.6"
}
bash-5.2$ brioche build -e test -p packages/php
75066  │ directorytreeiterator.inc
│ invertedregexiterator.inc
│ Build complete.
│ Don't forget to run 'make test'.
│ Installing shared extensions:     /home/brioche-runner-8fa05f607192ab33bb89b60e2c50c951d9bc10b551a011b8efed9ae939d50c25/.local/share/brioche/outputs/output-8fa05f607192ab33bb89b60e2c50c951d9bc10b551a011b8efed9ae939d50c25/lib/php/extensions/no-debug-non-zts-20240924/
│ Installing PHP CLI binary:        /home/brioche-runner-8fa05f607192ab33bb89b60e2c50c951d9bc10b551a011b8efed9ae939d50c25/.local/share/brioche/outputs/output-8fa05f607192ab33bb89b60e2c …
```

chore(php): update version to 8.4.6

---

packages/libffi/brioche.lock
packages/libffi/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/libffi/
0.06s ✓ Process 39608
Build finished, completed 1 job in 4.51s
{
"name": "libffi",
"version": "3.4.8"
}
bash-5.2$ brioche build -e test -p packages/libffi
Build finished, completed (no new jobs) in 1.89s
Result: 8e41eaf699967fcb84f81e22254417c0776b019ba274b0272baab0001fa818c9
```

chore(libffi): update version to 3.4.8 and add testing capability

---

packages/restic/brioche.lock
packages/restic/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/restic/
0.07s ✓ Process 90112
Build finished, completed 1 job in 5.48s
{
"name": "restic",
"version": "0.18.0"
}
bash-5.2$ brioche build -e test -p packages/restic/
90175  │ Initialized empty Git repository in /home/brioche-runner-af38bb13d6c3b9a638ba3ca3a6f53f53c4c0e29a559aadf8457b54876e8d1b45/.local/share/brioche/outputs/output-af38bb13d6c3b9a638ba3ca3a6f53f53c4c0e29a559aadf8457b54876e8d1b45/.gi
│ t/
│ From https://github.com/restic/restic
│  * branch            d401ad6c1ec93a8fbcfcd9f6855a7a4468878ec2 -> FETCH_HEAD
│ HEAD is now at d401ad6 Add version for 0.18.0
97503  │ restic 0.18.0 compiled with go1.24.0 on linux/amd64
0.24s ✓ Process …
```

chore(restic): update version to 0.18.0

---

packages/steampipe/brioche.lock
packages/steampipe/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/steampipe/
0.06s ✓ Process 10583
Build finished, completed 1 job in 5.01s
{
"name": "steampipe",
"version": "1.1.0"
}
bash-5.2$ brioche build -e test -p packages/steampipe/  
10644  │ Initialized empty Git repository in /home/brioche-runner-5fb9010657f60023fbc91376f6e179f68293fee4c05269135aaaceb9fa7a8cf0/.local/share/brioche/outputs/output-5fb9010657f60023fbc91376f6e179f68293fee4c05269135aaaceb9fa7a8cf0/.gi
│ t/
│ From https://github.com/turbot/steampipe
│  * branch            a312d91d978c92d3bfb79cc02d1345a33cce3681 -> FETCH_HEAD
│ HEAD is now at a312d91 v1.1.0
21671  │ Steampipe v1.1.0
0.37s ✓ Process 21671
1m57s ✓ Process 10813
40.77s ✓ …
```

chore(steampipe): update version to 1.1.0

---

packages/llvm/brioche.lock
packages/llvm/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/llvm
0.07s ✓ Process 39709
Build finished, completed 1 job in 12.00s
{
"name": "llvm",
"version": "20.1.2"
}
```
Sorry I didn't test the full build of LLVM on my machine. It was too slow to compile it. After one hour, it was just at 18%. Even with a M1 Pro... I think the abstraction with virtualisation is too slow for these kinds of things. Hope we'll have soon the cross-building support 😁

chore(llvm): update version to 20.1.2

---

packages/k9s/brioche.lock
packages/k9s/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/k9s/
Build finished, completed (no new jobs) in 2.72s
{
"name": "k9s",
"version": "0.50.3"
}
bash-5.2$ brioche build -e test -p packages/k9s
Build finished, completed (no new jobs) in 2.18s
Result: f6b6691d43f49cdbe416eeb298142760b7a889b567a3ade5535c1660c52349bc
```

chore(k9s): update version to 0.50.3 and add testing capability

---

packages/wasmtime/brioche.lock
packages/wasmtime/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/wasmtime/
0.08s ✓ Process 67100
Build finished, completed 1 job in 6.28s
{
"name": "wasmtime",
"version": "31.0.0"
}
bash-5.2$ brioche build -e test -p packages/wasmtime/
Build finished, completed (no new jobs) in 3.13s
Result: 246240b7a7ec4858f285e935015eada6428db04aa4cf8beacad43448957c7bdd
```

chore(wasmtime): update version to 31.0.0 and add testing capability

---

packages/terraform/brioche.lock
packages/terraform/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/terraform/
Build finished, completed (no new jobs) in 3.69s
{
"name": "terraform",
"version": "1.11.4"
}
bash-5.2$ brioche build -e test -p packages/terraform/
Build finished, completed (no new jobs) in 2.27s
Result: 5c387b866c7df48b7f58c60fa0defd419241d278e2f4db0b7c60b610def78be7
```

chore(terraform): update version to 1.11.4 and update build process for Go 1.24 workaround

---

packages/xplr/brioche.lock
packages/xplr/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/xplr/
0.07s ✓ Process 69755
Build finished, completed 1 job in 6.53s
{
"name": "xplr",
"version": "1.0.0"
}
bash-5.2$ brioche build -e test -p packages/xplr/
67311  │    Compiling nu-ansi-term v0.50.1
│    Compiling ansi-to-tui v7.0.0
│    Compiling skim v0.16.1
│    Compiling textwrap v0.16.2
│    Compiling snailquote v0.3.1
│    Compiling jf v0.6.2
│    Compiling lscolors v0.20.0
│    Compiling path-absolutize v3.1.1
│    Compiling humansize v2.1.3
│    Compiling tui-input v0.11.1
│    Compiling gethostname v1.0.0
│    Compiling natord v1.0.9
│    Compiling xdg v2.5.2
│    Compiling home v0.5.11
│    Compiling mlua v0.10.3
│    Compiling xplr v1.0.0 (/home/brioche-runner-18ad0df949dcce7df5918c81989616db722c55877b …
```

chore(xplr): update version to 1.0.0 and add testing capability

---

packages/just/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/just    
0.07s ✓ Process 30785
Build finished, completed 1 job in 13.18s
{
"name": "just",
"version": "1.40.0"
}
bash-5.2$ brioche build -e test -p packages/just
Build finished, completed (no new jobs) in 2.78s
Result: ed728a7d6d3136f1d657295d9790e10d614088e5c1623be8f1f40047c6a6ca19
```

chore(just): update test function to validate version

---

packages/zx/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/zx
Build finished, completed (no new jobs) in 2.86s
{
"name": "zx",
"version": "8.5.2"
}
bash-5.2$ brioche build -e test -p packages/zx
30507  │ npm notice
│ npm notice New major version of npm available! 10.9.2 -> 11.3.0
│ npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
│ npm notice To update run: npm install -g npm@11.3.0
│ npm notice
│ added 1 package in 826ms
30539  │ 8.5.2
0.78s ✓ Process 30539
0.18s ✓ Process 30530
2.78s ✓ Process 30507
Build finished, completed 3 jobs in 21.99s
Result: 808db600fd3bd07d95d9bbb82627d0918f6b8cfe62e051e08f839d111559c29b
```

chore(zx): update version to 8.5.2 and add test and auto-update functions

---

packages/fd/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/fd  
Build finished, completed (no new jobs) in 2.81s
{
"name": "fd",
"version": "10.2.0"
}
bash-5.2$ brioche build -e test -p packages/fd
Build finished, completed (no new jobs) in 2.82s
Result: 277121fee20cb8ef80722339012ebe987e879f6c979a6fa47d2bf76b1f27bb48
```

chore(fd): update test capability to enforce version checking

---

packages/pstack/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/pstack
Build finished, completed (no new jobs) in 3.18s
{
"name": "pstack",
"version": "2.10"
}
bash-5.2$ brioche build -e test -p packages/pstack
Build finished, completed (no new jobs) in 2.60s
Result: 9c297556324597f0b8be4e849ec33348e4f297917817150d114cc6e2530aa414
```

chore(pstack): enhance test function to validate version

---

packages/fx/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/fx     
Build finished, completed (no new jobs) in 2.93s
{
"name": "fx",
"version": "35.0.0"
}
bash-5.2$ brioche build -e test -p packages/fx
Build finished, completed (no new jobs) in 2.20s
Result: f5d39d97c98d438dd23611d856fa866a7dd23f95336f11f689ca27244ddcc6ba
```

chore(fx): enhance test function to validate version

---

packages/lurk/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/lurk  
0.06s ✓ Process 1517
Build finished, completed 1 job in 4.76s
{
"name": "lurk",
"version": "0.3.9"
}
bash-5.2$ brioche build -e test -p packages/lurk
Build finished, completed (no new jobs) in 2.91s
Result: 7dd22a3d3aa18713fda32745bc2e0f8f77c40b5ab16f1cb300799c673c8ae845
```

feat(lurk): add test function to validate version output

---

packages/oha/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/oha      
Build finished, completed (no new jobs) in 3.08s
{
"name": "oha",
"version": "1.8.0"
}
bash-5.2$ brioche build -e test -p packages/oha      
Build finished, completed (no new jobs) in 2.88s
Result: 5d25d9cd197a6d83524f1d6e0223d98af2c777cb0776f51e92229e383863b343
```

feat(oha): add test function to validate version output

---

packages/miniserve/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/miniserve
0.06s ✓ Process 1755
Build finished, completed 1 job in 4.60s
{
"name": "miniserve",
"version": "0.29.0"
}
bash-5.2$ brioche build -e test -p packages/miniserve
Build finished, completed (no new jobs) in 2.95s
Result: 803012377a24b08195555aedddd27034dc05fde3dbfe16b331daaab10c24d322
```

feat(miniserve): add test function to validate version output

---

packages/zoxide/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/zoxide
Build finished, completed (no new jobs) in 2.79s
{
"name": "zoxide",
"version": "0.9.7"
}
bash-5.2$ brioche build -e test -p packages/zoxide
Build finished, completed (no new jobs) in 2.62s
Result: d15066350b02e7409c7c78cca36f1b724ea9c08a2c7006f879e885817379ad5b
```

chore(zoxide): add test function to validate version output

---

packages/aws_cdk/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/aws_cdk/
0.06s ✓ Process 906
Build finished, completed 1 job in 4.72s
{
"name": "aws_cdk",
"version": "2.1010.0",
"packageName": "aws-cdk"
}
bash-5.2$ brioche build -e test -p packages/aws_cdk/
Build finished, completed (no new jobs) in 3.06s
Result: 67bc66f7a4072ccc8f1d73c30de5d055096a5c3162b34db7c07395d080c8d7e8
```

chore(aws_cdk): update version to 2.1010.0; update test function; add autoUpdate capability

---

packages/kubent/brioche.lock
packages/kubent/project.bri

```bash
bash-5.2$ brioche run -e autoUpdate -p packages/kubent/
Build finished, completed (no new jobs) in 2.77s
{
"name": "kubent",
"version": "0.7.3"
}
bash-5.2$ brioche build -e test -p packages/kubent/
Build finished, completed (no new jobs) in 2.24s
Result: bbf9c4592da293e95fc3db4e42d696ccc1ae67d307322a35b56a3a58bfaa6401
```

feat(kubent): add package with test and autoUpdate capabilities

---

packages/gitui/project.bri

```bash
[container@f1fcb7d2edd4 workspace]$ brioche run -e autoUpdate -p packages/gitui
Build finished, completed (no new jobs) in 2.53s
{
"name": "gitui",
"version": "0.27.0"
}
[container@f1fcb7d2edd4 workspace]$ brioche build -e test -p packages/gitui
Build finished, completed (no new jobs) in 2.73s
Result: 92bff9e3ecb20e3b021d536e7875829d0af51e36ae72a22480c9b26e49bdbffd
```

feat(gitui): add test function to validate version output

---

packages/jwt_cli/project.bri

```bash
[container@f1fcb7d2edd4 workspace]$ brioche run -e autoUpdate -p packages/jwt_cli/
Build finished, completed (no new jobs) in 2.30s
{
"name": "jwt_cli",
"version": "6.2.0"
}
[container@f1fcb7d2edd4 workspace]$ brioche build -e test -p packages/jwt_cli/
Build finished, completed (no new jobs) in 2.85s
Result: 9c215bf76bb881663c7022642eee666ae7ff7a316af5696ab21c87bd01f536f2
```

feat(jwt_cli): add test function to validate version output

---

packages/tokei/project.bri

```bash
[container@f1fcb7d2edd4 workspace]$ brioche run -e autoUpdate -p packages/tokei/
Build finished, completed (no new jobs) in 2.40s
{
"name": "tokei",
"version": "12.1.2"
}
[container@f1fcb7d2edd4 workspace]$ brioche build -e test -p packages/tokei
Build finished, completed (no new jobs) in 2.27s
Result: 705bc7b35c164f287109ecd091c675540ff9138e1389391d300dada5c7c536a9
```

feat(tokei): add test and autoUpdate capabilities

---

packages/xsv/project.bri

```bash
[container@f1fcb7d2edd4 workspace]$ brioche run -e autoUpdate -p packages/xsv/
Build finished, completed (no new jobs) in 2.25s
{
"name": "xsv",
"version": "0.13.0"
}
[container@f1fcb7d2edd4 workspace]$ brioche build -e test -p packages/xsv/
Build finished, completed (no new jobs) in 2.25s
Result: 4b4f6561b950349651a7775654f1a697f3f3ccb2c51a66d5c97b0057ce97141f
```

feat(xsv): add test function to validate version output

---

packages/rclone/brioche.lock
packages/rclone/project.bri

This PR adds a package for [Rclone](https://rclone.org/), a CLI tool for syncing files with cloud storage providers and remote servers

Add `rclone` package

---

packages/libpcap/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/libpcap/
Build finished, completed (no new jobs) in 2.41s
{
"name": "libpcap",
"version": "1.10.5"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/libpcap/
431    │ 1.10.5
0.12s ✓ Process 431
3.51s ✓ Cache     100% Fetch artifact: 3.2 MiB                                                                                                           
Build finished, completed 2 jobs in 8.94s
Result: 0911b7f058be0ac2e35c140acfa8c5a057962c36fdc4b36be377af6cd92d639e
```

feat(libpcap): add test and autoUpdate capabilities

---

packages/eza/project.bri
packages/fd/project.bri
packages/fx/project.bri
packages/gitui/project.bri
packages/icu/project.bri
packages/joshuto/project.bri
packages/jujutsu/project.bri
packages/just/project.bri
packages/jwt_cli/project.bri
packages/llvm/project.bri
packages/nginx/project.bri
packages/oniguruma/project.bri
packages/process_compose/project.bri
packages/pstack/project.bri
packages/restic/project.bri
packages/ripgrep/project.bri
packages/rust/project.bri
packages/strace/project.bri
packages/tokei/project.bri

This PR tries to uniformize the testing of the version in order to later refactor this code and it inside an helper function without too much rework.

refactor(testing): uniformize version assertion in test functions

---

packages/libxml2/brioche.lock
packages/libxml2/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/libxml2/
{
"name": "libxml2",
"version": "2.14.2",
"extra": {
"majorVersion": "2",
"minorVersion": "14"
}
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/libxml2/
Build finished, completed (no new jobs) in 1.86s
Result: 400d35569b9e30aef86564b4f317bb57599955c977ef14c13a1a8eab0d414301
```

feat(libxml2): add test and autoUpdate capabilities

---

packages/ca_certificates/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/ca_certificates/
{
"name": "ca_certificates",
"version": "2025-02-25"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/ca_certificates/
Build finished, completed (no new jobs) in 1.62s
Result: 38c26ecd02963d2106b8c2df12707cef2f090789a49f744e7ee0cafd14892328
```

feat(caCertificates): add test and autoUpdate capabilities

---

packages/go/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/go
Build finished, completed (no new jobs) in 2.26s
{
"name": "go",
"version": "1.24.2"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/go
Result: 0f1e3cdc18ba75914506b0c5a21211e961e49de615527ce06a44df0341de2534
```

feat(go): add test and autoUpdate capabilities

---

packages/nasm/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/nasm
Build finished, completed (no new jobs) in 2.21s
{
"name": "nasm",
"version": "2.16.03"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/nasm
Build finished, completed (no new jobs) in 1.61s
Result: 9422ec73e0924baf043aa8f1d1db2d902e4c0be7d71c5b3068b15eb45b09b61d
```

feat(nasm): add test function to validate version output

---

packages/nodejs/project.bri

```bash
[container@ba5998f2ae1e workspace]$ brioche run -e autoUpdate -p packages/nodejs
Build finished, completed (no new jobs) in 2.53s
{
"name": "nodejs",
"version": "23.11.0"
}
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/nodejs
Result: 9e89d218601329b5aac2aa3dab82b9df143651b77642fd580b402f7b8b334b5a
```

feat(nodejs): add test and autoUpdate capabilities

---

packages/aws_cli/project.bri
packages/joshuto/project.bri
packages/nasm/project.bri
packages/s2argv_execs/project.bri
packages/tokei/project.bri
packages/vdeplug4/project.bri

While working on https://github.com/brioche-dev/brioche-packages/pull/333, I was first getting a 504 in the autoUpdate function. During the initial testing of the nodejs PR, doing a GET on `https://api.github.com/repos/nodejs/node/git/matching-refs/` was leading a 504 error code from the GitHub API. After having read the documentation of [this REST API](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#list-matching-references), I saw that it was returning all the heads, tags, remotes of the repositories. While we only want the tags here.
Here is a quick showcase test (using Nushell) to demonstrate the different capabilities of the API:
```nu
➜ http get https://api.github.com/repos/aws/aws-cli/git/matching-refs/tags | length 
2833
➜ http get …
```

chore(autoUpdate): update API endpoint to fetch tags for versioning

---

packages/unzip/project.bri

There is no dedicated `--version` flag for UnZip.
```bash
[container@ba5998f2ae1e workspace]$ brioche build -e test -p packages/unzip
14857  │   Default action is to extract files in list, except those in xlist, to exdir;
│   file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).
│   -p  extract files to pipe, no messages     -l  list files (short format)
│   -f  freshen existing files, create none    -t  test compressed archive data
│   -u  update files, create if necessary      -z  display archive comment only
│   -v  list verbosely/show version info       -T  timestamp archive to latest
│   -x  exclude files that follow (in xlist)   -d  extract files into exdir
│ modifiers:
│   -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
│   -o …
```

feat(unzip): add test capability

---

packages/std/core/runtime.bri

Allow Zip in Brioche typing for archive format 

---

packages/libxml2/project.bri
packages/moreutils/project.bri
packages/process_compose/project.bri
packages/proot/project.bri
packages/s2argv_execs/project.bri
packages/scdoc/project.bri
packages/vdeplug4/project.bri

This PR standardizes the declaration of `source` variables across projects by removing the `export` keyword. We don't need to export it normally.

chore: remove unecessary export modifier from source definitions

---

packages/xh/brioche.lock
packages/xh/project.bri

This PR adds a package for [xh](https://github.com/ducaale/xh), a CLI tool for making HTTP requests. It's similar to Curl, but with a slicker UX largely based on [HTTPie](https://httpie.io/)

Add `xh` package

---

packages/libcap/brioche.lock
packages/libcap/project.bri

This PR adds a package for [libcap](https://git.kernel.org/pub/scm/libs/libcap/libcap.git/about/), a library for managing Linux / POSIX capabilities.
Getting this working ended up involving a lot of hacks! I also couldn't figure out an easy way to get the version for live-update scripts, so I've omitted it for the time being. I think the right option will be to use git tags, but I don't think we have such a script yet (we do for GitHub, but I don't remember seeing one for generic git servers?)

Add `libcap` package

---

packages/meson/brioche.lock
packages/meson/project.bri

This PR adds a package for [Meson](https://mesonbuild.com/), a user-friendly build system. Meson builds often use Ninja (added as a separate package in #374).
Meson is written in Python, and I used the `asciinema` package as a base for the build. That also means that this package will need to be cleaned up like `asciinema` in #219

Add `meson` package

---

packages/bubblewrap/brioche.lock
packages/bubblewrap/project.bri

This PR adds a new package for [bubblewrap](https://github.com/containers/bubblewrap), a CLI tool for setting up sandboxed environments on Linux.
Bubblewrap has 3 dependencies that were added in the three most recent PRs: libcap (#373), Ninja (#374), and Meson (#375)

Add `bubblewrap` package

---

packages/kmod/project.bri

```bash
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/kmod
Result: 00eb145456427418ccc1d0bc8215d2236c90c00b06f0b593f30a0cfb4c3b440c
[container@f7b5cac5aa21 workspace]$ brioche run -e autoUpdate -p packages/kmod
20.54s ✓ Cache     100% Fetch artifact: 40.8 MiB
0.07s ✓ Process 142
Build finished, completed 2 jobs in 25.04s
{
"name": "kmod",
"version": "34.2"
}
```

feat(kmod): add test and autoUpdate capabilities

---

packages/moreutils/project.bri

```bash
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/moreutils/
Build finished, completed (no new jobs) in 2.18s
Result: 03e7ceb51178164ce1dc216a1b9216c6747d1213594335fae8affc3332b90ed2
[container@f7b5cac5aa21 workspace]$ brioche run -e autoUpdate -p packages/moreutils/
Build finished, completed (no new jobs) in 2.51s
{
"name": "moreutils",
"version": "0.70"
}
```

feat(moreutils): add test and autoUpdate capabilities

---

packages/tcsh/project.bri

```bash
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/tcsh
Build finished, completed (no new jobs) in 1.58s
Result: ceeb101248e019e9ea4e10cf7700ef4cb3c8a2c2f01f7123c5f7da7e8a1280ba
```

feat(tcsh): add test capability

---

packages/tcpdump/project.bri

```bash
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/tcpdump
Build finished, completed (no new jobs) in 1.61s
Result: 4faf59dea88eca43194521b7326af341bfd90751f880aa3fcce21ed6ec778ce2
```

feat(tcpdump): add test capability

---

packages/aws_cdk/project.bri
packages/claude_code/project.bri
packages/go/project.bri
packages/nasm/project.bri
packages/nodejs/project.bri
packages/rust/project.bri
packages/zx/project.bri

This PR standardizes the return type of default export functions across some project files by explicitly specifying the `std.Recipe<std.Directory>` type.

refactor: add missing return type to default functions

---

packages/libtirpc/brioche.lock
packages/libtirpc/project.bri
packages/libxml2/project.bri
packages/libxslt/project.bri
packages/pcre/project.bri

```bash
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/libtirpc/
6680   │ 1.3.6
0.11s ✓ Process 6680
Build finished, completed 1 job in 2.61s
Result: 649015f1207cbf63f38810b1dc94819132640440bae6911c6c698314b34770de
[container@f7b5cac5aa21 workspace]$ brioche run -e autoUpdate -p packages/libtirpc/
Build finished, completed (no new jobs) in 2.42s
{
"name": "libtirpc",
"version": "1.3.6"
}
```

feat(libtirpc): add test and autoUpdate capabilities

---

packages/pnpm/brioche.lock
packages/pnpm/project.bri

This PR introduces a new `pnpm` package, including its installation, testing, and auto-update functionality.
```bash
[container@f7b5cac5aa21 workspace]$ brioche run -e autoUpdate -p packages/pnpm
Build finished, completed (no new jobs) in 2.67s
{
"name": "pnpm",
"version": "10.10.0"
}
[container@f7b5cac5aa21 workspace]$ brioche build -e test -p packages/pnpm
22532  │ 10.10.0
1.15s ✓ Process 22532
Build finished, completed 1 job in 7.25s
Result: 04449cafde4d6b54782402ef21748e8e6a4b5d3d8fa2e407a124af03cb965e35
```

feat(pnpm): add package

---

packages/libcap/project.bri

```bash
[container@748549e7edf3 workspace]$ brioche run -e autoUpdate -p packages/libcap/
Build finished, completed (no new jobs) in 2.37s
{
"name": "libcap",
"version": "1.2.76"
}
```

feat(libcap): add liveUpdate capability

---

packages/sqlite/project.bri

```bash
[container@de5053fafebd workspace]$ brioche build -e test -p packages/sqlite/
Build finished, completed (no new jobs) in 1.61s
Result: 67c6a09e700ac82306add0f4397c45eb87c8dbd076feb3f72d7fbc544de329bc
```

feat(sqlite): add test capability

---

packages/kmod/brioche.lock
packages/kmod/project.bri

Supersedes https://github.com/brioche-dev/brioche-packages/pull/388
This pull request updates the `kmod` project to use the new modern build system (`meson` and `ninja`), simplifies the test logic, and updates the project version. The most important changes include replacing the old `make`-based build system, updating dependencies, and modifying the test logic to align with the new versioning.
* Replaced the `./configure` and `make`-based build system with `meson` and `ninja` for setting up, compiling, and installing the project. (`packages/kmod/project.bri`, [packages/kmod/project.briL19-R32](diffhunk://#diff-5cacea6636b972dc49565a015ff6b6d9cc1bd2dbba682e4f48222e3992a1bf21L19-R32))
* Updated dependencies to include `meson` and `ninja` while keeping existing dependencies like `scdoc` and …

chore(kmod): update package; switch to new build system

---

packages/codex/brioche.lock
packages/codex/project.bri

This PR adds a new package from OpenAI: [codex](https://github.com/openai/codex) which is  a lightweight coding agent that runs in the terminal.
```bash
[container@748549e7edf3 workspace]$ brioche build -e test -p packages/codex
Build finished, completed (no new jobs) in 2.35s
Result: bf2d48a2dbe7379cd4cb2cc8ece97d52bd4c9cdbea7900dee6bf0057cdadff57
[container@748549e7edf3 workspace]$ brioche run -e liveUpdate -p packages/codex
{
"name": "codex",
"version": "0.1.2504251709",
"packageName": "@openai/codex"
}
```

feat(codex): add package

---

.github/workflows/_build.yml

This PR updates the GitHub Actions workflows to disable the legacy registry sync.
[As noted in the Brioche v0.1.5 announcement](https://brioche.dev/blog/announcing-brioche-v0-1-5/#psa-sunsetting-support-for-older-versions-of-brioche), I'm removing support for Brioche v0.1.4 and earlier from the registry. The final step will be the removal of several registry API endpoints.
This PR covers the first step, which is to stop the workflows in this repo from syncing to the legacy endpoint. This is done by un-setting the env var `$BRIOCHE_LEGACY_REGISTRY_SYNC`.

Disable legacy registry sync

---

packages/perl/project.bri

```bash
[container@868094031ec6 workspace]$ brioche build -e test -p packages/perl
15068  │ This is perl 5, version 40, subversion 1 (v5.40.1) built for x86_64-linux-thread-multi
│ Copyright 1987-2025, Larry Wall
│ Perl may be copied only under the terms of either the Artistic License or the
│ GNU General Public License, which may be found in the Perl 5 source kit.
│ Complete documentation for Perl, including FAQ lists, should be found on
│ this system using "man perl" or "perldoc perl".  If you have access to the
│ Internet, point your browser at https://www.perl.org/, the Perl Home Page.
0.12s ✓ Process 15068
Build finished, completed 1 job in 2.68s
Result: 3fa24934d9551039cf824c023bbd49d6f24d30ed06d4d359d66e4248b0637412
```

feat(perl): add test capability

---

packages/tailspin/brioche.lock
packages/tailspin/project.bri

Add a new package [`tailspin`](https://github.com/bensadeh/tailspin): a log file highlighter
```bash
[container@868094031ec6 workspace]$ brioche build -e test -p packages/tailspin
Build finished, completed (no new jobs) in 2.55s
Result: 7b04939f2831fda628a40480bd11c06793240f39fa9690aacc8300eb8082aea9
[container@868094031ec6 workspace]$ brioche run -e liveUpdate -p packages/tailspin/
Build finished, completed (no new jobs) in 2.46s
{
"name": "tailspin",
"version": "5.4.2"
}
```

feat(tailspin): add package

---

packages/biome/brioche.lock
packages/biome/project.bri

Add a new package [`biome`](https://github.com/biomejs/biome): A toolchain for web projects, aimed to provide functionalities to maintain them. Biome offers formatter and linter, usable via CLI. 
```bash
[container@868094031ec6 workspace]$ brioche build -e test -p packages/biome
Build finished, completed (no new jobs) in 2.50s
Result: 7fe5f990398e9a187e82e609cf2350655ece966e9452341e8e20ce11001b013f
[container@868094031ec6 workspace]$ brioche run -e liveUpdate -p packages/biome/
Build finished, completed (no new jobs) in 2.55s
{
"name": "biome",
"version": "1.9.4"
}
```

feat(biome): add package

---

packages/yazi/brioche.lock
packages/yazi/project.bri

Add a new package [`yazi`](https://github.com/sxyazi/yazi): a blazing fast terminal file manager written in Rust, based on async I/O.
```bash
[container@05f6a78d0dc4 workspace]$ brioche run -e liveUpdate -p packages/yazi
{
"name": "yazi",
"version": "25.4.8"
}
[container@05f6a78d0dc4 workspace]$ brioche build -e test -p packages/yazi
Result: 25710b63dae75ac6a5c2e8bbf3a8cf27ae86810a8b6c6374859be719eee0c887
```

feat(yazi): add package

---

packages/eks_node_viewer/brioche.lock
packages/eks_node_viewer/project.bri

Add a new package [`eks_node_viewer`](https://github.com/awslabs/eks-node-viewer) to view EKS nodes
```bash
[container@132881fa67a6 workspace]$ brioche build -e test -p packages/eks_node_viewer/
8363   │ eks-node-viewer version 0.7.4
│ commit: 798f9ba5059be4fe1083d535817918b9cdc2eca2
│ built at:
│ built by:
0.29s ✓ Process 8363
Build finished, completed 1 job in 3.23s
Result: fc2f26afb4f297bb0ba51e6fdf836e4418ee6785d3b7c6a64bdaa194bae58dc7
[container@132881fa67a6 workspace]$ brioche run -e liveUpdate -p packages/eks_node_viewer/
Build finished, completed (no new jobs) in 2.57s
{
"name": "eks_node_viewer",
"version": "0.7.4"
}
```

feat(eks_node_viewer): add package

---

packages/tcpdump/project.bri

```bash
[container@07115ffb5a58 workspace]$ brioche run -e liveUpdate -p packages/tcpdump/
0.06s ✓ Process 86
Build finished, completed 1 job in 3.21s
{
"name": "tcpdump",
"version": "4.99.5"
}
```

feat(tcpdump): add liveUpdate capability

---

.github/workflows/live-updates.yml

This PR makes a few updates to the "Live Updates" workflow:
- Configure the workflow to run on a schedule: every Friday at 12:17pm UTC
- I picked a time that I'm usually asleep so builds can run overnight, and I picked an odd minute to [avoid stampeding](https://akhaerov.medium.com/why-you-should-never-schedule-cron-jobs-exactly-at-midnight-8f11650f79f8)
- Fix script not printing a message on failure
- Add error annotations for each failed package
- Update job to fail at the end if any package failed
- This should hopefully make failures more visible. Medium-term, we'll want live-update scripts to have some kind of retry logic, and longer-term we'll probably want to ignore failures again (the best case would be if we could return an error only if a package's live-update fails for multiple …

Update "Live Updates" GH Actions workflow

---

packages/std/toolchain/native/index.bri

Closes #245
This PR rolls back the change introduced in #147. We started wrapping the recipes `std.tools()` and `std.toolchain()` into `.tar.zst` archives, which helped speed up artifact fetches on versions of Brioche prior to v0.1.5.
Now that Brioche v0.1.5 is live with the new cache (https://github.com/brioche-dev/brioche/pull/179), this change no longer helps with sync times (and if anything, using a compressed archive likely leads to storing more data in the cache due to how chunking works). We've also [past the point where the registry was still supporting Brioche v0.1.4 and earlier](https://brioche.dev/blog/announcing-brioche-v0-1-5/#psa-sunsetting-support-for-older-versions-of-brioche), so syncing these recipes "normally" again is a net-win.

Don't sync `std.tools` / `std.toolchain` as tarballs anymore

---

packages/xz/brioche.lock
packages/xz/project.bri

Add a new package [`xz`](https://github.com/tukaani-project/xz): a general-purpose data-compression library
```bash
[container@29ec39c53957 workspace]$ brioche build -e test -p packages/xz
Build finished, completed (no new jobs) in 1.80s
Result: a2b7813531402240d36ca3e39978d5c0382e81d2c9fee74351a2c11ceeaa0903
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/xz
{
"name": "xz",
"version": "5.8.1"
}
```

feat(xz): add package

---

packages/expat/brioche.lock
packages/expat/project.bri
packages/icu/project.bri

Add a new package [`expat`](https://github.com/libexpat/libexpat): Fast streaming XML parser written in C99 with >90% test coverage
```bash
[container@29ec39c53957 workspace]$ brioche build -e test -p packages/expat/
Build finished, completed (no new jobs) in 1.82s
Result: 52749c83cf924961ed2fdd9f3f22bde15d4f725f80311b169a73de90eb9a82a7
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/expat
Build finished, completed (no new jobs) in 2.44s
{
"name": "expat",
"version": "2.7.1",
"extra": {
"versionUnderscore": "2_7_1"
}
}
```

feat(expat): add package 

---

packages/libtirpc/project.bri
packages/libxml2/project.bri
packages/libxslt/project.bri
packages/pcre/project.bri

This PR updates the `liveUpdate` functions in several project files to ensure proper parsing of HTML anchor tags. The changes standardize the use of `<a href="...` in string matching conditions to align with expected HTML formatting.
```bash
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/pcre
0.07s ✓ Process 23180
Build finished, completed 1 job in 3.60s
{
"name": "pcre",
"version": "8.45"
}
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/libxslt/
0.06s ✓ Process 23216
Build finished, completed 1 job in 3.24s
{
"name": "libxslt",
"version": "1.1.43",
"extra": {
"majorVersion": "1",
"minorVersion": "1"
}
}
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/libxml2/
0.06s ✓ …
```

refactor: update the retrieving of version in some packages to properly parse the HTML tag `a`

---

packages/libunwind/brioche.lock
packages/libunwind/project.bri

Add a new package [`libunwind`](https://github.com/libunwind/libunwind): a portable and efficient C API for determining the current call chain of ELF program threads of execution and for resuming execution at any point in that call chain
```bash
[container@29ec39c53957 workspace]$ brioche build -e test -p packages/libunwind/
Build finished, completed (no new jobs) in 1.68s
Result: 6d80b456f624f3d42bca1969400675270116c3ea8b6eb6a783f7dc1f25d95487
[container@29ec39c53957 workspace]$ brioche run -e liveUpdate -p packages/libunwind/
Build finished, completed (no new jobs) in 2.34s
{
"name": "libunwind",
"version": "1.8.1"
}
```

feat(libunwind): add package

---

packages/std/core/recipes/process.bri
packages/std/core/runtime.bri

This PR updates the `std.Process` type to allow setting the starting directory for a process recipe-- either using the `currentDir` method when calling `std.process`, or the `.currentDir()` method on an existing process.
This is the `std` side change for https://github.com/brioche-dev/brioche/pull/231, which was included in Brioche v0.1.5.

[std] Add `Process.currentDir` setting

---

packages/moreutils/project.bri

This PR cleans up the `moreutils` package to call `.unarchive("zip")` to unzip a zip file (added in #335) rather than using the `unzip` package

[moreutils] Refactor to use `.unarchive()` instead of using `unzip`

---

packages/caddy/project.bri
packages/git/project.bri
packages/go/project.bri
packages/rust/project.bri
packages/std/core/recipes/process.bri
packages/std/core/runtime.bri

This PR updates the `std` package to inherit the host's CA certificates when running a process recipe that has networking enabled (`.unsafe({ networking: true })`). This is the `std` change for https://github.com/brioche-dev/brioche/issues/156, which was released as part of Brioche v0.1.5.
This PR includes 3 core changes:
1. Add new `std.caCertificateBundlePath` value. When used in a process template, it resolves to a file path that contains all of the CA certificates trusted by the host. **Using the value in a process without networking will result in an error!**
2. Update `std.process()` to set `$SSL_CERT_FILE` when `unsafe.networking` is enabled
3. Refactor existing packages to avoid `ca_certificates` (since the host's CA certificates are used instead by default)

[std] Automatically inherit host certificates in process recipes with networking

---

packages/zlib_ng/brioche.lock
packages/zlib_ng/project.bri

Add a new package [`zlib-ng`](https://github.com/zlib-ng/zlib-ng): zlib replacement with optimizations for "next generation" systems.
```bash
[container@07115ffb5a58 workspace]$ brioche run -e liveUpdate -p packages/zlib-ng/
Build finished, completed (no new jobs) in 2.60s
{
"name": "zlib_ng",
"version": "2.2.4"
}
[container@07115ffb5a58 workspace]$ brioche build -e test -p packages/zlib-ng/
Build finished, completed (no new jobs) in 1.74s
Result: 8435a843d2c60418599afe16e2e2706aab19d570b6d6c58c10a15b106844a217
```

feat(zlib_ng): add package

---

packages/aws_cli/project.bri
packages/cmake/project.bri
packages/joshuto/project.bri
packages/std/extra/apply_patch.bri
packages/std/extra/index.bri

This PR adds a new `std.applyPatch` function. It's a simple wrapper around the `patch` CLI utility from `std.tools()`, which was added to clean up a few places in the code where we need to apply source patches.
I decided to make the `strip` option explicit to start with (the `-p` / `--strip` CLI option). I don't think I've ever needed to apply a patch without `-p1`, so it might be nice to at least set a default of 1 as a follow-up?

[std] Add `std.applyPatch` utility

---

packages/dasel/project.bri
packages/github_cli/project.bri
packages/process_compose/project.bri
packages/rclone/project.bri
packages/terraform/project.bri

Always set the `-s` and `-w` LD flags when building go binaries:
- `-s`: This flag omits the symbol table and debug information from the binary
- `-w`: This flag omits the DWARF debugging information
Example for `eks-node-viewer`:
```bash
[container@f8fe1cf467ff workspace]$ ls -al /tmp/eks_node_viewer_without_optimizations/bin/
total 99312
drwxr-xr-x 2 container container      4096 May  5 06:54 .
drwxr-xr-x 3 container container      4096 May  5 06:54 ..
-rwxr-xr-x 1 container container 101679712 May  5 06:54 eks-node-viewer
[container@f8fe1cf467ff workspace]$ ls -al /tmp/eks_node_viewer/bin/
total 71396
drwxr-xr-x 2 container container     4096 May  5 06:51 .
drwxr-xr-x 3 container container     4096 May  5 06:51 ..
-rwxr-xr-x 1 container container 73097400 May  5 06:51 eks-node-viewer …
```

chore: always build go binary with `-s` and `-w`

---

packages/hyperfine/brioche.lock
packages/hyperfine/project.bri

Add a new package [`hyperfine`](https://github.com/sharkdp/hyperfine): A command-line benchmarking tool
```bash
[container@ca91eae7e26c workspace]$ brioche run -e liveUpdate -p packages/hyperfine/
Build finished, completed (no new jobs) in 3.31s
{
"name": "hyperfine",
"version": "1.19.0",
"repository": "https://github.com/sharkdp/hyperfine.git"
}
[container@ca91eae7e26c workspace]$ brioche build -e test -p packages/hyperfine/
Build finished, completed (no new jobs) in 2.95s
Result: 088633444c420cf0f2bcb6e88a3873abe3b3514acb40e807ae50d8be91d8b42b
```

feat(hyperfine): add package

---

packages/bugstalker/brioche.lock
packages/bugstalker/project.bri

Add a new package [`bugstalker`](https://github.com/godzie44/bugstalker): a Rust debugger for Linux x86-64.
```bash
[container@ca91eae7e26c workspace]$ brioche build -e test -p packages/bugstalker/
Build finished, completed (no new jobs) in 3.16s
Result: 4f2cb316f01914c99e74b5741f76c466940d61772db4062b450315b50106f540
[container@ca91eae7e26c workspace]$ brioche run -e liveUpdate -p packages/bugstalker/
Build finished, completed (no new jobs) in 2.94s
{
"name": "bugstalker",
"version": "0.3.0",
"repository": "https://github.com/godzie44/BugStalker.git"
}
```

feat(bugstalker): add package

---

packages/snazy/brioche.lock
packages/snazy/project.bri

Add a new package [`snazy`](https://github.com/chmouel/snazy): a snazzy json log viewer (with one z)
Already packaged on [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/sn/snazy/package.nix#L41) too. 
```bash
[container@ca91eae7e26c workspace]$ brioche build -e test -p packages/snazy/
Build finished, completed (no new jobs) in 3.12s
Result: 3852f8a367c5bee2d00fe4ae615e36055770b9710b2e558d667e11a23c4e743f
[container@ca91eae7e26c workspace]$ brioche run -e liveUpdate -p packages/snazy/
Build finished, completed (no new jobs) in 3.26s
{
"name": "snazy",
"version": "0.56.0",
"repository": "https://github.com/chmouel/snazy.git"
}
```

feat(snazy): add package

---

packages/nushell/project.bri

Add all the [core Nushell plugins](https://www.nushell.sh/book/plugins.html#core-plugins). Contrary to the homebrew [Nushell formula](https://github.com/Homebrew/homebrew-core/blob/89bd44cf086208aeffde0bc094f1b4e81eb88d34/Formula/n/nushell.rb#L41), we only install the core plugins and not the example plugins (this is unnecessary, and doesn't add any value for most of the users).
> Nushell also ships with several plugins that serve as examples or tools for plugin developers. These include nu_plugin_example, nu_plugin_custom_values, and nu_plugin_stress_internals.
The following plugins are now installed by default (which tends to be the recommended approach per Nushell's maintainers):
- polars: Extremely fast columnar operations using DataFrames via the [Polars …

feat(nushell): add core plugins

---

packages/libssh2/brioche.lock
packages/libssh2/project.bri

Add a new package [`libssh2`](https://www.libssh2.org): a Client-side C library implementing the SSH2 protocol
```bash
[container@6818e76b941a workspace]$ brioche build -e test -p packages/libssh2/
Build finished, completed (no new jobs) in 1.59s
Result: aa1601a9ed9d8582108c10c68464d84106b7ae77f5abd92c30a855983b7ef570
[container@6818e76b941a workspace]$ brioche run -e liveUpdate -p packages/libssh2/
Build finished, completed (no new jobs) in 5.63s
{
"name": "libssh2",
"version": "1.11.1"
}
```

feat(libssh2): add package

---

packages/gron/brioche.lock
packages/gron/project.bri

This PR adds a package for [gron](https://github.com/tomnomnom/gron), a tool to convert JSON from/to a greppable object notation

Add `gron` package

---

packages/go_mockery/project.bri

Small followup to #445 to use `Brioche.gitCheckout` (instead of `gitCheckout` + `Brioche.gitRef`)

Update `go_mockery` to use `Brioche.gitCheckout`

---

packages/libgit2/brioche.lock
packages/libgit2/project.bri
packages/libssh2/project.bri

Add a new package [`libgit2`](https://github.com/libgit2/libgit2/tree/main): A cross-platform, linkable library implementation of Git that you can use in your application.
```bash
[container@4a5f69ac8e1d workspace]$ brioche build -e test -p packages/libgit2/
Build finished, completed (no new jobs) in 2.31s
Result: a4efe75acf03d41668cad95bbb27ab66d69bb649782bb321825d242e2be8de9d
[container@4a5f69ac8e1d workspace]$ brioche run -e liveUpdate -p packages/libgit2/
Build finished, completed (no new jobs) in 5.76s
{
"name": "libgit2",
"version": "1.9.0",
"repository": "https://github.com/libgit2/libgit2.git"
}
```

feat(libgit2): add package

---

packages/python/project.bri

```bash
[container@4a5f69ac8e1d workspace]$ brioche build -e test -p packages/python
Build finished, completed (no new jobs) in 1.78s
Result: c1061e92814f545f61ccd28a1324f2287104eec5afd8c2a9827f67772be82227
```

feat(python): add test capability

---

packages/rpcsvc_proto/project.bri

```bash
[container@4a5f69ac8e1d workspace]$ brioche build -e test -p packages/rpcsvc_proto/
Build finished, completed (no new jobs) in 1.58s
Result: fb10d1e54235583825a73ab046c3270b618184cabbda157a1df422448d23e8e2
[container@4a5f69ac8e1d workspace]$ brioche run -e liveUpdate -p packages/rpcsvc_proto/
Build finished, completed (no new jobs) in 5.81s
{
"name": "rpcsvc_proto",
"version": "1.4.4",
"repository": "https://github.com/thkukuk/rpcsvc-proto.git"
}
```

feat(rpcsvcproto): add test and liveUpdate capabilities

---

packages/linux/project.bri

```bash
[container@071433f14fbe workspace]$ brioche run -e liveUpdate -p packages/linux/
Build finished, completed (no new jobs) in 5.92s
{
"name": "linux",
"version": "6.14.5",
"extra": {
"majorVersion": "6"
}
}
```

feat(linux): add live update capability

---

packages/curl/project.bri

cURL can support [SCP](https://everything.curl.dev/usingcurl/ssh/) through the library `libssh2`.
Before:
```bash
curl scp://localhost
curl: (1) Protocol "scp" not supported
```
After:
```bash
curl scp://localhost
curl: Couldn't find a known_hosts file
curl: (2) Failed initialization
```

feat(curl): add SCP support

---

packages/libsodium/brioche.lock
packages/libsodium/project.bri

Add a new package [`libsodium`](https://doc.libsodium.org): a modern, easy-to-use software library for encryption, decryption, signatures, password hashing, and more.
```bash
[container@071433f14fbe workspace]$ brioche run -e liveUpdate -p packages/libsodium/
Build finished, completed (no new jobs) in 5.69s
{
"name": "libsodium",
"version": "1.0.20"
}
[container@071433f14fbe workspace]$ brioche build -p packages/libsodium/ -e test
Build finished, completed (no new jobs) in 1.68s
Result: 5856b21de1eb1e62398ebd145ac3db93accac63d6d02d04fd17d33286f8db77a
```

feat(libsodium): add package

---

packages/fzf/brioche.lock
packages/fzf/project.bri

Add a new package [`fzf`](https://github.com/junegunn/fzf): A command-line fuzzy finder
```bash
[container@8682ebba2aec workspace]$ brioche-test packages/fzf/
Build finished, completed (no new jobs) in 2.26s
Result: d33d6ba1bdbdc89b4a046e2830c114d4a707e55973345ffb3cec18e6ab31a136
[container@8682ebba2aec workspace]$ brioche-live-update packages/fzf
Build finished, completed (no new jobs) in 5.85s
{
"name": "fzf",
"version": "0.62.0",
"repository": "https://github.com/junegunn/fzf.git"
}
```

feat(fzf): add package

---

packages/github_cli/project.bri
packages/golangci_lint/brioche.lock
packages/golangci_lint/project.bri
packages/process_compose/project.bri

Add a new package [`golangci-lint`](https://github.com/golangci/golangci-lint): Fast linters runner for Go
```bash
[container@8682ebba2aec workspace]$ brioche-test packages/golangci_lint/
Build finished, completed (no new jobs) in 2.13s
Result: 796eb879fd65f900cd06a41e5c4ede85f9986f53c5853581b8acf9301910b32e
[container@8682ebba2aec workspace]$ brioche-live-update packages/golangci_lint/
Build finished, completed (no new jobs) in 5.97s
{
"name": "golangci_lint",
"version": "2.1.6",
"repository": "https://github.com/golangci/golangci-lint.git",
"extra": {
"buildDate": "2025-05-04"
}
}
```

feat(golangcilint): add package

---

packages/cargo_nextest/brioche.lock
packages/cargo_nextest/project.bri
packages/rust/project.bri

This PR adds a package for [cargo-nextest](https://github.com/nextest-rs/nextest), a fast Rust test runner.
For the package name, it seems like both the README/website/repo bounce between "cargo nextest" and just "nextest". Repology shows [31 repositories use cargo-nextest vs 1 for nextest](https://repology.org/projects/?search=nextest&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=), so I based it on "cargo-nextest".
I also hit a weird build error that seemed to be caused by cargo-chef producing an out-of-date lockfile (https://github.com/LukeMathWalker/cargo-chef/issues/305). We've had issues with cargo-chef before (#189), so I decided to work around this by adding a new `cargoChefPrepare` option to `rust.cargoBuild()`, then set it to false for …

Add `cargo_nextest` package

---

packages/libjpeg/brioche.lock
packages/libjpeg/project.bri

Add a new package [`jpeg`](https://www.ijg.org): a image manipulation library for JPEG image codec.
The name of the package was also a bit hard to find (see #480). The official website uses `jpeg `, Nix uses `libjpeg_original` and homebrew simply uses `jpeg`.
I decide to choose `libjpeg` to make it clear this is the JPEG library and this is not the Turbo JPEG library. And to have a consistency with #480

feat(jpeg): add package

---

packages/cmake/project.bri
packages/curl/project.bri
packages/git/project.bri

This pull request introduces a new `minimal` build option for the `curl` package and updates its dependencies accordingly. The `minimal` option allows building `curl` with only the essential dependencies, which is then utilized in the `cmake` and `git` packages. Additionally, the `brotli` library is added as a dependency for `curl` when the `minimal` option is not enabled.
As display below, cURL still supports SCP, and now supports brotli when building it normally (aka not a minimal version).
```bash
99821  │ curl 8.13.0 (x86_64-pc-linux-gnu) libcurl/8.13.0 OpenSSL/3.5.0 zlib/1.2.13 brotli/1.1.0 zstd/1.5.5 libpsl/0.21.5 libssh2/1.11.1
│ Release-Date: 2025-04-02
│ Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps …
```

Add brotli support to cURL

---

packages/libjpeg_turbo/brioche.lock
packages/libjpeg_turbo/project.bri

Add a new package [`libjpeg-turbo`](https://www.libjpeg-turbo.org): a JPEG image codec that uses SIMD instructions (MMX, SSE2, AVX2, Neon, AltiVec) to accelerate baseline JPEG compression and decompression.
The name of the package was a bit hard to find, since there is also a libjpeg library.
The official website seems to refer to `libjpeg-turbo`, but Nix uses 3 different names `libjpeg-turbo`, `libjpeg8`, `libjpeg` whereas homebrew simply uses `jpeg-turbo`. Interesting enough Ubuntu uses the name `libjpeg-turbo8`.
So, I decide to choose `libjpeg_turbo` as it seems clear enough of what this package refers to.

feat(jpegturbo): add package

---

packages/libdeflate/brioche.lock
packages/libdeflate/project.bri

Add a new package [`libdeflate`](https://github.com/ebiggers/libdeflate): a Heavily optimized library for DEFLATE/zlib/gzip compression and decompression
```bash
[container@e9ad9fa14b46 workspace]$ bt packages/libdeflate/
Build finished, completed (no new jobs) in 1.75s
Result: 0001f38b3b23fd937d28df53ef273c4bfab4508c2fc3dd0e15ea45b9aa43102a
[container@e9ad9fa14b46 workspace]$ blu packages/libdeflate/
0.07s ✓ Process 236
Build finished, completed 1 job in 5.60s
{
"name": "libdeflate",
"version": "1.24",
"repository": "https://github.com/ebiggers/libdeflate"
}
```

feat(libdeflate): add package

---

packages/jjui/brioche.lock
packages/jjui/project.bri

Add a new package [`jjui`](https://github.com/idursun/jjui): a Text User Interface (TUI) designed for interacting with the Jujutsu version control system.
Thanks to the [PR](https://github.com/idursun/jjui/pull/81), we can now set the ld flags to correctly report the version of jjui. See the discussion [here](https://github.com/idursun/jjui/discussions/80).
```bash
[container@6957380374c0 workspace]$ bt packages/jjui
Build finished, completed (no new jobs) in 1.85s
Result: 6390c6b2f3842bf7836817efe2c88b7016a010b085ead57acb06d2a03b6f9ff1
[container@6957380374c0 workspace]$ blu packages/jjui
Build finished, completed (no new jobs) in 6.05s
{
"name": "jjui",
"version": "0.8.8",
"repository": "https://github.com/idursun/jjui.git"
}
```

feat(jjui): add package

---

packages/cmctl/brioche.lock
packages/cmctl/project.bri

Add a new package [`cmctl`](https://github.com/cert-manager/cmctl): a command line utility that makes cert-manager'ing easier.
```bash
[container@6957380374c0 workspace]$ blu packages/cmctl/
Build finished, completed (no new jobs) in 4.85s
{
"name": "cmctl",
"version": "2.2.0",
"repository": "https://github.com/cert-manager/cmctl.git"
}
[container@6957380374c0 workspace]$ bt packages/cmctl/
Build finished, completed (no new jobs) in 1.90s
Result: d11268dc3729c0f32d2acdf7c712a0b37cbb697c544b1e0478e4910d665c03ad
```

feat(cmctl): add package

---

.github/workflows/_check.yml
.github/workflows/build.yml
.github/workflows/live-updates.yml
packages/std/extra/live_update_from_github_releases.bri

This PR updates the Nushell script for `std.liveUpdateFromGithubReleases()` to authenticate the GitHub API request if the `$GITHUB_TOKEN` env var is set. GitHub recently announced that they were adding more restrictive rate limits for unauthenticated requests: https://github.blog/changelog/2025-05-08-updated-rate-limits-for-unauthenticated-requests/
Experimentally, the endpoint `https://api.github.com/repos/{owner}/{repo}/releases/latest` has a rate limit of 60 when unauthenticated, and resets on the hour (which can be seen with the `x-ratelimit-limit` and `x-ratelimit-reset` response headers). When using a token, the rate limit increases to 5,000 tokens (but seems to reset _after an hour_, not _on the hour_). We've got >100 packages, and we've already seen some live-update runs fail. …

Optionally authenticate requests in `std.liveUpdateFromGithubReleases`

---

packages/caddy/brioche.lock
packages/caddy/project.bri
packages/xcaddy/brioche.lock
packages/xcaddy/inject-version-information.patch
packages/xcaddy/project.bri

Extract from `caddy` the package `xcaddy`. It let us to rely on `std.liveUpdateFromGithubReleases()` for both packages now.
```bash
[container@ab3f489dbbf1 workspace]$ blu packages/xcaddy/
Build finished, completed 8 jobs in 1m 0s
{
"name": "xcaddy",
"version": "0.4.4",
"repository": "https://github.com/caddyserver/xcaddy.git"
}
[container@ab3f489dbbf1 workspace]$ bt packages/xcaddy/
Build finished, completed (no new jobs) in 2.01s
Result: 2e0ddceede13e1bf3c79fdebeb98ac4ee2ed9ce05f2f22ee0b31003255a7738d
```
```bash
[container@ab3f489dbbf1 workspace]$ blu packages/caddy/
Build finished, completed (no new jobs) in 4.95s
{
"name": "caddy",
"version": "2.10.0",
"repository": "https://github.com/caddyserver/caddy.git"
}
[container@ab3f489dbbf1 …
```

Add xcaddy package

---

packages/gosec/brioche.lock
packages/gosec/project.bri

Add a new package `gosec`: inspects source code for security problems by scanning the Go AST and SSA code representation.
```bash
[container@ab3f489dbbf1 workspace]$ blu packages/gosec/
Build finished, completed (no new jobs) in 4.69s
{
"name": "gosec",
"version": "2.22.4",
"repository": "https://github.com/securego/gosec.git"
}
[container@ab3f489dbbf1 workspace]$ bt packages/gosec/
Build finished, completed (no new jobs) in 1.67s
Result: b72dff9b3641e5520a650996aa30aa3d7e28a9a37e9a0be57fdea50be614203c
```

feat(gosec): add package

---

packages/std/extra/live_update_from_github_releases.bri

Follow-up to #488
This PR fixes a typo in #488 that was causing authenticating to the GitHub API to fail (the script was adding an extra `$` to the authorization token). I also spotted another typo in the version validation while I was debugging

Fix typos in `std.liveUpdateFromGithubReleases()` script

---

packages/trivy/brioche.lock
packages/trivy/project.bri

Add a new package [`trivy`](https://github.com/aquasecurity/trivy): find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code repositories, clouds and more
```bash
[container@28d2ad4a7808 workspace]$ blu packages/trivy
Build finished, completed (no new jobs) in 4.22s
{
"name": "trivy",
"version": "0.62.1",
"repository": "https://github.com/aquasecurity/trivy.git"
}
[container@28d2ad4a7808 workspace]$ bt packages/trivy
Build finished, completed (no new jobs) in 1.71s
Result: 90775a409101de561cdf02ac070e9cf796503229db2c8fd6dab55f3c2f2b9872
```

feat(trivy): add package

---

packages/kor/brioche.lock
packages/kor/project.bri

Add a new package [`kor`](https://github.com/yonahd/kor): a Golang Tool to discover unused Kubernetes Resources
```bash
[container@f4786e3b97ec workspace]$ blu packages/kor
Build finished, completed (no new jobs) in 4.18s
{
"name": "kor",
"version": "0.6.1",
"repository": "https://github.com/yonahd/kor.git"
}
[container@f4786e3b97ec workspace]$ bt packages/kor
Build finished, completed (no new jobs) in 1.65s
Result: 8452674ffbf8a28816d0196f0c078c8e0ff328f155d30deded11769f210a3b40
```

feat(kor): add package

---

packages/cargo_mutants/brioche.lock
packages/cargo_mutants/project.bri

Add a new package [`cargo_mutants`](https://github.com/sourcefrog/cargo-mutants): inject bugs and see if your tests catch them!
```bash
[container@fad58cc35c32 workspace]$ bt packages/cargo_mutants/
Result: 5e399c39b79c96aa9b7f80baaf1568405869fe46aeac2b7a3bc93db3d825d559
[container@fad58cc35c32 workspace]$ blu packages/cargo_mutants/
Build finished, completed (no new jobs) in 4.39s
{
"name": "cargo_mutants",
"version": "25.0.1",
"repository": "https://github.com/sourcefrog/cargo-mutants.git"
}
```

feat(cargomutants): add package

---

packages/cargo_about/brioche.lock
packages/cargo_about/project.bri

Add a new package [`cargo_about`](https://github.com/EmbarkStudios/cargo-about): a cargo plugin to generate list of all licenses for a crate 
```bash
[container@1a7e3f630874 workspace]$ blu packages/cargo_about/
Build finished, completed (no new jobs) in 3.97s
{
"name": "cargo_about",
"version": "0.7.1",
"repository": "https://github.com/EmbarkStudios/cargo-about.git"
}
[container@1a7e3f630874 workspace]$ bt packages/cargo_about/
Build finished, completed (no new jobs) in 2.23s
Result: 78432915bfe845ba398ce346e621aed23506da5d124d8c4de921d7a93b59393c
```

feat(cargoabout): add package

---

packages/bash_language_server/brioche.lock
packages/bash_language_server/project.bri

Add a new package [`bash_language_server`](https://github.com/bash-lsp/bash-language-server): a language server for Bash
```bash
[container@30423e35af26 workspace]$ blu packages/bash_language_server/
Build finished, completed (no new jobs) in 3.98s
{
"name": "bash_language_server",
"version": "5.6.0",
"packageName": "bash-language-server"
}
[container@30423e35af26 workspace]$ bt packages/bash_language_server/
Build finished, completed (no new jobs) in 4.25s
Result: 36e0a1276abfab6dbd9f09a64a25e4b53bca383801f5d854ba96d7a68c927217
```

feat(bashlanguageserver): add package

---

packages/uv/brioche.lock
packages/uv/project.bri

This PR adds a new package for [uv](https://docs.astral.sh/uv/), an extremely fast Python package and project manager, written in Rust.

Add `uv` package

---

packages/cargo_audit/brioche.lock
packages/cargo_audit/project.bri

Add a new package [`cargo_audit`](https://github.com/rustsec/rustsec): RustSec API & Tooling
```bash
[container@d994e4df4ab5 workspace]$ blu packages/cargo_audit/
Build finished, completed (no new jobs) in 4.41s
{
"name": "cargo_audit",
"version": "0.21.2",
"repository": "https://github.com/rustsec/rustsec.git"
}
[container@d994e4df4ab5 workspace]$ bt packages/cargo_audit/
Build finished, completed (no new jobs) in 2.34s
Result: 36414b2e2f9227c22cae26077c60b268874e4589f51810a9d64c03d54a32f3c8
```

feat(cargoaudit): add package

---

packages/mitmproxy/brioche.lock
packages/mitmproxy/project.bri

This PR adds a package for [mitmproxy](https://mitmproxy.org/), a free and open source interactive HTTPS proxy
This uses the newly-added uv package (#520). uv is _really_ slick, but using it for packaging was pretty painful. There's a lot that should probably be cleaned up. Longer term, I think it'd make sense to have a utility to package a project that uses  uv (similar to `nodejs.npmInstall()`, etc.)

Add `mitmproxy` package

---

packages/sccache/brioche.lock
packages/sccache/project.bri

Add a new package [`sccache`](https://github.com/mozilla/sccache): a ccache-like tool. It is used as a compiler wrapper and avoids compilation when possible. Sccache has the capability to utilize caching in remote storage environments, including various cloud storage options, or alternatively, in local storage.
```bash
[container@d9c3552e7d91 workspace]$ blu packages/sccache/
Build finished, completed (no new jobs) in 3.94s
{
"name": "sccache",
"version": "0.10.0",
"repository": "https://github.com/mozilla/sccache.git"
}
[container@d9c3552e7d91 workspace]$ bt packages/sccache/
Build finished, completed (no new jobs) in 2.31s
Result: b1063cf2fa912c519912da7840f33c0e75d1088e7e08ce2f3951bc1ae007eed1
```

feat(sccache): add package

---

packages/delve/brioche.lock
packages/delve/project.bri

Add a new package [`delve`](https://github.com/go-delve/delve): a debugger for the Go programming language.
```bash
[container@395d2febf6a6 workspace]$ bt packages/delve
Build finished, completed (no new jobs) in 1.65s
Result: 6b33097ec4a4d1705dd7d176e46a0568b7f6f1f4bf1c6c74ca77d5dec5109160
[container@395d2febf6a6 workspace]$ blu packages/delve/
Build finished, completed (no new jobs) in 4.11s
{
"name": "delve",
"version": "1.24.2",
"repository": "https://github.com/go-delve/delve.git"
}
```

feat(delve): add package

---

packages/cargo_bloat/brioche.lock
packages/cargo_bloat/project.bri

Add a new package [`cargo_bloat`](https://github.com/RazrFalcon/cargo-bloat): a tool to find out what takes most of the space in your executable.
```bash
[container@395d2febf6a6 workspace]$ blu packages/cargo_bloat/
Build finished, completed (no new jobs) in 4.05s
{
"name": "cargo_bloat",
"version": "0.12.1",
"repository": "https://github.com/RazrFalcon/cargo-bloat.git"
}
[container@395d2febf6a6 workspace]$ bt packages/cargo_bloat/
Build finished, completed (no new jobs) in 2.32s
Result: 8a777a57530d5271890ec3c26acd21038a671c9fc20415db02bc4e50605170d1
```

feat(cargobloat): add package

---

packages/cargo_udeps/brioche.lock
packages/cargo_udeps/project.bri

Add a new package [`cargo_udeps`](https://github.com/est31/cargo-udeps): Find unused dependencies in Cargo.toml 
```bash
[container@178f927a158d workspace]$ blu packages/cargo_udeps/
Build finished, completed (no new jobs) in 4.25s
{
"name": "cargo_udeps",
"version": "0.1.55",
"repository": "https://github.com/est31/cargo-udeps.git"
}
[container@178f927a158d workspace]$ bt packages/cargo_udeps/
Build finished, completed (no new jobs) in 2.36s
Result: 2f29c1e61a09b3dc4c411a1378378dfa5626ec561fbb078b27c823a77c6d463a
```

feat(cargoudeps): add package

---

packages/cargo_msrv/brioche.lock
packages/cargo_msrv/project.bri

Add a new package [`cargo_msrv`](https://github.com/foresterre/cargo-msrv): find the minimum supported Rust version (MSRV) for your project.
```bash
[container@178f927a158d workspace]$ blu packages/cargo_msrv/
Build finished, completed (no new jobs) in 3.95s
{
"name": "cargo_msrv",
"version": "0.18.4",
"repository": "https://github.com/foresterre/cargo-msrv.git"
}
[container@178f927a158d workspace]$ bt packages/cargo_msrv/
Build finished, completed (no new jobs) in 2.40s
Result: 3c4a358e57235b5a05afff12a05461f24f82254129eb6b73960417e03566235d
```

feat(cargomsrv): add package

---

packages/vegeta/brioche.lock
packages/vegeta/project.bri

Add a new package `[vegeta](https://github.com/tsenart/vegeta)`: a HTTP load testing tool and library
```bash
[container@178f927a158d workspace]$ bt packages/vegeta/
18689  │ Version: 12.12.0
│ Commit: 03ca49e9b419c106db29d687827c4c823d8b8ece
│ Runtime: go1.24.3 linux/amd64
│ Date: 2025-04-07
0.15s ✓ Process 18689
Build finished, completed 1 job in 3.30s
Result: dfb9e47edd91844e746dfbcbd8ffc52dd984e62836fe1c56c76f03da633b0910
[container@178f927a158d workspace]$ blu packages/vegeta/
Build finished, completed (no new jobs) in 5.25s
{
"name": "vegeta",
"version": "12.12.0",
"repository": "https://github.com/tsenart/vegeta.git",
"extra": {
"releaseDate": "2024-07-29"
}
}
```

feat(vegeta): add package

---

packages/zziplib/brioche.lock
packages/zziplib/project.bri

Add a new package `[zziplib](https://github.com/gdraheim/zziplib)`: provides read access on ZIP-archives and unpacked data. It features an additional simplified API following the standard Posix API for file access
```bash
[container@725c7be98007 workspace]$ blu packages/zziplib/
Build finished, completed (no new jobs) in 3.89s
{
"name": "zziplib",
"version": "0.13.79",
"repository": "https://github.com/gdraheim/zziplib.git"
}
[container@725c7be98007 workspace]$ bt packages/zziplib/
Build finished, completed (no new jobs) in 1.73s
Result: 070605c322893853bd0825ca8cf387d79665f9885dabbae5553f35659763f3f6
```

feat(zziplib): add package

---

packages/gtest/brioche.lock
packages/gtest/project.bri

Add a new package `[gtest](https://github.com/google/googletest)`: GoogleTest - Google Testing and Mocking Framework
```bash
[container@229b00addb2f workspace]$ blu packages/gtest/
Build finished, completed (no new jobs) in 3.93s
{
"name": "gtest",
"version": "1.17.0",
"repository": "https://github.com/google/googletest.git"
}
[container@229b00addb2f workspace]$ bt packages/gtest
Build finished, completed (no new jobs) in 1.68s
Result: a447d14fdcea861408dd77dc055814db266543d3e45fb6ecb9590fe66b98c26a
```

feat(gtest): add package

---

packages/markdownlint_cli/brioche.lock
packages/markdownlint_cli/project.bri

Add a new package `[markdownlint_cli](https://github.com/igorshubovych/markdownlint-cli)`: a MarkdownLint Command Line Interface
```bash
[container@b83650471a4e workspace]$ blu packages/markdownlint_cli
0.08s ✓ Process 78
Build finished, completed 1 job in 6.17s
{
"name": "markdownlint_cli",
"version": "0.45.0",
"packageName": "markdownlint-cli"
}
[container@b83650471a4e workspace]$ bt packages/markdownlint_cli
Build finished, completed (no new jobs) in 4.55s
Result: de1b5c0f9318732fab79781ad1c4f09676d171ddc38ecd8e569ff6d1b5e01596
```

feat(markdownlint): add package

---

packages/mitmproxy/project.bri

This PR updates the `mitmproxy` package
I didn't realize when you do `uv tool install $name`, it treats `$name` as a normal PyPI package name. In other words, it's basically equivalent to doing `pip install $name`!
Instead, it looks like `uv tool install .` will install a package from the current directory, which (I think) is what we want. It doesn't seem like there's a way to enforce the lockfile from this command, so I'm still not 100% sure this is fully pure yet? At a minimum, it seems like this change resolves some of the live-update issues we've seen around mitmproxy (#563, #569, #573)

Fix impurity in `mitmproxy` package

---

packages/markdownlint_cli2/brioche.lock
packages/markdownlint_cli2/project.bri

Add a new package `[markdownlint_cli2](https://github.com/DavidAnson/markdownlint-cli2)`: a  fast, flexible, configuration-based command-line interface for linting Markdown/CommonMark files with the markdownlint library
```bash
[container@6f9294b2850f workspace]$ bt packages/markdownlint_cli2
Build finished, completed (no new jobs) in 4.55s
Result: 16bc51ec665fe3f4566a7c506975053f5159e6f7554cf64d4495d23394bd53a6
[container@3db101c74769 workspace]$ blu packages/markdownlint_cli2
Build finished, completed (no new jobs) in 4.22s
{
"name": "markdownlint_cli2",
"version": "0.18.1",
"packageName": "markdownlint-cli2"
}
``

feat(markdownlintcli2): add package

---

.github/workflows/live-updates.yml
packages/aws_cli/project.bri
packages/cargo_bloat/project.bri
packages/git/project.bri
packages/go/project.bri
packages/joshuto/project.bri
packages/nasm/project.bri
packages/nodejs/project.bri
packages/rust/project.bri
packages/s2argv_execs/project.bri
packages/uthash/project.bri
packages/vdeplug4/project.bri
packages/zziplib/project.bri

This PR fixes 2 issues with live updates:
1. Fix "Live Update" GitHub Actions workflow not cleaning up properly between packages. This caused failures e.g. in [Live Updates#27](https://github.com/brioche-dev/brioche-packages/actions/runs/15347290763), due to `git` leaving a dirty lockfile around, causing subsequent packages to fail. This PR uses `git restore .` to clean up any modified files
2. Fix regex matching across several packages. This was causing issues with git, which recently had a `v2.50.0-rc0` release. The regex for matching tags matched this release but not the `-rc0` part, which tried to live-update to `2.50.0`. The fix was to just update the regex to exclude tags with anything following the patch number in the version (a.k.a prerelease versions, which we shouldn't try to …

Fix live update errors

---

packages/toml11/brioche.lock
packages/toml11/project.bri

Add a new package [`toml11`](https://github.com/ToruNiina/toml11): TOML for Modern C++
```bash
[container@0f0fc8649678 workspace]$ blu packages/toml11/
Build finished, completed (no new jobs) in 4.12s
{
"name": "toml11",
"version": "4.4.0",
"repository": "https://github.com/ToruNiina/toml11"
}
[container@0f0fc8649678 workspace]$ bt packages/toml11/
Build finished, completed (no new jobs) in 1.88s
Result: a685197f6323b6e527a5a997481dc0c1f5fbf98f057cdefc50836698a6a7a430
```

feat(toml11): add package

---

packages/libevent/brioche.lock
packages/libevent/project.bri

Add a new package [`libevent`](https://github.com/libevent/libevent): an event notification library
```bash
[container@2e2630b7574b workspace]$ bt packages/libevent/
Build finished, completed (no new jobs) in 2.85s
Result: 7b980d211b166405910f42b328e3fa9801ccde0d8beb322ee9136e590abb8c0b
[container@2e2630b7574b workspace]$ blu packages/libevent/
Build finished, completed (no new jobs) in 4.23s
{
"name": "libevent",
"version": "2.1.12",
"repository": "https://github.com/libevent/libevent"
}
```

feat(libevent): add package

---

packages/editline/brioche.lock
packages/editline/project.bri

Add a new package [`editline`](https://github.com/troglobit/editline): a small replacement for GNU readline() for UNIX
```bash
[container@0f0fc8649678 workspace]$ blu packages/editline/
Build finished, completed (no new jobs) in 4.05s
{
"name": "editline",
"version": "1.17.1",
"repository": "https://github.com/troglobit/editline"
}
[container@0f0fc8649678 workspace]$ bt packages/editline/
Build finished, completed (no new jobs) in 1.70s
Result: f95a716ffcade281bfc188ada498d6a1f928912570c75e56cf8fad58fb3d638e
```

feat(editline): add package

---

packages/cmake/project.bri
packages/libgit2/project.bri

Resolve an issue when using `cmakeBuild` when `lib`already exists and we want to symlink `lib64` folder.
Before (when building `libgit2` package):
```bash
[container@0f0fc8649678 workspace]$ ls /tmp/output/lib/
cmake/ lib64
[container@0f0fc8649678 workspace]$ ls /tmp/output/lib64
libgit2.so  libgit2.so.1.9  libgit2.so.1.9.0  pkgconfig
[container@0f0fc8649678 workspace]$ ls -al /tmp/output/lib/lib64
lrwxrwxrwx 1 container container 5 Jun  1 19:33 /tmp/output/lib/lib64 -> lib64
```
After (when building `libgit2` package):
```bash
[container@0f0fc8649678 workspace]$ ls /tmp/output/lib
cmake  libgit2.so  libgit2.so.1.9  libgit2.so.1.9.0  pkgconfig
[container@0f0fc8649678 workspace]$ ls /tmp/output/lib64
libgit2.so  libgit2.so.1.9  libgit2.so.1.9.0  pkgconfig
[container@0f0fc8649678 …
```

Fix a possible bad symlink of lib64 folder with cmakeBuild()

---

packages/nlohmann_json/brioche.lock
packages/nlohmann_json/project.bri

Add a new recipe [`nlohmann_json`](https://github.com/nlohmann/json): JSON for Modern C++
```bash
[container@f36faaa936d4 workspace]$ bt packages/nlohmann_json/
Build finished, completed (no new jobs) in 2.00s
Result: 19936c49a3847e8d2a9c102358ec89cb1abf772ed96baee657a24a7d6c7283e0
[container@f36faaa936d4 workspace]$ blu packages/nlohmann_json/
Build finished, completed (no new jobs) in 4.26s
{
"name": "nlohmann_json",
"version": "3.12.0",
"repository": "https://github.com/nlohmann/json.git"
}
```

feat(nlohmannJson): add package

---

packages/boost/brioche.lock
packages/boost/project.bri

Add a new package [`boost`](https://github.com/boostorg/boost): provides free peer-reviewed portable C++ source libraries
```bash
[container@1ea5fc976642 workspace]$ bt packages/boost/
Build finished, completed (no new jobs) in 1.71s
Result: 5da2013f5155b281439281bfb89254ddd4e4226c9a2b3122a57aef2f4cd610dc
[container@1ea5fc976642 workspace]$ blu packages/boost/
Build finished, completed (no new jobs) in 4.43s
{
"name": "boost",
"version": "1.88.0",
"repository": "https://github.com/boostorg/boost"
}
```

feat(boost): add package

---

packages/curl/project.bri

As shown below, there is no need to expose `CMAKE_PREFIX_PATH` in the `curl` recipe, since there is no CMake files present.
```bash
[container@fd7763c91f9e workspace]$ bb packages/curl
Build finished, completed (no new jobs) in 1.84s
Result: 3ef6623484d67f7cdca559b6261400a85564f8390fa034bc39ebdf56a11db755
Writing output
Wrote output to /tmp/output
[container@fd7763c91f9e workspace]$ find /tmp/output -name "*.cmake"
```

refactor(curl): remove unnecessary CMAKE_PREFIX_PATH

---

examples/c_hello/project.bri
examples/go_cli/project.bri
examples/nodejs_frontend/project.bri
examples/rust_backend/project.bri
packages/std/extra/bash_runnable.bri

Just to enforce the signatures of functions found in the examples. It'll help `brioche check` for better checking possible unwanted mismatches

chore: add explicit type signatures to examples' export

---

packages/krb5/brioche.lock
packages/krb5/project.bri

Add a new package [`krb5`](https://web.mit.edu/Kerberos/): kerberos is a network authentication protocol.
```bash
[container@b2ec1fbd59c7 workspace]$ blu packages/krb5/
Build finished, completed (no new jobs) in 4.55s
{
"name": "krb5",
"version": "1.21.3",
"extra": {
"majorVersion": "1",
"minorVersion": "21"
}
}
[container@b2ec1fbd59c7 workspace]$ bt packages/krb5/
60993  │ 1.21.3
0.11s ✓ Process 60993
Build finished, completed 1 job in 24.13s
Result: 35ffee22e65e83967d8b3521cd10f87060079206a858020f0ffade5a68da05a0
```

feat(krb5): add package

---

packages/jujutsu/brioche.lock
packages/jujutsu/project.bri

This PR upgrades the `jujutsu` package to [v0.30.0](https://github.com/jj-vcs/jj/releases/tag/v0.30.0)
From the release notes, jj no longer depends on `openssl`, so I manually removed it as a dependency. Also, I updated the repo URL (from https://github.com/martinvonz/jj.git, which now redirects to https://github.com/jj-vcs/jj.git)

[jujutsu] Upgrade to v0.30.0

---

packages/readline/brioche.lock
packages/readline/project.bri

Add a new package (already part of the std.toolchain) [readline](https://tiswww.cwru.edu/php/chet/readline/rltop.html): a library that provides a set of functions for use by applications that allow users to edit command lines as they are typed in.
```bash
[container@bbf67fa58b38 workspace]$ bt packages/readline/
Build finished, completed (no new jobs) in 1.57s
Result: e987e736e4b4d57bd6bd43d2207c70dc1db3d99d86c999ed53fe12bfcc2d2cce
[container@bbf67fa58b38 workspace]$ blu packages/readline/
Build finished, completed (no new jobs) in 4.22s
{
"name": "readline",
"version": "8.2.13"
}
```

feat(readline): add package

---

packages/yaml_language_server/brioche.lock
packages/yaml_language_server/project.bri

Add a new package [`yaml_language_server`](https://github.com/redhat-developer/yaml-language-server): a Language Server for YAML Files
```bash
[container@a46679c949d8 workspace]$ blu packages/yaml_language_server/
Build finished, completed (no new jobs) in 4.42s
{
"name": "yaml_language_server",
"version": "1.18.0",
"packageName": "yaml-language-server"
}
[container@a46679c949d8 workspace]$ bt packages/yaml_language_server/
Build finished, completed (no new jobs) in 4.01s
Result: 11c4385a9ae296aad626e1c69239d0e2b98ca544cf0c29fbad3730ba13c19f6b
```

feat(yamlLanguageServer): add package

---

packages/dependabot/brioche.lock
packages/dependabot/project.bri

Add a new package [`dependabot`](https://github.com/dependabot/cli): A tool for testing and debugging Dependabot update jobs.
```bash
[container@brioche-package-devenv workspace]$ bt packages/dependabot/
5301   │ dependabot version 1.66.0
0.16s ✓ Process 5301
42.63s ✓ Process 2773
Build finished, completed 2 jobs in 46.62s
Result: ecb7f7fecaf48f035813dac71de4110c47a651518bbc307228257908b7a47960
[container@brioche-package-devenv workspace]$ blu packages/dependabot/
Build finished, completed (no new jobs) in 4.06s
{
"name": "dependabot",
"version": "1.66.0",
"repository": "https://github.com/dependabot/cli"
}
```

feat(dependabot): add package

---

packages/renovate/brioche.lock
packages/renovate/project.bri

Add a new package [`renovate`](https://github.com/renovatebot/renovate): a cross-platform Dependency Automation by Mend.io
```bash
[jaudiger@lima-fedora-x86-64 brioche-packages]$ brioche build -e test -p packages/renovate/
19948  │ 40.48.5
35.25s ✓ Process 19948
Build finished, completed 1 job in 3m32s
Result: 9ad7136cb3abd52e0a3c44ac20e0888d88080da1f8fd36b4873589fb0a0b376d
[jaudiger@lima-fedora-x86-64 brioche-packages]$ brioche run -e liveUpdate -p packages/renovate/
Build finished, completed (no new jobs) in 49.31s
{
"name": "renovate",
"version": "40.54.1"
}
```

feat(renovate): add package

---

packages/patch/brioche.lock
packages/patch/project.bri

Add a new package [`patch`](https://savannah.gnu.org/projects/patch) (that is already part of the std.toolchain(), though): it takes a patch file containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions
```bash
jaudiger@lima-ubuntu:/Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages$ brioche build -e test -p packages/patch/
Build finished, completed (no new jobs) in 1.67s
Result: 154c23d4eae298ea97d4b74d58bce9205e4f8213fc8a397af2c311bc6657dd39
jaudiger@lima-ubuntu:/Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages$ brioche run -e liveUpdate -p packages/patch/
Build finished, completed (no new jobs) in 4.30s
{
"name": "patch",
"version": …
```

feat(patch): add package

---

packages/cargo_chef/brioche.lock
packages/cargo_chef/project.bri
packages/rust/brioche.lock
packages/rust/project.bri

Add a new package [`cargo_chef`](https://github.com/LukeMathWalker/cargo-chef): a cargo-subcommand to speed up Rust Docker builds using Docker layer caching.
This one is yours @kylewlacy, I just cherry picked your changes to upstream from https://github.com/brioche-dev/brioche-packages/tree/build/wip-aarch64-linux.

feat(cargo_chef): add package

---

packages/cmake/project.bri
packages/curl/project.bri
packages/git/project.bri
packages/go/project.bri
packages/linux/project.bri
packages/nodejs/project.bri
packages/nushell/project.bri
packages/rust/project.bri
packages/std/core/global.bri
packages/std/core/recipes/directory.bri
packages/std/core/recipes/download.bri
packages/std/core/recipes/file.bri
packages/std/core/recipes/glob.bri
packages/std/core/recipes/process.bri
packages/std/core/recipes/recipe.bri
packages/std/core/recipes/symlink.bri
packages/std/core/semver.bri
packages/std/core/utils.bri
packages/std/extra/apply_patch.bri
packages/std/extra/bash_runnable.bri
packages/std/extra/extra_global.bri
packages/std/extra/live_update_from_github_releases.bri
packages/std/extra/oci_container_image.bri
packages/std/extra/run_bash.bri
packages/std/extra/runnable.bri
packages/std/extra/set_env.bri
packages/std/extra/with_runnable_link.bri

This PR standardizes the documentation style by replacing informal option lists with TSDoc-style `@param`, `@returns`, and `@example` annotations. This improves code readability and consistency, plus it helps for better IDE integration when `bri` files are configured to be recognized as TypeScript files.

chore: update function comments to use TSDoc style

---

packages/libfaketime/brioche.lock
packages/libfaketime/project.bri
packages/libfaketime/resolve-library-path.patch

Add a new package [`libfaketime`](https://github.com/wolfcw/libfaketime): libfaketime modifies the system time for a single application
```bash
[container@bbf67fa58b38 workspace]$ bt packages/libfaketime/
880    │ faketime: Version 0.9.11
│ For usage information please use 'faketime --help'.
0.11s ✓ Process 880
Build finished, completed 1 job in 2.78s
Result: ac4a56db725ea7d23087d32a280bf45e79ec696b7d02fea0d67d0276b6c442d9
[container@bbf67fa58b38 workspace]$ blu packages/libfaketime/
0.06s ✓ Process 946
Build finished, completed 1 job in 5.34s
{
"name": "libfaketime",
"version": "0.9.11",
"repository": "https://github.com/wolfcw/libfaketime"
}
```

feat(libfaketime): add package

---

packages/nlohmann_json/project.bri
packages/std/extra/pkg_config_make_paths_relative.bri

This PR includes changes to improve the handling of pkg-config directories to better handle search path outside of the usual `lib` folder. Some packages put their pkg-config files inside the `share` folder. And we were having a workaround for that in the `nlohmann_json` recipe.
I'm also working on another [recipe](https://www.linuxfromscratch.org/blfs/view/svn/x/util-macros.html) (I'll upstream soon) that also exposes their pkg-config files in the same `share` folder. So, I thought it was worth the modification here. Since it could reduce the burden when packaging new libraries by abstracting the usual locations for the pkg-config files.
```bash
jaudiger@lima-ubuntu:/Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages$ rm -rf /tmp/output; brioche build -o /tmp/output -p …
```

Update pkgconfig relative paths

---

packages/wabt/brioche.lock
packages/wabt/project.bri

This PR adds a new package for [WABT](https://github.com/WebAssembly/wabt): the WebAssembly Binary Toolkit.
I needed to avoid using the `cmakeBuild()` function for the time being, since the CMake build seems to try generating source files at build time (see #677).
Also, as mentioned in a comment in the `.bri` file, it seems like the latest WABT release is reporting the incorrect version number (1.0.36 instead of 1.0.37). I saw it mentioned in a comment upstream (https://github.com/WebAssembly/wabt/issues/2550#issuecomment-2697494141), I'm guessing it'll be fixed in the next release

Add `wabt` package

---

README.md
packages/cmake/project.bri
packages/nodejs/project.bri
packages/std/core/global.bri
packages/std/core/recipes/directory.bri
packages/std/core/recipes/download.bri
packages/std/core/recipes/glob.bri
packages/std/core/recipes/recipe.bri
packages/std/core/recipes/symlink.bri
packages/std/core/semver.bri
packages/std/core/utils.bri
packages/std/extra/bash_runnable.bri
packages/std/extra/run_bash.bri
packages/std/extra/runnable.bri
packages/std/extra/set_env.bri
packages/std/extra/with_runnable_link.bri

This PR just focuses on improving code documentation by standardizing punctuation in parameter descriptions across various files. All changes involve adding a period at the end of parameter descriptions in JSDoc comments to ensure consistency and clarity.

Uniformize TSDoc comments

---

packages/util_macros/brioche.lock
packages/util_macros/project.bri

Add a new package [`util_macros`](https://cgit.freedesktop.org/xorg/util/macros/): util-macros package contains the m4 macros used by all of the Xorg packages
```bash
> limactl shell ubuntu -- brioche build -e test -p packages/util_macros
Build finished, completed (no new jobs) in 1.63s
Result: 93def359accdbc05d51ff03b584c7eb326b40cc84adc42c5eab69fefa710f9ee
> limactl shell ubuntu -- brioche run -e liveUpdate -p packages/util_macros
0.07s ✓ Process 8592
Build finished, completed 1 job in 10.47s
{
"name": "util_macros",
"version": "1.20.2"
}
jaudiger@lima-ubuntu:/Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages$ rm -rf /tmp/output; brioche build -o /tmp/output -p packages/util_macros/
Build finished, completed (no new jobs) in 1.67s
Result: …
```

feat(util_macros): add package

---

packages/libssh2/project.bri

I missed it in https://github.com/brioche-dev/brioche-packages/pull/587. Nothing more. I just saw it yesterday while looking at a completely different things ^^'

fix(libssh2): add a missing `std.pkgConfigMakePathsRelative` when building the package

---

packages/git/project.bri

With the release of Git 2.49, we can rewrite our bash script to clone a repository at a specific revision without the history. See https://about.gitlab.com/blog/whats-new-in-git-2-49-0/#thin-clone-using---revision.
I benchmarked the new approach with `hyperfine`, and it's at least 1.1 times faster:
```bash
➜ export REPOSITORY="https://github.com/brioche-dev/brioche.git"
➜ export COMMIT="a4c817f0acc16536e4e528170bec0ee9782c4528"
➜ hyperfine \
--prepare 'TMP=$(mktemp -d -p ./temp) && echo $TMP > .tmpdir' \
--conclude 'rm -rf "$(cat .tmpdir)" && rm .tmpdir' \
'git -c advice.detachedHead=false clone --depth 1 --revision=$COMMIT $REPOSITORY "$(cat .tmpdir)"' \
'cd "$(cat .tmpdir)" && \
git -c init.defaultBranch=main init && \
git remote add origin $REPOSITORY && \
git fetch --depth 1 origin …
```

perf(git): use newer git clone argument to clone a single revision

---

packages/git/project.bri
packages/go/project.bri

Follow up of https://github.com/brioche-dev/brioche-packages/pull/334, but at the time of this PR, the packages [`git`](https://github.com/jaudiger/brioche-packages/blob/9afeba281e554ee1eefef388f1ed35d457617466/packages/git/project.bri) and [`go`](https://github.com/jaudiger/brioche-packages/blob/9afeba281e554ee1eefef388f1ed35d457617466/packages/go/project.bri) didn't have any live update methods. They were added later. All of that will be reworked soon with new std helpers for live updates. I began to work on it locally.
```bash
> brioche run -e liveUpdate -p packages/git
Build finished, completed 1 job in 10.22s
{
"name": "git",
"version": "2.50.0"
}
> brioche run -e liveUpdate -p packages/go
Build finished, completed (no new jobs) in 9.74s
{ …
```

chore: always target the GitHub tags API when retrieving the latest tags

---

packages/pv/brioche.lock
packages/pv/project.bri

Resolve the issue with `pv` recipe detected during the last [live update run](https://github.com/brioche-dev/brioche-packages/actions/runs/15779487892). The URL used has been changed. This PR reflects it.
```bash
> brioche run -e liveUpdate -p packages/pv
Build finished, completed (no new jobs) in 14.32s
{
"name": "pv",
"version": "1.9.31"
}
```

fix(pv): resolve issue with live update

---

packages/biome/brioche.lock
packages/biome/project.bri

Same as with https://github.com/brioche-dev/brioche-packages/pull/706, but for `biome` recipe. It fixes an issue detected during the last [live update run](https://github.com/brioche-dev/brioche-packages/actions/runs/15779487892).
```bash
> brioche build -e test -p packages/biome
158932 │ Version: 2.0.1
0.17s ✓ Process 158932
Build finished, completed 1 job in 6.31s
Result: 000d513d952648874c489520e9db99494a6c91c074555e794cf19259b79b2415
> brioche run -e liveUpdate -p packages/biome
{
"name": "biome",
"version": "2.0.1",
"repository": "https://github.com/biomejs/biome.git"
}
```

fix(biome): resolve live update issue

---

packages/gperf/brioche.lock
packages/gperf/project.bri

Add a new package `gperf` that is already part of the `std.toolchain` but this one is more recent.
```bash
> brioche build -e test -p packages/gperf
Build finished, completed (no new jobs) in 1.81s
Result: 6bf146e63d0dcf3294d11f48b2e06c036fe1a6e260501405b2305f21f12b04e4
> brioche run -e liveUpdate -p packages/gperf
Build finished, completed (no new jobs) in 9.59s
{
"name": "gperf",
"version": "3.3"
}
```

feat(gperf): add package

---

packages/sqlx_cli/brioche.lock
packages/sqlx_cli/project.bri

Add a new package [`sqlx_cli`](https://github.com/launchbadge/sqlx/tree/main): a Rust SQL Toolkit.
Tested in a native aarch64 VM 🚀
```bash
{
"name": "sqlx_cli",
"version": "v0.8.6",
"repository": "https://github.com/launchbadge/sqlx"
}
```
```bash
Build finished, completed (no new jobs) in 1.87s
Result: 263e22d099a7cdf9c5f36d01df1a9b2de83bf767675daa9c5609fd6e8509a560
```

feat(sqlx_cli): add package

---

.github/workflows/_build.yml

This PR updates the artifact naming when `events.bin.zst` files are uploaded for failed GitHub Actions build jobs. This ensures that multiple jobs failing in the workflow will use unique artifact names. I also chose to add the job ID to the name, which will make it so each download should have a unique name (which will make it easier to find in my downloads folder!)
This resolves an issue when both the aarch64 and x86-64 build fail, since they both would try to use the same artifact name, which would conflict. See [Live Update#447](https://github.com/brioche-dev/brioche-packages/actions/runs/15944050614/job/44975857146) as an example:

Tweak process event artifact naming for failed GH Actions jobs

---

packages/gengetopt/brioche.lock
packages/gengetopt/project.bri

Add a new package [`gengetopt`](https://www.gnu.org/software/gengetopt/gengetopt.html): a tool to write command line option parsing code for C programs.
```bash
61357  │ GNU gengetopt 2.23
│ Copyright (C) 1999-2011  Free Software Foundation Inc.
│ This program comes with ABSOLUTELY NO WARRANTY; for details
│ please see the file 'COPYING' supplied with the source code.
│ This is free software, and you are welcome to redistribute it
│ under certain conditions; again, see 'COPYING' for details.
│ This program is released under the GNU General Public License.
0.02s ✓ Process 61357
Build finished, completed 1 job in 1.44s
Result: afc3b228f23e9979542b3a58d90204db7f39e546a44b5603739498ca68f21be3
```
```bash
Build finished, completed 7 jobs in …
```

feat(gengetopt): add package

---

packages/std/extra/index.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri
packages/std/extra/live_update/from_npm_packages.bri
packages/std/extra/live_update/index.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/std/extra/live_update/scripts/live_update_from_gitlab_releases.nu
packages/std/extra/live_update/scripts/live_update_from_npm_packages.nu

This PR refactors a bit the live update feature that lives in the `std` package. First all the live update methods are moved inside a new folder to better segment the files hierarchy and to not raise the number of files inside one `std.extra` directory. Second, all the Nushell scripts have been extracted into normal Nu files. The advantages of that is: we can now use the usual Nu LSP to work on Nu scripts and we can even run the Nu scripts as standalone scripts to debug them if needed (of course a preliminary environment would need to be setup to at least set all the environment variables the scripts required).
I wanted to rework that before updating and adding new live update methods.

refactor(std): move live update methods into a new folder

---

packages/tinycbor/brioche.lock
packages/tinycbor/project.bri

Add a new package `tinycbor`:
```bash
Build finished, completed (no new jobs) in 0.82s
Result: 14bd58c4b9fa0eb117e8a487d5b0b36102a26300dfd3b45d3eba8939eef48b6a
```
```bash
Build finished, completed (no new jobs) in 6.08s
{
"name": "tinycbor",
"version": "0.6.1",
"repository": "https://github.com/intel/tinycbor.git"
}
```

feat(tinycbor): add package

---

packages/kubectl_view_allocations/brioche.lock
packages/kubectl_view_allocations/project.bri

Add a new package [`kubectl_view_allocations`](https://github.com/davidB/kubectl-view-allocations): a kubectl plugin to list allocations
```bash
0.02s ✓ Process 35617
Build finished, completed 1 job in 9.01s
{
"name": "kubectl_view_allocations",
"version": "0.22.1",
"repository": "https://github.com/davidB/kubectl-view-allocations.git"
}
```
```bash
Build finished, completed (no new jobs) in 2.38s
Result: 0c0dcfa7fbca07c94361d846a7f2ed3b6a871c8887f52ac5fb9124d4d2d16b79
```

feat(kubectl_view_allocations): add package

---

packages/dagger/brioche.lock
packages/dagger/project.bri

Add a new package [`dagger`](https://github.com/dagger/dagger): an open-source runtime for composable workflows. Great for AI agents and CI/CD
```bash
Build finished, completed (no new jobs) in 0.91s
Result: f89e1507ae6053965e184078ebc8cbc23cc44bdfb2627c07bdfabaa9f645be6f
```
```bash
Build finished, completed (no new jobs) in 6.41s
{
"name": "dagger",
"version": "0.18.12",
"repository": "https://github.com/dagger/dagger.git"
}
```

feat(dagger): add package

---

packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri
packages/std/extra/live_update/from_npm_packages.bri

~~Improve the stack trace when the field `repo` is missing and the live update method is executed.~~ Improve the detection when the field `repo` is missing by ensuring to detect it during static checking. The [previous behavior](https://github.com/brioche-dev/brioche-packages/pull/786/commits/bfb06bdc7b96bccd76f0216649217d4a1c0b5681) which was relying on the nullability check wasn't that easy to implement without modifying the way the constant variable `project` is cast to `LiveUpdateFromGithubReleasesOptions` or `LiveUpdateFromGitlabReleasesOptions`.
Before:
```bash
Error: error when calling liveUpdate
Caused by:
TypeError: Cannot read properties of undefined (reading 'match')
at tryParseGithubRepo (file:///Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages/packages/std …
```

chore(live-update): better handle when the field `repo` is not present

---

packages/cosign/project.bri
packages/github_cli/project.bri
packages/golangci_lint/project.bri
packages/process_compose/project.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/std/extra/live_update/scripts/live_update_from_gitlab_releases.nu
packages/std/extra/live_update/scripts/live_update_from_npm_packages.nu
packages/vegeta/project.bri

This PR enhances the GitHub release live update capabilities to also update the release date when the package relies on it in its recipe. With this PR, 3 packages are still using a custom GitHub release implementation:
- curl
- expat
- icu
Bu the good news is we want from 8 custom implementations to now 3. Of course, I'm not counting here the custom implementations we have for GitHub tags, these implementations will be refactored later with a new live update method.
Talking back of GitHub release, all the remaining packages using a custom implementation relies on specific version representation (dash, hyphen, underscore). We could, in a future work, add it to the std GitHub release live update.

Update automatically GitHub release date

---

packages/nushell/nushell_runnable.bri
packages/nushell/project.bri
packages/nushell/run_nushell.bri
packages/std/extra/bash_runnable.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri
packages/std/extra/live_update/from_npm_packages.bri
packages/std/extra/live_update/index.bri

Closes #220
This PR adds 2 new utility functions in the `nushell` package:
- `runNushell` - Takes a Nushell script (called as a tagged template function) that returns a Process recipe to run a Nushell script. Similar to `std.runBash`.
- `nushellRunnable` - Takes a Nushell script (as a tagged template function or with a string or file recipe) that returns a runnable to run a Nushell recipe. Similar to `std.bashRunnable`.
Example:
```typescript
import { runNushell } from "nushell";
export default function() {
return runNushell`
echo hello | save $env.BRIOCHE_OUTPUT
`;
}
```
I made it so `nushellRunnable` can take the script by calling it as a tagged template function, or by passing the script directly (as a string or as a file). After #781, the live update scripts in `std` were moved to …

[nushell] Add `runNushell` and `nushellRunnable` utils

---

packages/nodejs/brioche.lock
packages/nodejs/project.bri
packages/pnpm/project.bri
packages/renovate/brioche.lock
packages/renovate/project.bri

Closes #747
This PR makes some major changes to how the `renovate` package is built:
- Fetch Renovate via GitHub instead of via the npm registry. The version in the registry doesn't have a lockfile (which we need to make the build pure).
- Install Renovate deps with `pnpmInstall` so pnpm lockfile is respected (see #783).
- Update Renovate to use Node.js v22. This is the version locked in Renovate's lockfile, and it seems that Node.js v24 doesn't work today.
- I believe Node.js v24 might be blocked by an issue in `tsx`? I _think_ it might be this: https://github.com/privatenumber/tsx/issues/694
- To handle Node.js v22 and v24, I updated `nodejs` to support passing a major version number, similar to Python. Some functions in `npm` and `pnpm` were also updated to be able to take a custom …

[renovate] Update Renovate to install via pnpm + GitHub + Node.js v22

---

packages/nushell/run_nushell.bri
packages/std/extra/run_bash.bri

Follow-up to https://github.com/brioche-dev/brioche-packages/pull/787#discussion_r2190797578 to fix the doc comment example for the new `runNushell` function. While looking at this, I also noticed that the example for `std.runBash` was also broken!

Fix doc comment examples for `runBash` and `runNushell`

---

packages/libunistring/brioche.lock
packages/libunistring/project.bri

Add a new package [`libunistring`](https://www.gnu.org/software/libunistring/): it provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.
```bash
Build finished, completed (no new jobs) in 0.77s
Result: 0d8e188ce16ea77c9e261dcdeb8a422445821c4419d6f8f5971a414a414c89e0
```
```bash
Build finished, completed 1 job in 6.81s
{
"name": "libunistring",
"version": "1.3"
}
```

feat(libunistring): add package

---

packages/curl/project.bri
packages/difftastic/project.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/std/extra/live_update/scripts/live_update_from_gitlab_releases.nu

Add a version normalizer for GitHub and GitLab live update releases. This new capability will be used with the following packages:
- curl (this PR)
- expat (will be done in an upcoming PR)
- icu (will be done in an upcoming PR)
`expat` and `icu` require project version formatter to convert `X.Y.Z` to either `X-Y-Z` or `X_Y_Z`. I'm planning to add a new std helper to convert a package version. Why this approach instead of simply using a one line function in each package ?
1. Factorize the code inside a common package (here std)
2. Later we could add function to extract sub part of a version (this is sometimes needed in testing package function, ie: `libcap`)

Add live update version normalizer

---

packages/nodejs/brioche.lock
packages/nodejs/project.bri
packages/python/project.bri

We now also support Node.js 20 version in addition to 22 and 24 (per https://nodejs.org/en/about/previous-releases, that's all the current supported versions).
Also we now properly test each Node.js to make sure the installation went well.
```bash
Build finished, completed (no new jobs) in 6.47s
{
"name": "nodejs",
"version": "24.4.0",
"extra": {
"currentMajorVersion": "24",
"majorVersions": {
"24": "24.4.0",
"22": "22.17.0",
"20": "20.19.3"
}
}
}
```
```bash
Build finished, completed (no new jobs) in 0.75s
Result: 9de45ffdb2439747bab26d8c50cb6683405abd2b3d9d1d8f889e1fc2eba081b0
```

Add nodejs supported versions

---

packages/eigen/brioche.lock
packages/eigen/project.bri

Add a new package [`eigen`](https://gitlab.com/libeigen/eigen): a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
```bash
INFO run_build: brioche::run: updated lockfiles num_lockfiles_updated=1
0.01s ✓ Process 27261
Build finished, completed 1 job in 7.03s
{
"name": "eigen",
"version": "3.4.0",
"repository": "https://gitlab.com/libeigen/eigen.git"
}
```
```bash
27956  │ 3.4.0
0.01s ✓ Process 27956
Build finished, completed 1 job in 1.69s
Result: cd0a15baa375125f5ae280872e4501d7a8f21840139a99bfb306f34f93ef5b8f
```

feat(eigen): add package

---

packages/expat/project.bri
packages/icu/project.bri
packages/std/extra/index.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri
packages/std/extra/live_update/from_npm_packages.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/std/extra/live_update/scripts/live_update_from_gitlab_releases.nu
packages/std/extra/project_version/format.bri
packages/std/extra/project_version/index.bri

Finally finish what was began in https://github.com/brioche-dev/brioche-packages/pull/785 and https://github.com/brioche-dev/brioche-packages/pull/791.
This PR removes the remaining GitHub release custom live update implementation (found in `icu` and `expat)`. `https://api.github.com/repos/.../releases/latest` can now only be found in the Nushell script of the GitHub release live update. Meaning all the API call for checking the latest release available make use of the GitHub token (at least in the CI), reducing the API throttling, etc.
Also part of this PR, there are new methods in the std package to manipulate the project version:
- `std.projectVersionToDashFormat`
- `std.projectVersionToUnderscoreFormat`
As the name implies, they convert the project version to a specific format. All …

Project version formatting

---

packages/git/project.bri

Since the git invocation commands was done through a single call, we can now switch to `std.process()` instead of using `std.runBash()`. It better enforces the process isolation, I think.

refactor(git): use std.process() instead of std.runBash() for gitCheckout()

---

packages/nodejs/project.bri
packages/std/extra/live_update/from_npm_packages.bri

Just fix a small typo I introduced

fix(npm): resolve typo `a npm` -> `an npm`

---

packages/wasm_pack/brioche.lock
packages/wasm_pack/project.bri

Add a new package [`wasm_pack`](https://github.com/rustwasm/wasm-pack): a tool seeks to be a one-stop shop for building and working with rust- generated WebAssembly that you would like to interop with JavaScript, in the browser or with Node.js.
```bash
Result: 475b5725abd013f21512efda0727a9c6305d92e405736fd0796c1a3a58b371f8
```
```bash
Build finished, completed (no new jobs) in 11.76s
{
"name": "wasmtime",
"version": "0.13.1",
"repository": "https://github.com/rustwasm/wasm-pack.git"
}
```

feat(wasm_pack): add package

---

packages/rust/project.bri

Sometimes the upstream source of a Rust package does not contain any `Cargo.lock` file which is not recommended, since we cannot ensure build reproducibility. I think, we should try generating the lock file when we encounter such rust packages. It's more a workaround, and usually this issue should be fixed upstream.
Here is a list of packages for example that do not contain any lock files:
- https://github.com/taiki-e/cargo-hack
- https://github.com/taiki-e/cargo-llvm-cov
- https://github.com/taiki-e/cargo-minimal-versions
- https://github.com/taiki-e/cargo-no-dev-deps

feat(rust): generate `Cargo.lock` when the file does not exist in the upstream source

---

packages/cargo_hack/brioche.lock
packages/cargo_hack/project.bri
packages/std/extra/live_update/from_rust_crates.bri
packages/std/extra/live_update/index.bri
packages/std/extra/live_update/scripts/live_update_from_rust_crates.nu
packages/std/extra/project_version/format.bri

~~Wait until #834 is merged.~~
Add a new package [`cargo_hack`](https://github.com/taiki-e/cargo-hack): a Cargo subcommand to provide various options useful for testing and continuous integration.
```bash
Build finished, completed (no new jobs) in 2.17s
Result: f0cab01f713139ac464e21b3a723df823b5d19a8d708cb0f23b202bb5639ebc2
```
```bash
Build finished, completed (no new jobs) in 7.73s
{
"name": "cargo_hack",
"version": "0.6.37",
"repository": "https://github.com/taiki-e/cargo-hack.git"
}
``

Add cargo hack

---

packages/cargo_llvm_cov/brioche.lock
packages/cargo_llvm_cov/project.bri
packages/std/extra/live_update/from_rust_crates.bri
packages/std/extra/live_update/index.bri
packages/std/extra/live_update/scripts/live_update_from_rust_crates.nu
packages/std/extra/project_version/format.bri

~~Wait until #834 is merged.~~
Add a new package [`cargo_llvm_cov`](https://github.com/taiki-e/cargo-llvm-cov): a Cargo subcommand to easily use LLVM source-based code coverage (-C instrument-coverage)
```bash
Build finished, completed (no new jobs) in 2.15s
Result: b04823e9d3dcacfad4916f190b48ac85679f100d2488357c73ba3138244bd21e
```
```bash
Build finished, completed (no new jobs) in 7.81s
{
"name": "cargo_llvm_cov",
"version": "0.6.17",
"repository": "https://github.com/taiki-e/cargo-llvm-cov.git"
}
```

Add cargo llvm cov

---

packages/freetype/brioche.lock
packages/freetype/project.bri

Add a new package [`freetype`](https://freetype.org): a software library to render fonts
```bash
Build finished, completed 2 jobs in 9.24s
{
"name": "freetype",
"version": "2.13.3"
}
```
```bash
Build finished, completed 1 job in 1.87s
Result: 50012dd35a586b57a72c0cfc12b1ce433d34b5a918deb671782c2ef82cb4808f
```

feat(freetype): add package

---

packages/cargo_minimal_versions/brioche.lock
packages/cargo_minimal_versions/project.bri

Add a new package [`cargo_minimal_versions`](https://github.com/taiki-e/cargo-minimal-versions): a Cargo subcommand for proper use of -Z minimal-versions and -Z direct-minimal-versions.
```bash
Build finished, completed (no new jobs) in 2.46s
Result: 6b15de0079e0d7aebc3566578054e658e54f49d55f4196ce92ae18f4beec0180
```
```bash
Build finished, completed (no new jobs) in 7.84s
{
"name": "cargo_minimal_versions",
"version": "0.1.31",
"extra": {
"crateName": "cargo-minimal-versions"
}
}
```

feat(cargo_minimal_versions): add package

---

packages/cargo_no_dev_deps/brioche.lock
packages/cargo_no_dev_deps/project.bri

Add a new package [`cargo_no_dev_deps`](https://github.com/taiki-e/cargo-no-dev-deps): a Cargo subcommand for running cargo without dev-dependencies.
```bash
Build finished, completed (no new jobs) in 8.54s
{
"name": "cargo_no_dev_deps",
"version": "0.2.16",
"extra": {
"crateName": "cargo-no-dev-deps"
}
}
```
```bash
Result: c7c65d553e2c6893fa70669dc1357aab92a47f6a8eed4f388875dc22280a3230
```

feat(cargo_no_dev_deps): add package

---

packages/font_iosevka/brioche.lock
packages/font_iosevka/project.bri

howdy! thanks for sharing this project! <3
i've had an attempt at putting together a font package, for https://typeof.net/Iosevka/
`brioche install iosevka` here will install the font files in ~/.local/share/brioche/installed/share/fonts
after `brioche install ...` i then made a link so that ~/.local/share/fonts/brioche is symlinked to ~/.local/share/brioche/installed/share/fonts , and then ran `fc-cache -fv`
that isn't so different to having to add ~/.local/share/brioche/installed/bin to PATH, but it's not great either
i'm just not sure if that UX can be improved (and surely if users get this far they can figure out either fontconfig's settings or how to create symlinks :)
anyhow, let me know what you think!

feat(iosevka): 📦️ add font package

---

packages/binaryen/project.bri
packages/biome/project.bri
packages/cargo_audit/project.bri
packages/cargo_nextest/project.bri
packages/codex/project.bri
packages/curl/project.bri
packages/cyrus_sasl/project.bri
packages/expat/project.bri
packages/icu/project.bri
packages/jq/project.bri
packages/libevent/project.bri
packages/llvm/project.bri
packages/nginx/project.bri
packages/openssl/project.bri
packages/pcre2/project.bri
packages/php/project.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_gitlab_releases.bri

Switch from regex `/^(?<version>.*)$/` to `/^(?<version>.+)$/`. I made the choice of using `+` since we want "one or more characters" and not "zero or more characters". The current regex could suggest that an empty string is valid for a version.

chore(live-update): better default for matchTag in std.liveUpdateFromGithubReleases()

---

packages/wasm_tools/brioche.lock
packages/wasm_tools/project.bri

Add a new package [`wasm_tools`](https://github.com/bytecodealliance/wasm-tools): a CLI and Rust libraries for low-level manipulation of WebAssembly modules
```bash
Build finished, completed (no new jobs) in 8.29s
{
"name": "wasm_tools",
"version": "1.235.0",
"extra": {
"crateName": "wasm-tools"
}
}
```
```bash
Build finished, completed (no new jobs) in 2.35s
Result: d007e1db5686c76ec66c86c9cc3905f8e3fd41713760bcfce8a806c8edaf413d
```

feat(wasm_tools): add package

---

packages/iperf3/brioche.lock
packages/iperf3/project.bri

This PR adds a package for [iperf3](https://github.com/esnet/iperf), a TCP, UDP, and SCTP network bandwidth measurement tool

Add `iperf3` package

---

packages/wasm_bindgen_cli/brioche.lock
packages/wasm_bindgen_cli/project.bri

Add a new package [`wasm_bindgen_cli`](https://github.com/rustwasm/wasm-bindgen): this package facilitates high-level interactions between Wasm modules and JavaScript.
```bash
Build finished, completed (no new jobs) in 9.04s
{
"name": "wasm_bindgen_cli",
"version": "0.2.100",
"extra": {
"crateName": "wasm-bindgen-cli"
}
}
```
```bash
Build finished, completed (no new jobs) in 2.73s
Result: 5d878cf90c3fb16802bccde903f7b9656b75d6117c38d80dc034682b99bec2a3
```

feat(wasm_bindgen_cli): add package

---

packages/actionlint/brioche.lock
packages/actionlint/project.bri

Add a new package [`actionlint`](https://github.com/rhysd/actionlint): a static checker for GitHub Actions workflow files
```bash
Build finished, completed 1 job in 9.17s
{
"name": "actionlint",
"version": "1.7.7",
"repository": "https://github.com/rhysd/actionlint.git"
}
```
```bash
Build finished, completed (no new jobs) in 0.80s
Result: 44f741a604eaa1449254dc8b68254889a241477a07b21efb93dd3e3bff722187
```

feat(actionlint): add package

---

packages/cargo_binstall/brioche.lock
packages/cargo_binstall/project.bri

Add a new package [`cargo_binstall`](https://github.com/cargo-bins/cargo-binstall): binary installation for rust projects.
```bash
Build finished, completed (no new jobs) in 2.61s
Result: 43577aaba7452f21306fe9f3c9dc912e2feb1bf9ceba967ee54a5892858230bc
```
```bash
Build finished, completed (no new jobs) in 8.71s
{
"name": "cargo_binstall",
"version": "1.14.1",
"extra": {
"crateName": "cargo-binstall"
}
}
```

feat(cargo_binstall): add package

---

packages/wrangler/brioche.lock
packages/wrangler/project.bri

Add a new package [`wrangler`](https://github.com/cloudflare/workers-sdk): a command line tool for building [Cloudflare Workers](https://workers.cloudflare.com/).
```bash
0.01s ✓ Process 334318
Build finished, completed 1 job in 9.35s
{
"name": "wrangler",
"version": "4.25.1",
"extra": {
"packageName": "wrangler"
}
}
```
```bash
Build finished, completed (no new jobs) in 8.62s
Result: 5408bb4f5946b0c935e76405671aa98cbf7d4c17d7b19c7995d13f3f7e2b128e
```

feat(wrangler): add package

---

packages/cargo_quickinstall/brioche.lock
packages/cargo_quickinstall/project.bri

Add a new package [`cargo_quickinstall`](https://github.com/cargo-bins/cargo-quickinstall):  pre-compiled binary packages for `cargo install`
```bash
Build finished, completed (no new jobs) in 9.83s
{
"name": "cargo_quickinstall",
"version": "0.3.22",
"extra": {
"crateName": "cargo-quickinstall"
}
}
```
```bash
Build finished, completed (no new jobs) in 3.61s
Result: 8602134e9b171fc8ec955f37c096dc11a2b662e8ed083423437749d4e0c69585
```

feat(cargo_quickinstall): add package

---

packages/fribidi/brioche.lock
packages/fribidi/project.bri

Add a new package [`fribidi`](https://github.com/fribidi/fribidi): a Free Implementation of the Unicode Bidirectional Algorithm
```bash
Build finished, completed (no new jobs) in 9.81s
{
"name": "fribidi",
"version": "1.0.16",
"repository": "https://github.com/fribidi/fribidi"
}
```
```bash
Build finished, completed (no new jobs) in 0.89s
Result: 1984c98f02e559d1896e575debd824abddc1cdfb9f1458381d05b62367e2f0a1
```

feat(fribidi): add package

---

packages/aws_cli/project.bri
packages/boost/project.bri
packages/git/project.bri
packages/joshuto/project.bri
packages/moreutils/project.bri
packages/nasm/project.bri
packages/rpcsvc_proto/project.bri
packages/s2argv_execs/project.bri
packages/tokei/project.bri
packages/uthash/project.bri
packages/vdeplug4/project.bri

Just to keep consistency in our packages

chore: always using `project.repository` variable when retrieving sources from GitHub

---

packages/aws_cli/brioche.lock
packages/joshuto/brioche.lock
packages/nasm/brioche.lock
packages/s2argv_execs/brioche.lock
packages/tokei/brioche.lock
packages/uthash/brioche.lock
packages/vdeplug4/brioche.lock

Follow up of https://github.com/brioche-dev/brioche-packages/pull/918. I missed the update of `brioche.lock` files.

fix: update outdated lockfile due to git references update

---

packages/asciinema/project.bri
packages/aws_cli/project.bri
packages/boost/project.bri
packages/cargo_bloat/project.bri
packages/git/project.bri
packages/go/project.bri
packages/joshuto/project.bri
packages/nasm/project.bri
packages/pyrefly/project.bri
packages/rust/project.bri
packages/s2argv_execs/project.bri
packages/sqlx_cli/project.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_github_tags.bri
packages/std/extra/live_update/github_global.bri
packages/std/extra/live_update/index.bri
packages/std/extra/live_update/scripts/live_update_from_github_tags.nu
packages/tokei/project.bri
packages/uthash/project.bri
packages/vdeplug4/project.bri
packages/zziplib/project.bri

As discussed earlier, here is the new `std.liveUpdateFromGithubTags()` helper for live update check through GitHub tags. The interface is pretty similar to `std.liveUpdateFromGithubReleases()`. I tweaked the previous Nushell script to make it easier to filter per tag:
```nu
http get https://api.github.com/repos/asciinema/asciinema/git/matching-refs/tags
| get ref
| each {|ref|
$ref
| parse --regex '^refs/tags/v(?P<tag>(?P<major>[\\d]+)\\.(?P<minor>[\\d]+)\\.(?P<patch>[\\d]+))$'
| get -o 0
}
| sort-by -n major minor patch
http get https://api.github.com/repos/asciinema/asciinema/git/matching-refs/tags
| get ref
| each {|ref|
$ref
| str substring 10..-1
| parse --regex $env.matchTag
| get -o 0
}
| sort-by --natural version
```
One package wasn't updated, that's `nodejs` since we handle …

Add GitHub tags live update

---

packages/vacuum/brioche.lock
packages/vacuum/project.bri

Add a new package [`vacuum`](https://github.com/daveshanley/vacuum): fast OpenAPI 3, OpenAPI 2 / Swagger linter and quality analysis tool.
```bash
Build finished, completed (no new jobs) in 0.95s
Result: 9bee4b7597eecb5c79bc65a4e76e55045dadb41979dc57a9911f078429855d5b
```
```bash
Build finished, completed 1 job in 11.32s
{
"name": "vacuum",
"version": "0.17.6",
"repository": "https://github.com/daveshanley/vacuum.git"
}
```

feat(vacuum): add package

---

packages/cargo_spellcheck/brioche.lock
packages/cargo_spellcheck/project.bri

Add a new package [`cargo_spellcheck`](https://github.com/drahnr/cargo-spellcheck): checks all your documentation for spelling and grammar mistakes with hunspell and a nlprule based checker for grammar.
```bash
{
"name": "cargo_spellcheck",
"version": "0.15.5",
"extra": {
"crateName": "cargo-spellcheck"
}
}
```
```bash
Build finished, completed (no new jobs) in 3.01s
Result: 660b71d8bdb98c5bec7a898c521329cf190dfe947bd5918b7eb3b12af90ea37a
```

feat(cargo_spellcheck): add package

---

packages/renovate/project.bri

[Node.js v22.18.0](https://nodejs.org/en/blog/release/v22.18.0) was released on Thursday, and today we had a live-update PR to update to this new version in the `nodejs` package (#944). The build failed (but was inadvertently auto-merged; see #963).
Here was the error from the build:
```
> renovate@0.0.0-semantic-release create-json-schema /home/brioche-runner-d15ac752d340eb70693ad58ede3dbb3feb13280b3297f2cd5bbe1688c16689bb/work
> tsx tools/generate-schema.ts && prettier --write --cache 'renovate-schema.json'
/home/brioche-runner-d15ac752d340eb70693ad58ede3dbb3feb13280b3297f2cd5bbe1688c16689bb/work/lib/modules/manager/bazel-module/extract.ts:1
import { dirname } from 'upath';
^
SyntaxError: The requested module 'upath' does not provide an export named 'dirname'
at ModuleJob._instantiate …
```

[renovate] Work around failing build with Node.js v22.18.0

---

packages/renovate/project.bri

Simply reformat the Nushell embedded script found in the `renovate` recipe

chore(renovate): reformat Nushell embedded script

---

packages/libxcrypt/brioche.lock
packages/libxcrypt/project.bri

Add a new package [`libxcrypt`](https://github.com/besser82/libxcrypt) already part of std but with a newer release and less restrictions in its building options.
```bash
Build finished, completed (no new jobs) in 7.71s
{
"name": "libxcrypt",
"version": "4.4.38",
"repository": "https://github.com/besser82/libxcrypt"
}
```
```bash
Build finished, completed (no new jobs) in 0.75s
Result: 14737d74043482ebebb93c62afcdbbb68b17abf82000e5ff6bc782a6a3862671
```

feat(libxcrypt): add package

---

packages/hunspell/brioche.lock
packages/hunspell/project.bri

Add a new package [`hunspell`](https://github.com/hunspell/hunspell): a spellchecking library.
```bash
Build finished, completed (no new jobs) in 0.96s
Result: 8c7def9d723638ba82af84ec60ecab3decbf0cbdce883919f4583666afede12d
```
```bash
Build finished, completed (no new jobs) in 7.74s
{
"name": "hunspell",
"version": "1.7.2",
"repository": "https://github.com/hunspell/hunspell"
}
```

feat(hunspell): add package

---

packages/xorgproto/brioche.lock
packages/xorgproto/project.bri

Add a new package [`xorgproto`](https://gitlab.freedesktop.org/xorg/proto/xorgproto): provides the headers and specification documents defining
the core protocol and (many) extensions for the X Window System
```bash
Build finished, completed (no new jobs) in 0.76s
Result: c97ee1074bde800ac2c363dd745f82681a19639c4bfc878ef0fde195a66f2f1c
```
```bash
{
"name": "xorgproto",
"version": "2024.1"
}
```

feat(xorgproto): add package

---

packages/asciinema/project.bri
packages/boost/project.bri
packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/index.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/tokei/project.bri

`std.liveUpdateFromGithubReleases()` does now fetch all the releases as its name suggests: 'releaseS' and not 'latestRelease'. As of today, this function was only retrieving the latest GitHub Release for a package but it caused issues in the past since for a few packages. It can happen that the latest release is not a final release (see https://github.com/asciinema/asciinema/releases/tag/v3.0.0-rc.5 for example). This PR does not necessarily resolved this specific issue, since `std.liveUpdateFromGithubReleases()` and `std.liveUpdateFromGithubTags()` (without `matchTag` overriding) will both return the wrong tag -> the real issue comes from the maintainers not having tagged properly the tag v3.0.0-rc.5 as a pre-release. But now, we can move from `std.liveUpdateFromGithubTags()` to …

Update live update GitHub releases

---

packages/kor/brioche.lock
packages/kor/project.bri

The inspiration of this PR was taken from https://github.com/brioche-dev/brioche-packages/pull/1004/commits/b8eb598e5e35d08515e199d3bf59ae6563a3b84f

chore(kor): use variable `project.repository` when fetching the patch

---

.github/workflows/_build.yml

**Blocked**: Cannot merge until https://github.com/brioche-dev/brioche/pull/294 is merged and included in a nightly build
This PR uses the new `--experimental-lazy` flag` (https://github.com/brioche-dev/brioche/pull/294) when calling `brioche build` in our GitHub Actions workflows.
Hopefully, this will help speed up our workflows, since it'll let us short-circuit calls to `brioche build` when we can determine that the build result has already been saved in the remote cache.

Use `--experimental-lazy` option when running builds in GitHub Actions

---

packages/std/extra/pkg_config_make_paths_relative.bri
packages/std/toolchain/native/index.bri

This PR tweaks the script transforming pkg-config paths to relative paths by removing a leading `/` that is not necessary. In practice, it should change nothing, since both path construction point to the same location. It's just to ensure well-constructed paths. Here is a comparison for `alsa_lib` package:
```bash
> cat /tmp/output/lib/pkgconfig/alsa.pc
prefix=${pcfiledir}/../../
exec_prefix=${pcfiledir}/../../
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: alsa
Description: Advanced Linux Sound Architecture (ALSA) - Library
Version: 1.2.14
Requires:
Libs: -L${libdir} -lasound
Libs.private: -lm -lpthread -lrt
Cflags: -I${includedir}
```
The following pkg-configs are not well-constructed:
```bash
libdir = ${pcfiledir}/../..//lib
includedir=${pcfiledir}/../..//include
``` …

chore(pkgConfig): tweak the recipe to make paths relative

---

packages/rust/project.bri

Move from gzip to xz archives compression for Rust toolchain. It can saved between 30-40% in download size when building the Rust toolchain, due to higher compression ratio using xz.
```bash
172560 │ rustc 1.89.0 (29483883e 2025-08-04)
0.05s ✓ Process 172560
Build finished, completed 1 job in 1.63s
Result: d061736ebcd489ce544fd212cb13a1e305c039b2dfd2feb37230ff63a211033e
```
Also move from process decompression to usual Brioche decompression methods. The problem with `rust-docs` seems to be resolved.

build(rust): Update package to use xz decompression for toolchain archives

---

packages/xtrans/brioche.lock
packages/xtrans/project.bri

Add a new package [`xtrans`](https://www.x.org/releases/X11R7.7/doc/xtrans/xtrans.html): a library of code that is shared among various X packages to handle network protocol transport in a modular fashion, allowing a single place to add new transport types.
```bash
Build finished, completed (no new jobs) in 0.79s
Result: 3c8d20634dc8b220ae420e85fb99e42455ab298838cfef24ab62a9f5e298af9a
```
```bash
{
"name": "xtrans",
"version": "1.6.0"
}
```

feat(xtrans): add package

---

packages/deno/brioche.lock
packages/deno/project.bri
packages/rust/project.bri

Closes #336 
This PR adds a package for [Deno](https://github.com/denoland/deno), a modern runtime for JavaScript and TypeScript.
Thanks to @rawkode and @nz366 for work-in-progress code towards Deno! This PR started from https://github.com/brioche-dev/brioche-packages/issues/336#issuecomment-3146436138 as a base and grew from there. A few notes:
- I needed to set `$LD_LIBRARY_PATH` during the build. Something (I think bindgen?) dynamically loads `libclang`, which failed by default due to not finding standard libraries like `libz.so.1`-- setting `$LD_LIBRARY_PATH` resolves this.
- I set an env var to pass the Rust flag `-Clink-arg=-fuse-ld=bfd`, which switches to using `ld.bfd` instead of `ld.gold`. The Deno build uses the linker option `--export-dynamic-symbol-list` (see …

Add `deno` package

---

packages/libsm/brioche.lock
packages/libsm/project.bri

Add a new package [`libsm`](https://www.x.org/releases/X11R7.7/doc/libSM/SMlib.html): the X Session Management Protocol (XSMP) is to provide a uniform mechanism for users to save and restore their sessions.
```bash
{
"name": "libsm",
"version": "1.2.6"
}
```
```bash
Build finished, completed (no new jobs) in 0.81s
Result: ed23977807711a5b8a29a2e5cf6350b0573444f56cb4902483e6fd692c189fba
```

feat(libsm): add package

---

packages/libxc/brioche.lock
packages/libxc/project.bri

Add a new package [`libxc`](https://x.org/releases/current/doc/libX11/libX11/libX11.html): Xlib is a C subroutine library that application programs (clients) use to interface with the window system by means of a stream connection.
```bash
Build finished, completed (no new jobs) in 7.90s
{
"name": "libxc",
"version": "7.0.0",
"repository": "https://gitlab.com/libxc/libxc.git"
}
```
```bash
Build finished, completed (no new jobs) in 0.93s
Result: 2299509fc71b796f489786b7b9039cc53a424e92710f7a97b6dfafc7c4010c01
```

feat(libxc): add package

---

packages/coturn/brioche.lock
packages/coturn/project.bri

This PR adds a package for [coturn](https://github.com/coturn/coturn), a free open source implementation of TURN and STUN Server.
This includes basic support, with just `libevent` and `openssl` as dependencies. coturn also optionally supports Prometheus, SQLite, Postgres, and MySQL which aren't enabled in this PR (we have packages for SQLite and Postgres today, but the CMake build didn't pick them up automatically when added as dependencies). Personally, I mainly added this to be able to use the various TURN utils included by default, so I haven't really tried the main server very thoroughly.

Add `coturn` package

---

packages/aws_cli/project.bri

New output when testing the recipe:
```bash
129786 │ aws-cli/2.28.15 Python/3.13.1 Linux/6.8.0-71-generic source/aarch64
0.95s ✓ Process 129786
Build finished, completed 1 job in 2.85s
Result: 4908d009e49e34b7b6feaec82f5729d9c108123522db5c89a3af43b4193fdf3c
```

Update awscli recipe

---

packages/mutagen/brioche.lock
packages/mutagen/project.bri

This PR adds a package for [Mutagen](https://github.com/mutagen-io/mutagen), a tool for fast file synchronization and network forwarding for remote development.
I considered building it using `goBuild`, but it seemed like a pretty tall order to also build the agent bundle, considering the set of platforms they support out-of-the-box:
- `darwin_amd64`
- `darwin_arm64`
- `freebsd_amd64`
- `linux_amd64`
- `linux_arm64`
- `windows_amd64`
(It's not hard to compile all of these in Go, but we don't have very many options for cross-compilation yet)
They provide a simple build script under `scripts/build.go`, which is [the recommended way to build Mutagen](https://github.com/mutagen-io/mutagen/blob/03c982a3a34e1dfe496f4bcd4ee7ced34307db68/BUILDING.md), so I decided to just use that for the build. …

Add `mutagen` package

---

packages/keep_sorted/brioche.lock
packages/keep_sorted/project.bri

This PR adds [keep-sorted](https://github.com/google/keep-sorted) which has a need to use [git] as a dependency during go build to pull the commit information. Also it relies on knowing the current tag in order to create the version command accordingly.

add package keep-sorted

---

packages/nushell/run_nushell.bri
packages/std/extra/run_bash.bri

Resolve a typo seen in TSDoc comments of `nushellRunnable` and `bashRunnable`

fix: resolve a typo in TSDoc comments

---

packages/asciinema/brioche.lock
packages/asciinema/project.bri
packages/meson/brioche.lock
packages/meson/project.bri

Nothing else than just updating `setuptools` and `wheels` when building `meson` and `asciinema` packages.

build: update Python building dependencies for meson and asciinema

---

packages/std/core/utils.bri

It improves the error message for the unreachable function.
Before this modification, the message printed when an object was injected in this function was: `reached unreachable code with value: [Object object]`. Now this function will stringily the object before to print it.

chore(std): improve unreachable function error message

---

packages/std/extra/live_update/from_github_releases.bri
packages/std/extra/live_update/from_github_tags.bri
packages/std/extra/live_update/scripts/live_update_from_github_releases.nu
packages/std/extra/live_update/scripts/live_update_from_github_tags.nu

This PR updates `std.liveUpdateFromGithubTags()` and `std.liveUpdateFromGithubReleases()` to handle multiple versions for a single recipe. It'll be as simple as just updating the `project` variable to include the other possible versions as it's done in the `python` recipe:
```ts
export const project = {
name: "python",
version: "3.13.1",
repository: "https://github.com/python/cpython",
extra: {
otherVersions: {
"3.13": "3.13.1",
"3.12": "3.12.8",
},
},
};
```
Everything will be handled behind the scene when calling `std.liveUpdateFromGithubTags()` and `std.liveUpdateFromGithubReleases()`. The versions will be scraped from the Github API and only the most recent versions will be kept per supported version.

Add the ability to update multiple versions for a recipe

---

packages/nodejs/project.bri

Similar to #1104, we can now make use of the updated `std.liveUpdateFromGithubReleases()` method to check all the supported versions of `nodejs` recipe:
```bash
Build finished, completed (no new jobs) in 8.18s
{
"name": "nodejs",
"version": "24.7.0",
"repository": "https://github.com/nodejs/node",
"extra": {
"otherVersions": {
"24": "24.7.0",
"22": "22.19.0",
"20": "20.19.4"
}
}
}
```

refactor(nodejs): update live update by using std method

---

packages/libxdmcp/brioche.lock
packages/libxdmcp/project.bri

Add a new package [`libxdmcp`](https://www.x.org/releases/X11R7.6/doc/libXdmcp/xdmcp.html): library providing a uniform mechanism for an autonomous display to request login service from a remote host.
```bash
Build finished, completed (no new jobs) in 13.64s
{
"name": "libxdmcp",
"version": "1.1.5"
}
```
```bash
Build finished, completed (no new jobs) in 1.03s
Result: 138324da257150d31ec242e96a2b2ede4a6d4f9a8c891aed582f381b3e9b8b2a
```

feat(libxdmcp): add package

---

packages/cmake/project.bri
packages/wabt/project.bri

In order to resolve the recently issue with `llvm` recipe (#1124), due to building in a not writable directory:
```bash
[3h 0m35s] [100%] Linking CXX shared library ../../../../lib/liblldb.so
[3h 0m37s] Traceback (most recent call last):
[3h 0m37s]   File "/home/brioche-runner-c9b0b24f22bf3645600bd6801f4dbe9fb01c175235bd99be6a7c76af4346d78c/.local/share/brioche/locals/01cef55de38da0d1b29aaac3f1dbd80d07922094f29de52b3b1512f54b119b8e/lldb/scripts/version-header-fix.py", line 62, in <module>
[3h 0m37s]     main()
[3h 0m37s]     ~~~~^^
[3h 0m37s]   File "/home/brioche-runner-c9b0b24f22bf3645600bd6801f4dbe9fb01c175235bd99be6a7c76af4346d78c/.local/share/brioche/locals/01cef55de38da0d1b29aaac3f1dbd80d07922094f29de52b3b1512f54b119b8e/lldb/scripts/version-header-fix.py", line 36, in main
[3h …
```

Update cmakeBuild method to use workDir

---

packages/tree_sitter/brioche.lock
packages/tree_sitter/project.bri

Add a new package [`tree_sitter`](https://github.com/tree-sitter/tree-sitter): an incremental parsing system for programming tools
```bash
Build finished, completed 1 job in 10.44s
{
"name": "tree_sitter",
"version": "0.25.8",
"repository": "https://github.com/tree-sitter/tree-sitter"
}
``` 
```bash
Result: 515dc7e953be68b2c6a5c681fc6978d1a0c19e51ef9a8828c353842f423460a0
```

feat(tree_sitter): add package

---

packages/usage/brioche.lock
packages/usage/project.bri

Add a new package [`usage`](https://github.com/jdx/usage): a spec and CLI for defining CLI tools
```bash
{
"name": "usage",
"version": "2.2.2",
"repository": "https://github.com/jdx/usage.git"
}
```
```bash
Build finished, completed (no new jobs) in 2.55s
Result: 04321ffcb04b537ecbe9412f28c5db6ce5649aba596c8b07dd0568fcb19bd9e3
```

feat(usage): add package

---

packages/igrep/brioche.lock
packages/igrep/project.bri

Add a new package [`igrep`](https://github.com/konradsz/igrep): an interactive grep
```bash
Build finished, completed (no new jobs) in 2.21s
Result: cd690538180ca2b6e1f23be1c3d32a7a15fb3193d42fd0dad9644f9739b29d6f
```
```bash
{
"name": "igrep",
"version": "1.3.0",
"repository": "https://github.com/konradsz/igrep.git"
}
```

feat(igrep): add package

---

packages/alsa_lib/project.bri
packages/cyrus_sasl/project.bri
packages/fribidi/project.bri
packages/gengetopt/project.bri
packages/gperf/project.bri
packages/isl/project.bri
packages/libfaketime/project.bri
packages/libice/project.bri
packages/libpcap/project.bri
packages/libpng/project.bri
packages/libpsl/project.bri
packages/libsm/project.bri
packages/libsodium/project.bri
packages/libssh2/project.bri
packages/libxau/project.bri
packages/libxdmcp/project.bri
packages/libyaml/project.bri
packages/lzop/project.bri
packages/ncurses/project.bri
packages/patch/project.bri
packages/readline/project.bri
packages/tcpdump/project.bri
packages/util_macros/project.bri
packages/xorgproto/project.bri
packages/xtrans/project.bri

For reference: https://github.com/brioche-dev/brioche-packages/discussions/230
I tested each recipe one by one by running `brioche build -e test -p packages/RECIPE` to ensure no regression happened. On my machine (MacBook Pro with M1 CPU), `nproc` returns 8. I can definitively see the build improvement here in the updated recipes, the build time is most of the time significantly reduced.

refactor(recipes): add missing make commands when building packages

---

packages/eslint/brioche.lock
packages/eslint/project.bri

Add a new package [`eslint`](https://eslint.org): The pluggable linting utility for JavaScript and JSX
```bash
Build finished, completed (no new jobs) in 11.71s
Result: 64a1be47d14ecafe112ce55d6bb086c08f0d09464cc31640217d6cc077fa4431
```
```bash
{
"name": "eslint",
"version": "9.34.0",
"extra": {
"packageName": "eslint"
}
}
```

feat(eslint): add package

---

packages/cmake/project.bri
packages/pstack/project.bri

As mentioned in #1194, this PR is the final work on parallel build in our recipe when using `make` or `cmake` tools. By default for `cmakeBuild()`, parallel build will be enabled, if for a recipe we need to disable it, I updated the TSDoc of this function to state that we only need to set `CMAKE_BUILD_PARALLEL_LEVEL` to `1`.
We can still customise (override) the number of jobs used by CMake by setting this env var as we continue to do in:
- binaryen
- libxc
- llvm
For `pstack`, I removed/unset the env var since the building is fast enough (less than 30s) with 8 threads (on my computer).

Improve cmake building

---

packages/libxml2/project.bri
packages/llvm/project.bri
packages/nuspell/project.bri

Rewrite the `libxml2` recipe to use the modern CMake tool building. No difference should be seen when using the library.

Rewrite libxml2 recipe

---

packages/traefik/brioche.lock
packages/traefik/project.bri

Add a new package [`traefik`](https://traefik.io): Traefik is your all-in-one, self-hosted, cloud-native, GitOps-driven application proxy, API gateway, and API management platform.
```bash
{
"name": "traefik",
"version": "3.5.2",
"repository": "https://github.com/traefik/traefik",
"extra": {
"majorVersion": 3
}
}
```
```bash
Build finished, completed (no new jobs) in 0.97s
Result: 5154604143aa1fa8a5db12a392f354fc8ab44e3c32dfd8b947f3007e3f71d1a8
```

feat(traefik): add package

---

packages/terraform_docs/brioche.lock
packages/terraform_docs/project.bri

Add a new package [`terraform_docs`](https://github.com/terraform-docs/terraform-docs): Generate documentation from Terraform modules in various output formats
```bash
Build finished, completed (no new jobs) in 1.34s
Result: 7ef9f5b026da7a742b8792fb2efe8bf2cbdc3d4db09f7866451ac6936f45c2b1
```
```bash
Build finished, completed (no new jobs) in 10.88s
{
"name": "terraform_docs",
"version": "0.20.0",
"repository": "https://github.com/terraform-docs/terraform-docs.git"
}
```

feat(terraform_docs): add package

---

packages/go_task/brioche.lock
packages/go_task/project.bri

Add a new package `go_task`:
```bash
brioche run -e liveUpdate -p packages/go_task/
0.02s ✓ Process 92108
Build finished, completed 1 job in 9.49s
{
"name": "go_task",
"version": "3.45.4",
"repository": "https://github.com/go-task/task.git",
"extra": {
"majorVersion": "3"
}
}
```
```bash
brioche build -e test -p packages/go_task/
Build finished, completed (no new jobs) in 0.90s
Result: 7521377fdaaf5d7200ec6ec9da1ed41b2614fce95cd1434d05fadf93b2b6c548
```

feat(go_task): add package

---

packages/tenv/brioche.lock
packages/tenv/project.bri

Add a new package [`tenv`](https://github.com/tofuutils/tenv): OpenTofu / Terraform / Terragrunt / Terramate and Atmos version manager
```bash
Build finished, completed 1 job in 9.28s
{
"name": "tenv",
"version": "4.7.21",
"repository": "https://github.com/tofuutils/tenv.git"
}
```
```bash
Build finished, completed (no new jobs) in 0.92s
Result: 82296a3bdba262f21965cdfb9b823702c2331ba52c96401ce3a2b3763fbcf5f8
```

feat(tenv): add package

---

packages/ncurses/project.bri

Without:
```bash
> ls /tmp/output/lib/
libformw.a   libformw.so.6    libmenuw.a   libmenuw.so.6    libncurses++w.a   libncurses++w.so.6    libncursesw.a   libncursesw.so.6    libpanelw.a   libpanelw.so.6    pkgconfig
libformw.so  libformw.so.6.5  libmenuw.so  libmenuw.so.6.5  libncurses++w.so  libncurses++w.so.6.5  libncursesw.so  libncursesw.so.6.5  libpanelw.so  libpanelw.so.6.5  terminfo
```
With:
```bash
> ls /tmp/output/lib/
libformw.a   libformw.so.6    libmenuw.a   libmenuw.so.6    libncurses++w.a   libncurses++w.so.6    libncursesw.a   libncursesw.so.6    libpanelw.a   libpanelw.so.6    libtinfow.a   libtinfow.so.6    pkgconfig
libformw.so  libformw.so.6.5  libmenuw.so  libmenuw.so.6.5  libncurses++w.so  libncurses++w.so.6.5  libncursesw.so  libncursesw.so.6.5  libpanelw.so …
```

chore(ncurses): add --with-termlib to configure options

---

packages/std/extra/index.bri
packages/std/extra/libtool_sanitize_dependencies.bri
packages/std/toolchain/native/acl.bri

Add a new std function (inspired from the post process of `acl` recipe of the std toolchain) to ensure libtool files do not contain absolute deps path inside the variable `dependency_libs`. I discovered all of that by working on packaging `libx11` locally (and it now work 🚀), but I first need to upstream a few updates around `libxau` and `libxcb` to make use of the new std method related to libtool files.
Before:
```bash
> cat /tmp/output/lib/libxcb-composite.la
#
dlname='libxcb-composite.so.0'
library_names='libxcb-composite.so.0.0.0 libxcb-composite.so.0 libxcb-composite.so'
old_library='libxcb-composite.a'
inherited_linker_flags=''
dependency_libs=' //lib/libxcb.la -L/home/brioche-runner-eaf315e60b9ee608cdcfe57271bb2c755cbe20586c1aebceafe6f992958ff40c/.local/share/brioche/locals/7030701 …
```

Add a new std function to ensure libtool files do not contain absolute deps path

---

packages/jq/project.bri
packages/kmod/project.bri
packages/postgresql/project.bri
packages/scdoc/project.bri

See https://github.com/brioche-dev/brioche-packages/pull/1286 for context. This PR adds the missing calling to `std.pkgConfigMakePathsRelative` where the recipe contains a pkgconfig folder.
This PR is interesting for `scdoc`, since it's used by `kmod` which is in turn used by `linux` recipe.

Tweak pkgconfig files

---

packages/libxpm/brioche.lock
packages/libxpm/project.bri

Add a new package `libxpm`: this package contains the X PixMap library. XPM (X PixMap) is a format for storing and retrieving X pixmaps to and from files.
```bash
Build finished, completed 1 job in 10.56s
{
"name": "libxpm",
"version": "3.5.17"
}
```
```bash
Build finished, completed 6 jobs in 19.68s
Result: 63fd1f03f2613170dc1213c4b61ca2fcb0a4aa099dc333875c8676f8126a93cb
```

feat(libxpm): add package

---

packages/cargo_tarpaulin/brioche.lock
packages/cargo_tarpaulin/project.bri

Add a new package [`cargo_tarpaulin`](https://github.com/xd009642/tarpaulin): a code coverage tool for Rust projects
```bash
Build finished, completed 1 job in 10.35s
{
"name": "cargo_tarpaulin",
"version": "0.32.8",
"extra": {
"crateName": "cargo-tarpaulin"
}
}
```
I wasn't able to generate the output for testing, but it was working yesterday. I'm having network issues right now (since I'm on my mobile network, and for some reasons I can't access the crates.io API through my mobile network...):
```bash
63018  │     Updating crates.io index
│ warning: spurious network error (3 tries remaining): [28] Timeout was reached (Connection timed out after 30014 milliseconds)
│ warning: spurious network error (2 tries …
```

feat(cargo_tarpaulin): add package

---

.github/workflows/live-updates.yml

The [last "Live updates" workflow run](https://github.com/brioche-dev/brioche-packages/actions/runs/18038375041) failed to create PRs for live-updates. The "Push branches" step failed with a bunch of errors like this:
```
Creating PR for live-update/aws_cdk
remote: {"auth_status":"auth_error","body":"Invalid username or token. Password authentication is not supported for Git operations."}
fatal: Authentication failed for 'https://github.com/brioche-dev/brioche-packages.git/'
Error: Failed to push live-update/aws_cdk
Creating PR for live-update/aws_cli
remote: {"auth_status":"auth_error","body":"Invalid username or token. Password authentication is not supported for Git operations."}
fatal: Authentication failed for 'https://github.com/brioche-dev/brioche-packages.git/'
Error: Failed to …
```

Update "Live updates" workflow to refresh GitHub app token

---

packages/libxmu/brioche.lock
packages/libxmu/project.bri

Add a new package [`libxmu`](https://www.x.org/releases/X11R7.7/doc/libXmu/Xmu.html): a collection of miscellaneous (some might say random) utility functions that have been useful in building various applications and widgets. This library is required by the Athena Widgets.
```bash
{
"name": "libxmu",
"version": "1.2.1"
}
```
```bash
Build finished, completed (no new jobs) in 1.72s
Result: 533ab8419757ea9170f559b09f12537dde6c5a83e08b41bbdf9939779808757a
```

feat(libxmu): add package

---

packages/ck_search/brioche.lock
packages/ck_search/project.bri

Add a new package [`ck_search`](https://github.com/BeaconBay/ck): Local first semantic and hybrid BM25 grep / search tool for use by AI and humans
```bash
Build finished, completed (no new jobs) in 13.60s
{
"name": "ck_search",
"version": "0.5.3",
"extra": {
"crateName": "ck-search"
}
}
```
```bash
Build finished, completed (no new jobs) in 5.15s
Result: 0310594206ad25a37108f14d822026eebb7ced99c8f4f3461f53ecc9a018d861
```

feat(ck_search): add package

---

packages/libxfixes/brioche.lock
packages/libxfixes/project.bri

Add a new package [`libxfixes`](https://www.x.org/releases/X11R7.6/doc/man/man3/Xfixes.3.xhtml): a simple library designed to interface the X Fixes Extension. This extension provides application with work arounds for various limitations in the core protocol.
```bash
Build finished, completed (no new jobs) in 12.61s
{
"name": "libxfixes",
"version": "6.0.2"
}
```
```bash
Build finished, completed (no new jobs) in 1.19s
Result: 89022b7044c460b13ae51956b88cdc4345a2db3a0edfde1f76d38f7b116b9077
```

feat(libxfixes): add package

---

packages/cargo_expand/brioche.lock
packages/cargo_expand/project.bri

Add a new package [`cargo_expand`](https://github.com/dtolnay/cargo-expand): a subcommand to show result of macro expansion.
```bash
Build finished, completed (no new jobs) in 13.02s
{
"name": "cargo_expand",
"version": "1.0.117",
"extra": {
"crateName": "cargo-expand"
}
}
```
```bash
Build finished, completed (no new jobs) in 4.43s
Result: 385e2cd6bf034610a96f27d6a5b31868adb306bc31d4ef51ddab6efa41e9c5e9
```

feat(cargo_expand): add package

---

packages/bubblewrap/project.bri

It was unused by the build process of bubblewrap.

build(bubblewrap): remove CMake dependency from the build process

---

packages/nasm/brioche.lock
packages/nasm/project.bri

By using directly the archive from the repository, it simplifies the build process of nasm. 
Bonus point: with the usage of `make install`, we now have two binaries available when installing this recipe:
```bash
> ls /tmp/output/bin/
nasm  ndisasm
```

refactor(nasm): update recipe to use download instead of git checkout

---

.github/workflows/_build.yml
.github/workflows/_check.yml
.github/workflows/live-updates.yml
.github/workflows/publish.yml

Based on top of #1393.
Similar to https://github.com/brioche-dev/brioche/pull/317.
Following the release of https://github.com/brioche-dev/setup-brioche/releases/tag/v1.4.0, we can now make use of the latest capability of the Brioche GitHub Action in the CI to streamline the installation of Brioche.

[CI] Use GitHub Action to install Brioche nightly

---

packages/libxi/brioche.lock
packages/libxi/project.bri

Add a new package [`libxi`](https://x.org/releases/X11R7.7/doc/libXi/inputlib.html): a library for the X Input Extension.
```bash
Build finished, completed 11 jobs in 45.88s
Result: 3f122b72902789273f2439b9928bad9992270e91ebeb790ad04788af9258807a
```
```bash
Build finished, completed 6 jobs in 49.47s
{
"name": "libxi",
"version": "1.8.2"
}
```

feat(libxi): add package

---

packages/std/extra/live_update/scripts/live_update_from_gitlab_releases.nu

This PR improves the Nushell script we are using to extract and sort GitLab releases based on a regex pattern. This ensures the latest matching release is used for updates.
Resolves https://github.com/brioche-dev/brioche-packages/issues/1390.
The issue was detected first with `eigen` recipe during the last live update checking:
Before the PR:
```bash
{
"name": "eigen",
"version": "3.4.1",
"repository": "https://gitlab.com/libeigen/eigen.git"
}
```
After the PR:
```bash
{
"name": "eigen",
"version": "5.0.0",
"repository": "https://gitlab.com/libeigen/eigen.git"
}
```

feat(gitlab): improve the script to retrieve and process multiple releases from GitLab

---

packages/cargo_llvm_lines/brioche.lock
packages/cargo_llvm_lines/project.bri

Add a new package [`cargo_llvm_lines`](https://github.com/dtolnay/cargo-llvm-lines): count lines of LLVM IR per generic function.
```bash
{
"name": "cargo_llvm_lines",
"version": "0.4.45",
"extra": {
"crateName": "cargo-llvm-lines"
}
}
```
```bash
Build finished, completed 2 jobs in 5.56s
Result: 7e321787a894d9780c32412d49005619e2cc9a5cf53898f7fe10275d63ef3f58
```

feat(cargo_llvm_lines): add package

---

packages/libxtst/brioche.lock
packages/libxtst/project.bri

Add a new package [`libxtst`](https://www.x.org/releases/X11R7.7/doc/libXtst/xtestlib.html): this extension is a minimal set of client and server extensions required to completely test the X11 server with no user intervention.
```bash
{
"name": "libxtst",
"version": "1.2.5"
}
```
```bash
Build finished, completed (no new jobs) in 2.59s
Result: f199e8bfbfd5186a08acb30143c3b61239754196f4d472fbab2dc9e2562a3912
```

feat(libxtst): add a new package
